if (typeof MAZOS === 'undefined') { var MAZOS = []; }

MAZOS.push({
  id: "literatura",
  name: "Literatura y Premios Nobel",
  icon: "📚",
  questions: [
    // ROSCO 1 - PREMIOS NOBEL Y CLÁSICOS
    {q: "Con la A: Apellido del autor de 'La Regenta', obra cumbre del naturalismo.", a: "Alas", letra: "A"},
    {q: "Con la B: Autor romántico español de las 'Rimas'.", a: "Bécquer", letra: "B"},
    {q: "Con la C: Seudónimo de Leopoldo Alas, autor de 'La Regenta'.", a: "Clarín", letra: "C"},
    {q: "Con la D: Autor ruso de 'Crimen y castigo'.", a: "Dostoievski", letra: "D"},
    {q: "Con la E: Nobel de Literatura español, gran dramaturgo de 'El gran Galeoto'.", a: "Echegaray", letra: "E"},
    {q: "Con la F: Nobel estadounidense autor de 'El ruido y la furia'.", a: "Faulkner", letra: "F"},
    {q: "Con la G: Gran autor chino Nobel de 2000, autor de 'La montaña del alma'.", a: "Gao Xingjian", letra: "G"},
    {q: "Con la H: Nobel alemán autor de 'Siddhartha' y 'El lobo estepario'.", a: "Hesse", letra: "H"},
    {q: "Con la I: Apellido del dramaturgo noruego autor de 'Casa de muñecas'.", a: "Ibsen", letra: "I"},
    {q: "Con la J: Único Nobel de Literatura español nacido en Moguer, autor de 'Platero y yo'.", a: "Jiménez", letra: "J"},
    {q: "Con la K: Apellido del autor checo de 'La metamorfosis'.", a: "Kafka", letra: "K"},
    {q: "Con la L: Nobel sueca de 1909, autora de 'Jerusalén'.", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel colombiano, máximo exponente del realismo mágico (García ___).", a: "Márquez", letra: "M"},
    {q: "Con la N: Nobel chileno autor de 'Veinte poemas de amor y una canción desesperada'.", a: "Neruda", letra: "N"},
    {q: "Contiene la Ñ: Novelista chileno autor de '2666' y 'Los detectives salvajes'.", a: "Bolaño", letra: "Ñ"},
    {q: "Con la O: Nombre de pila del Nobel mexicano de apellido Paz.", a: "Octavio", letra: "O"},
    {q: "Con la P: Nobel mexicano autor de 'El laberinto de la soledad'.", a: "Paz", letra: "P"},
    {q: "Con la Q: Obra cumbre de Miguel de Cervantes, hito de la novela moderna.", a: "Quijote", letra: "Q"},
    {q: "Con la R: Nobel francés de 1915 y gran pacifista (Romain ___).", a: "Rolland", letra: "R"},
    {q: "Con la S: Apellido del Nobel polaco autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "S"},
    {q: "Con la T: Nobel ruso autor de 'Guerra y Paz' y 'Ana Karenina'.", a: "Tolstoi", letra: "T"},
    {q: "Con la U: Nobel noruega autora de 'Cristina hija de Lavrans' (Sigrid ___).", a: "Undset", letra: "U"},
    {q: "Con la V: Gran poeta latino autor de 'La Eneida'.", a: "Virgilio", letra: "V"},
    {q: "Con la W: Dramaturgo irlandés autor de 'La importancia de llamarse Ernesto'.", a: "Wilde", letra: "W"},
    {q: "Contiene la X: Nobel bielorrusa autora de 'Voces de Chernóbil'.", a: "Alexiévich", letra: "X"},
    {q: "Con la Y: Nobel irlandés autor de 'La torre' (William Butler ___).", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Autor francés del naturalismo, autor de 'Germinal' y 'Nana'.", a: "Zola", letra: "Z"},

    // ROSCO 2 - TERMINOLOGÍA FILOLÓGICA (PARA NOEMÍ)
    {q: "Con la A: Palabra que tiene el acento en la última sílaba.", a: "aguda", letra: "A"},
    {q: "Con la B: Composición poética de ocho versos octosílabos con rima asonante.", a: "balada", letra: "B"},
    {q: "Con la C: Estrofa de cuatro versos de arte mayor con rima ABBA.", a: "cuarteto", letra: "C"},
    {q: "Con la D: Licencia métrica que deshace un diptongo para formar dos sílabas.", a: "Diéresis", letra: "D"},
    {q: "Con la E: Verso que consta de once sílabas métricas.", a: "endecasílabo", letra: "E"},
    {q: "Con la F: Antología de textos selectos de diversos autores.", a: "florilegio", letra: "F"},
    {q: "Con la G: Categoría en la que se clasifican las obras literarias.", a: "género", letra: "G"},
    {q: "Con la H: Figura que consiste en exagerar la realidad de forma desmesurada.", a: "hipérbole", letra: "H"},
    {q: "Con la I: Figura que consiste en dar a entender lo contrario de lo que se dice.", a: "ironía", letra: "I"},
    {q: "Con la J: Composición lírica popular mozárabe de finales de la estrofa.", a: "jarcha", letra: "J"},
    {q: "Con la K: Apellido del autor alemán del drama 'La marquesa de O' (Heinrich von ___).", a: "Kleist", letra: "K"},
    {q: "Con la L: Narración breve de hechos imaginarios.", a: "leyenda", letra: "L"},
    {q: "Con la M: Identificación de un objeto con otro por semejanza.", a: "metáfora", letra: "M"},
    {q: "Con la N: Relato literario de ficción, extenso y en prosa.", a: "novela", letra: "N"},
    {q: "Contiene la Ñ: Lengua romance en la que escribió Cervantes.", a: "español", letra: "Ñ"},
    {q: "Con la O: Palabra que lleva el acento en la última sílaba.", a: "oxítona", letra: "O"},
    {q: "Con la P: Empleo de palabras innecesarias para intensificar el sentido.", a: "pleonasmo", letra: "P"},
    {q: "Con la Q: Figura sintáctica que cruza el orden de los elementos de dos secuencias.", a: "Quiasmo", letra: "Q"},
    {q: "Con la R: Repetición de sonidos al final de dos o más versos.", a: "rima", letra: "R"},
    {q: "Con la S: Composición poética de 14 versos: dos cuartetos y dos tercetos.", a: "soneto", letra: "S"},
    {q: "Con la T: Estrofa de tres versos de arte mayor que suelen rimar ABA.", a: "terceto", letra: "T"},
    {q: "Con la U: Relato que describe una sociedad ideal e imaginaria.", a: "utopía", letra: "U"},
    {q: "Con la V: Unidad rítmica de amplitud variable, propia de ciertos textos bíblicos y modernos.", a: "versículo", letra: "V"},
    {q: "Con la W: Término de Goethe para designar la literatura universal.", a: "Weltliteratur", letra: "W"},
    {q: "Contiene la X: Palabra acentuada en la última sílaba.", a: "Oxítona", letra: "X"},
    {q: "Contiene la Y: Figura que atribuye rasgos humanos a seres inanimados.", a: "Prosopopeya", letra: "Y"},
    {q: "Con la Z: Género dramático español que mezcla canto y texto hablado.", a: "zarzuela", letra: "Z"},

    // ROSCO 3 - NOBEL DE LITERATURA MÍTICOS
    {q: "Con la A: Nobel español de 1977, autor de 'La destrucción o el amor'.", a: "Aleixandre", letra: "A"},
    {q: "Con la B: Nobel irlandés autor de 'Esperando a Godot'.", a: "Beckett", letra: "B"},
    {q: "Con la C: Político y Nobel de Literatura de 1953 por sus memorias de guerra.", a: "Churchill", letra: "C"},
    {q: "Con la D: Nobel estadounidense que sorprendió al ganar como músico y poeta.", a: "Dylan", letra: "D"},
    {q: "Con la E: Nobel francesa de 2022, autora de 'Los años'.", a: "Ernaux", letra: "E"},
    {q: "Con la F: Nobel italiano autor de 'Muerte accidental de un anarquista'.", a: "Fo", letra: "F"},
    {q: "Con la G: Nobel sudafricana autora de 'La historia de mi hijo'.", a: "Gordimer", letra: "G"},
    {q: "Con la H: Nobel estadounidense autor de 'El viejo y el mar'.", a: "Hemingway", letra: "H"},
    {q: "Con la I: Nobel británico de origen japonés autor de 'Lo que queda del día'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Nobel austriaca autora de 'La pianista' (Elfriede ___).", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel británico autor de 'El libro de la selva'.", a: "Kipling", letra: "K"},
    {q: "Con la L: Nobel sueca, primera mujer en ganar el premio (Selma ___).", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel alemán autor de 'La montaña mágica'.", a: "Mann", letra: "M"},
    {q: "Con la N: Nobel británico nacido en Trinidad, autor de 'Un recodo en el río'.", a: "Naipaul", letra: "N"},
    {q: "Contiene la Ñ: Novelista chileno autor de '2666' y 'Los detectives salvajes'.", a: "Bolaño", letra: "Ñ"},
    {q: "Con la O: Nobel estadounidense autor de 'Largo viaje hacia la noche' (Eugene ___).", a: "O'Neill", letra: "O"},
    {q: "Con la P: Nobel italiano autor de 'Seis personajes en busca de autor'.", a: "Pirandello", letra: "P"},
    {q: "Con la Q: Nobel italiano de 1959, gran poeta del hermetismo.", a: "Quasimodo", letra: "Q"},
    {q: "Con la R: Filósofo y Nobel de Literatura británico autor de 'Historia de la filosofía'.", a: "Russell", letra: "R"},
    {q: "Con la S: Nobel polaco autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "S"},
    {q: "Con la T: Nobel indio autor de 'Gitanjali'.", a: "Tagore", letra: "T"},
    {q: "Con la U: Nobel noruega autora de 'Cristina hija de Lavrans'.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel peruano autor de 'La tía Julia y el escribidor'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la W: Nobel de 1992, poeta y dramaturgo caribeño autor de 'Omeros'.", a: "Walcott", letra: "W"},
    {q: "Contiene la X: Nobel chino de 2000, autor de 'La montaña del alma'.", a: "Xingjian", letra: "X"},
    {q: "Con la Y: Nobel irlandés de 1923, autor de 'La torre'.", a: "Yeats", letra: "Y"},
    {q: "Contiene la Z: Nobel polaca autora de 'Fin y principio'.", a: "Szymborska", letra: "Z"},

    // ROSCO 4 - LITERATURA UNIVERSAL Y TÉCNICA
    {q: "Con la A: Texto atribuido falsamente a un autor o de autenticidad dudosa.", a: "apócrifo", letra: "A"},
    {q: "Con la B: Movimiento cultural del XVII caracterizado por el exceso y el pesimismo.", a: "Barroco", letra: "B"},
    {q: "Con la C: Corriente narrativa que retrata tipos, usos y ambientes cotidianos.", a: "costumbrismo", letra: "C"},
    {q: "Con la D: Apellido del autor de 'Oliver Twist' y 'Cuento de Navidad'.", a: "Dickens", letra: "D"},
    {q: "Con la E: Tragedia de Sófocles sobre el rey de Tebas.", a: "Edipo", letra: "E"},
    {q: "Con la F: Autor de 'Los pilares de la Tierra' (Ken ___).", a: "Follett", letra: "F"},
    {q: "Con la G: Poema épico mesopotámico considerado el más antiguo conservado.", a: "Gilgamesh", letra: "G"},
    {q: "Con la H: Autor de la 'Odisea' y la 'Ilíada'.", a: "Homero", letra: "H"},
    {q: "Con la I: Autor de 'Lo que queda del día' y Nobel de 2017.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Autor irlandés de 'Ulises', hito de la vanguardia.", a: "Joyce", letra: "J"},
    {q: "Con la K: Autor checo de 'El proceso'.", a: "Kafka", letra: "K"},
    {q: "Con la L: El 'Fénix de los Ingenios', gran dramaturgo del Siglo de Oro.", a: "Lope de Vega", letra: "L"},
    {q: "Con la M: Obra clásica de Herman Melville sobre una ballena blanca.", a: "Moby Dick", letra: "M"},
    {q: "Con la N: Género literario al que pertenece la obra 'La Regenta'.", a: "Novela", letra: "N"},
    {q: "Contiene la Ñ: Palabra que cierra el título de la tragedia calderoniana 'La vida es ...'.", a: "sueño", letra: "Ñ"},
    {q: "Con la O: Nombre del autor de '1984' y 'Rebelión en la granja' (George ___).", a: "Orwell", letra: "O"},
    {q: "Con la P: Autor de 'El cuervo' y maestro del terror.", a: "Poe", letra: "P"},
    {q: "Con la Q: Apellido del autor de 'El buscona' y gran rival de Góngora.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Apellido de la autora de Harry Potter.", a: "Rowling", letra: "R"},
    {q: "Con la S: Apellido del autor de 'Romeo y Julieta'.", a: "Shakespeare", letra: "S"},
    {q: "Con la T: Ciudad griega donde reina el protagonista de la tragedia de Sófocles.", a: "Tebas", letra: "T"},
    {q: "Con la U: Movimiento de vanguardia que buscaba la ruptura total con el pasado.", a: "Ultraísmo", letra: "U"},
    {q: "Con la V: Segundo apellido de Garcilaso, autor de las 'Églogas'.", a: "Vega", letra: "V"},
    {q: "Con la W: Novelista británica autora de 'La señora Dalloway'.", a: "Woolf", letra: "W"},
    {q: "Contiene la X: Apellido del autor de 'Un mundo feliz'.", a: "Huxley", letra: "X"},
    {q: "Contiene la Y: Apellido del poeta irlandés autor de 'La torre'.", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Obra filosófico-poética de Nietzsche protagonizada por un profeta persa.", a: "Zaratustra", letra: "Z"},

    // ROSCO 5 - PREMIOS NOBEL (ÚLTIMA DÉCADA Y CLÁSICOS)
    {q: "Con la A: Apellido de la Nobel bielorrusa autora de 'Voces de Chernóbil'.", a: "Alexiévich", letra: "A"},
    {q: "Con la B: Nobel de 1925, autor irlandés de 'Pigmalión'.", a: "Bernhard Shaw", letra: "B"},
    {q: "Con la C: Apellido del Nobel español autor de 'La colmena'.", a: "Cela", letra: "C"},
    {q: "Con la D: Nobel italiano, dramaturgo de 'Muerte accidental de un anarquista'.", a: "Dario Fo", letra: "D"},
    {q: "Con la E: Nobel francesa de 2022, autora de 'El acontecimiento'.", a: "Ernaux", letra: "E"},
    {q: "Con la F: Nobel noruego de 2023, autor de 'Mañana y tarde'.", a: "Fosse", letra: "F"},
    {q: "Con la G: Nobel tanzano de 2021, autor de 'Paraíso'.", a: "Gurnah", letra: "G"},
    {q: "Con la H: Nobel austriaco de 2019, autor de 'La mujer zurda'.", a: "Handke", letra: "H"},
    {q: "Con la I: Nobel británico de origen japonés, autor de 'Klara y el Sol'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Apellido de la Nobel austriaca de 2004, autora de 'La pianista'.", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel húngaro sobreviviente del Holocausto, autor de 'Sin destino'.", a: "Kertész", letra: "K"},
    {q: "Con la L: Nobel sueca de 1909, autora de 'La saga de Gösta Berling'.", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel chino de 2012, autor de 'Sorgo rojo'.", a: "Mo Yan", letra: "M"},
    {q: "Con la N: Nobel británico nacido en Trinidad, autor de 'Un recodo en el río'.", a: "Naipaul", letra: "N"},
    {q: "Contiene la Ñ: Lengua en la que escribieron la mayoría de los autores del Siglo de Oro.", a: "español", letra: "Ñ"},
    {q: "Con la O: Nombre de pila de la Nobel polaca Tokarczuk.", a: "Olga", letra: "O"},
    {q: "Con la P: Nombre de pila del Nobel austríaco de apellido Handke.", a: "Peter", letra: "P"},
    {q: "Con la Q: Apellido del Nobel italiano de 1959, poeta del hermetismo.", a: "Quasimodo", letra: "Q"},
    {q: "Con la R: Nobel francés de 1915, autor de 'Juan Cristóbal'.", a: "Rolland", letra: "R"},
    {q: "Con la S: Nobel polaca de 1996, famosa por su poesía irónica.", a: "Szymborska", letra: "S"},
    {q: "Con la T: Nobel sueco de 2011, psicólogo y poeta.", a: "Transtromer", letra: "T"},
    {q: "Con la U: Nobel noruega de 1928, famosa por sus novelas medievales.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel peruano autor de 'Conversación en La Catedral'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la W: Nobel de 1992, autor de 'Omeros'.", a: "Walcott", letra: "W"},
    {q: "Con la X: Nobel chino de 2000, autor de 'La montaña del alma'.", a: "Xingjian", letra: "X"},
    {q: "Con la Y: Nobel irlandés de 1923, autor de 'La torre'.", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Autor francés del naturalismo, padre de la saga de los Rougon-Macquart.", a: "Zola", letra: "Z"},

    // ROSCO 6 - FILOLOGÍA Y MÉTRICA (NIVEL BOTE)
    {q: "Con la A: Palabra que designa el nombre de pila de un autor.", a: "antropónimo", letra: "A"},
    {q: "Con la B: Composición poética narrativa de carácter tradicional.", a: "Balada", letra: "B"},
    {q: "Con la C: Estrofa de cuatro versos de arte mayor con rima ABBA.", a: "cuarteto", letra: "C"},
    {q: "Con la D: Estrofa de diez versos octosílabos, también llamada espinela.", a: "décima", letra: "D"},
    {q: "Con la E: Figura que consiste en omitir un elemento que se sobreentiende.", a: "elipsis", letra: "E"},
    {q: "Con la F: Ciencia que estudia las lenguas y los textos escritos.", a: "filología", letra: "F"},
    {q: "Con la G: Poema breve de origen árabe adoptado por la lírica española contemporánea.", a: "Gacela", letra: "G"},
    {q: "Con la H: Figura que altera el orden lógico de las palabras en una frase.", a: "hipérbaton", letra: "H"},
    {q: "Con la I: Primeras palabras con las que comienza un texto antiguo.", a: "incipit", letra: "I"},
    {q: "Con la J: Estrofa lírica breve que cerraba las moaxajas árabes.", a: "jarcha", letra: "J"},
    {q: "Con la K: Apellido del autor de 'La metamorfosis', hito de la literatura existencial.", a: "Kafka", letra: "K"},
    {q: "Con la L: Nombre de la estrofa de cinco versos con rima consonante (7-11-7-7-11).", a: "lira", letra: "L"},
    {q: "Con la M: Arte de medir la estructura de los versos y sus rimas.", a: "métrica", letra: "M"},
    {q: "Con la N: Voz que cuenta los hechos en una obra narrativa.", a: "narrador", letra: "N"},
    {q: "Contiene la Ñ: Valoración breve de una obra o edición reciente.", a: "reseña", letra: "Ñ"},
    {q: "Con la O: Estrofa de ocho versos endecasílabos con rima ABABABCC.", a: "octava", letra: "O"},
    {q: "Con la P: Figura que repite conjunciones para intensificar el ritmo.", a: "Polisíndeton", letra: "P"},
    {q: "Con la Q: Estrofa de cinco versos de arte menor con rima consonante.", a: "Quintilla", letra: "Q"},
    {q: "Con la R: Poema narrativo de versos octosílabos con rima asonante en los pares.", a: "romance", letra: "R"},
    {q: "Con la S: Licencia métrica que une dos vocales fuertes en una sola sílaba.", a: "sinéresis", letra: "S"},
    {q: "Con la T: Etiqueta pegada al lomo del libro con el título y autor.", a: "tejolet", letra: "T"},
    {q: "Con la U: Movimiento de vanguardia español liderado por Cansinos Assens.", a: "ultraísmo", letra: "U"},
    {q: "Con la V: Unidad rítmica de amplitud variable, propia de ciertos textos bíblicos y modernos.", a: "versículo", letra: "V"},
    {q: "Con la W: Tipo de dicho irónico atribuido a un personaje o autoridad.", a: "Wellerismo", letra: "W"},
    {q: "Contiene la X: Palabra acentuada en la penúltima sílaba.", a: "Paroxítona", letra: "X"},
    {q: "Contiene la Y: Figura que repite la última palabra de un verso al inicio del siguiente.", a: "Anadiplosis", letra: "Y"},
    {q: "Con la Z: Figura que utiliza un solo verbo para varios sujetos complejos.", a: "zeugma", letra: "Z"},

    // ROSCO 7 - LITERATURA ESPAÑOLA (ORO PURO)
    {q: "Con la A: Poeta del 27 autor de 'Sobre los ángeles'.", a: "Alberti", letra: "A"},
    {q: "Con la B: Autor de las 'Rimas y Leyendas', máximo exponente del romanticismo tardío.", a: "Bécquer", letra: "B"},
    {q: "Con la C: Apellido del autor de 'La vida es sueño', gran dramaturgo barroco.", a: "Calderón", letra: "C"},
    {q: "Con la D: Apellido del autor de 'Cinco horas con Mario'.", a: "Delibes", letra: "D"},
    {q: "Con la E: Poeta romántico autor de la 'Canción del pirata'.", a: "Espronceda", letra: "E"},
    {q: "Con la F: Seudónimo de Mariano José de Larra.", a: "Fígaro", letra: "F"},
    {q: "Con la G: Poeta del 27, autor de 'Cántico'.", a: "Guillén", letra: "G"},
    {q: "Con la H: Apellido del autor de 'El Rayo que no cesa', el poeta cabrero.", a: "Hernández", letra: "H"},
    {q: "Con la I: Fabulista neoclásico español, autor de las 'Fábulas literarias'.", a: "Iriarte", letra: "I"},
    {q: "Con la J: Apellido del Nobel de 1956, autor de 'Platero y yo'.", a: "Jiménez", letra: "J"},
    {q: "Con la K: Filósofo alemán cuya doctrina inspiró el krausismo español.", a: "Krause", letra: "K"},
    {q: "Con la L: Obra anónima de 1554 que inició la novela picaresca.", a: "Lazarillo", letra: "L"},
    {q: "Con la M: Apellido del autor de 'Campos de Castilla'.", a: "Machado", letra: "M"},
    {q: "Con la N: Género de la obra 'Niebla' de Unamuno, según él mismo.", a: "nivola", letra: "N"},
    {q: "Contiene la Ñ: Novelista español autor de 'El jinete polaco'.", a: "Muñoz Molina", letra: "Ñ"},
    {q: "Con la O: Protagonista de 'La Regenta' de Clarín (Ana ___).", a: "Ozores", letra: "O"},
    {q: "Con la P: Apellido de la autora de 'Insolación' y 'Los pazos de Ulloa'.", a: "Pardo Bazán", letra: "P"},
    {q: "Con la Q: Gran satírico del Barroco, autor de 'El Buscón'.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Autor de 'La Celestina', de apellido de pila Fernando de ___.", a: "Rojas", letra: "R"},
    {q: "Con la S: Poeta de la Generación del 27, autor de 'La voz a ti debida'.", a: "Salinas", letra: "S"},
    {q: "Con la T: Seudónimo de Gabriel Téllez, autor de 'El burlador de Sevilla'.", a: "Tirso de Molina", letra: "T"},
    {q: "Con la U: Apellido del autor de 'San Manuel Bueno, mártir'.", a: "Unamuno", letra: "U"},
    {q: "Con la V: Autor de 'Luces de bohemia'.", a: "Valle-Inclán", letra: "V"},
    {q: "Con la W: Nombre de pila del novelista Fernández Flórez.", a: "Wenceslao", letra: "W"},
    {q: "Contiene la X: Apellido del Nobel español de 1977, autor de 'La destrucción o el amor'.", a: "Aleixandre", letra: "X"},
    {q: "Contiene la Y: Apellido del autor de 'Señas de identidad'.", a: "Goytisolo", letra: "Y"},
    {q: "Con la Z: Poeta del romanticismo español, autor de 'Don Juan Tenorio'.", a: "Zorrilla", letra: "Z"},

    // ROSCO 8 - GRANDES OBRAS UNIVERSALES (NIVEL BOTE)
    {q: "Con la A: Autor latino de 'El asno de oro'.", a: "Apuleyo", letra: "A"},
    {q: "Con la B: Autor de 'Las flores del mal'.", a: "Baudelaire", letra: "B"},
    {q: "Con la C: Novelista anglo-polaco autor de 'El corazón de las tinieblas'.", a: "Conrad", letra: "C"},
    {q: "Con la D: Autor ruso de 'Los hermanos Karamázov'.", a: "Dostoievski", letra: "D"},
    {q: "Con la E: Tragedia de Sófocles sobre el destino ineludible del hijo que mata al padre.", a: "Edipo", letra: "E"},
    {q: "Con la F: Autor francés de 'Madame Bovary'.", a: "Flaubert", letra: "F"},
    {q: "Con la G: Poema épico de la cultura sumeria, el más antiguo del mundo.", a: "Gilgamesh", letra: "G"},
    {q: "Con la H: Autor británico de 'Un mundo feliz'.", a: "Huxley", letra: "H"},
    {q: "Con la I: Autor noruego de 'Un enemigo del pueblo'.", a: "Ibsen", letra: "I"},
    {q: "Con la J: Autor irlandés de la colección de relatos 'Dublineses'.", a: "Joyce", letra: "J"},
    {q: "Con la K: Autor griego de 'Zorba el griego'.", a: "Kazantzakis", letra: "K"},
    {q: "Con la L: Novelista portuguesa autora de 'La hora de la estrella'.", a: "Lispector", letra: "L"},
    {q: "Con la M: Dramaturgo francés autor de 'Tartufo'.", a: "Molière", letra: "M"},
    {q: "Con la N: Apellido del autor de 'Lolita'.", a: "Nabokov", letra: "N"},
    {q: "Contiene la Ñ: Novelista chileno autor de '2666' y 'Los detectives salvajes'.", a: "Bolaño", letra: "Ñ"},
    {q: "Con la O: Autor de 'El retrato de Dorian Gray'.", a: "Oscar Wilde", letra: "O"},
    {q: "Con la P: Poeta ruso del Siglo de Oro, autor de 'Eugenio Oneguin'.", a: "Pushkin", letra: "P"},
    {q: "Con la Q: Caballero manchego creado por Cervantes.", a: "Quijote", letra: "Q"},
    {q: "Con la R: Nombre de pila del Nobel indio de 1913 de apellido Tagore.", a: "Rabindranath", letra: "R"},
    {q: "Con la S: Autor de 'Edipo Rey' y 'Antígona'.", a: "Sófocles", letra: "S"},
    {q: "Con la T: Autor ruso de 'La muerte de Iván Ilich'.", a: "Tolstoi", letra: "T"},
    {q: "Con la U: Héroe homérico de la 'Odisea' en su forma latina.", a: "Ulises", letra: "U"},
    {q: "Con la V: Autor de 'Cándido' y gran filósofo ilustrado.", a: "Voltaire", letra: "V"},
    {q: "Con la W: Novelista británica autora de 'Al faro'.", a: "Woolf", letra: "W"},
    {q: "Contiene la X: Apellido del autor de 'Un mundo feliz'.", a: "Huxley", letra: "X"},
    {q: "Con la Y: Poeta irlandés y Nobel de 1923.", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Autor de 'Germinal'.", a: "Zola", letra: "Z"},

    // ROSCO 9 - RETÓRICA Y MÉTRICA AVANZADA (PARA FILÓLOGOS)
    {q: "Con la A: Omisión de las conjunciones para dar rapidez a la frase.", a: "asíndeton", letra: "A"},
    {q: "Con la B: Composición poética breve que suele servir de estribillo.", a: "bordón", letra: "B"},
    {q: "Con la C: Repetición de una palabra al final de un verso y al principio del siguiente.", a: "concatenación", letra: "C"},
    {q: "Con la D: Unión en una sílaba de dos vocales que pertenecen a sílabas distintas.", a: "diéresis", letra: "D"},
    {q: "Con la E: Repetición de un verso al final de cada estrofa de un poema.", a: "estribillo", letra: "E"},
    {q: "Con la F: Reunión para contar cuentos o leer textos en voz alta.", a: "filandón", letra: "F"},
    {q: "Con la G: Repetición inmediata de una palabra en un mismo verso.", a: "geminación", letra: "G"},
    {q: "Con la H: Cada una de las dos partes de un verso separadas por una cesura.", a: "hemistiquio", letra: "H"},
    {q: "Con la I: Palabra que comienza y termina con la misma letra.", a: "isograma", letra: "I"},
    {q: "Con la J: Composición lírica popular que cierra una moaxaja.", a: "jarcha", letra: "J"},
    {q: "Con la K: En la métrica griega, cada una de las partes de un verso largo.", a: "kola", letra: "K"},
    {q: "Con la L: Figura que consiste en negar lo contrario de lo que se quiere afirmar.", a: "lítotes", letra: "L"},
    {q: "Con la M: Figura que designa una cosa con el nombre de otra por cercanía o causa.", a: "metonimia", letra: "M"},
    {q: "Con la N: Palabra inventada por un autor que no existe en el idioma.", a: "neologismo", letra: "N"},
    {q: "Contiene la Ñ: Texto breve en prosa que valora una obra recién publicada.", a: "reseña", letra: "Ñ"},
    {q: "Con la O: Verso que tiene ocho sílabas métricas.", a: "octosílabo", letra: "O"},
    {q: "Con la P: Palabra que lleva el acento en la penúltima sílaba.", a: "paroxítona", letra: "P"},
    {q: "Con la Q: Estrofa de cinco versos de arte menor con rima consonante.", a: "quintilla", letra: "Q"},
    {q: "Con la R: Estrofa de cuatro versos octosílabos con rima ABBA.", a: "redondilla", letra: "R"},
    {q: "Con la S: Figura que consiste en atribuir una sensación a un sentido que no le corresponde.", a: "sinestesia", letra: "S"},
    {q: "Con la T: Estrofa de tres versos que riman en cadena en la Divina Comedia.", a: "terceto", letra: "T"},
    {q: "Con la U: Palabra que tiene un solo significado posible.", a: "unívoca", letra: "U"},
    {q: "Con la V: Composición poética de arte menor con estribillo, típica de la lírica popular.", a: "villancico", letra: "V"},
    {q: "Con la W: Dicho ingenioso puesto en boca de un personaje real o ficticio.", a: "Wellerismo", letra: "W"},
    {q: "Contiene la X: Figura que une dos términos de significado opuesto.", a: "Oxímoron", letra: "X"},
    {q: "Contiene la Y: Figura que humaniza animales u objetos.", a: "Prosopopeya", letra: "Y"},
    {q: "Con la Z: Figura que consiste en usar un solo verbo para varios sujetos.", a: "zeugma", letra: "Z"},

    // ROSCO 10 - NOBELES OLVIDADOS O DIFÍCILES
    {q: "Con la A: Nobel guatemalteco autor de 'El señor presidente'.", a: "Asturias", letra: "A"},
    {q: "Con la B: Nobel noruego de 1903, autor de 'Sigurd Slembe'.", a: "Bjørnson", letra: "B"},
    {q: "Con la C: Nobel búlgaro nacionalizado británico, autor de 'Masa y poder'.", a: "Canetti", letra: "C"},
    {q: "Con la D: Segunda mujer en ganar el Nobel de Literatura, de origen italiano.", a: "Deledda", letra: "D"},
    {q: "Con la E: Nobel español de 1904, autor de 'El gran Galeoto'.", a: "Echegaray", letra: "E"},
    {q: "Con la F: Nobel noruego de 2023, autor de 'Septología'.", a: "Fosse", letra: "F"},
    {q: "Con la G: Nobel sudafricana de 1991, autora de 'La hija de Burger'.", a: "Gordimer", letra: "G"},
    {q: "Con la H: Nobel sueco de 1916, autor de 'Hans Alienus'.", a: "Heidenstam", letra: "H"},
    {q: "Con la I: Nobel británico de origen japonés, autor de 'Nunca me abandones'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Nobel austriaca de 2004, autora de 'La pianista'.", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel japonés de 1968, autor de 'La casa de las bellas durmientes'.", a: "Kawabata", letra: "K"},
    {q: "Con la L: Nobel sueca de 1909, creadora de 'Nils Holgersson'.", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel sueco de 1974 (Harry ___).", a: "Martinson", letra: "M"},
    {q: "Con la N: Nobel británico de origen trinitense, autor de 'Una casa para el señor Biswas'.", a: "Naipaul", letra: "N"},
    {q: "Contiene la Ñ: Novelista chileno autor de '2666' y 'Los detectives salvajes'.", a: "Bolaño", letra: "Ñ"},
    {q: "Con la O: Nobel japonés de 1994, autor de 'Una cuestión personal'.", a: "Oe", letra: "O"},
    {q: "Con la P: Nobel turco de 2006, autor de 'Me llamo Rojo'.", a: "Pamuk", letra: "P"},
    {q: "Con la Q: Nobel italiano de 1959, autor de 'Y de repente es de noche'.", a: "Quasimodo", letra: "Q"},
    {q: "Con la R: Nobel polaco de 1924, autor de 'Los campesinos'.", a: "Reymont", letra: "R"},
    {q: "Con la S: Nobel ruso de 1970, autor de 'Archipiélago Gulag'.", a: "Solzhenitsyn", letra: "S"},
    {q: "Con la T: Nobel indio de 1913, autor de 'El cartero del rey'.", a: "Tagore", letra: "T"},
    {q: "Con la U: Nobel noruega de 1928, autora de la trilogía 'Kristin Lavransdatter'.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel peruano de 2010, autor de 'La guerra del fin del mundo'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la W: Nobel de 1992, autor de 'Omeros'.", a: "Walcott", letra: "W"},
    {q: "Contiene la X: Nobel chino de 2000, autor de 'La montaña del alma'.", a: "Xingjian", letra: "X"},
    {q: "Con la Y: Nobel irlandés de 1923, autor de 'La torre'.", a: "Yeats", letra: "Y"},
    {q: "Contiene la Z: Nobel polaca autora de 'El gran número'.", a: "Szymborska", letra: "Z"},

    // ROSCO 11 - AUTORES Y OBRAS "HUESO" (ESPAÑOL)
    {q: "Con la A: Nombre de la autora de 'Olvidado Rey Gudú'.", a: "Ana María", letra: "A"},
    {q: "Con la B: Apellido de la familia protagonista de 'Cien años de soledad'.", a: "Buendía", letra: "B"},
    {q: "Con la C: Autor de 'San Camilo, 1936' y Nobel de Literatura.", a: "Cela", letra: "C"},
    {q: "Con la D: Autor de 'El camino' y 'Señora de rojo sobre fondo gris'.", a: "Delibes", letra: "D"},
    {q: "Con la E: Nombre de pila de la autora de 'Insolación', de apellido Pardo Bazán.", a: "Emilia", letra: "E"},
    {q: "Con la F: Seudónimo de Mariano José de Larra.", a: "Fígaro", letra: "F"},
    {q: "Con la G: Apellido del autor de 'La zapatera prodigiosa'.", a: "García Lorca", letra: "G"},
    {q: "Con la H: Poeta de la Generación del 27, autor de 'Perito en lunas'.", a: "Hernández", letra: "H"},
    {q: "Con la I: Fabulista español del XVIII, autor de las 'Fábulas literarias'.", a: "Iriarte", letra: "I"},
    {q: "Con la J: Nombre del Nobel de Literatura de 1956.", a: "Juan Ramón", letra: "J"},
    {q: "Con la K: Filósofo alemán cuya doctrina inspiró el krausismo español.", a: "Krause", letra: "K"},
    {q: "Con la L: Autora de 'Nada', novela ganadora del primer Premio Nadal.", a: "Laforet", letra: "L"},
    {q: "Con la M: Apellido de la autora de 'Primera memoria' y 'Paraíso inhabitado'.", a: "Matute", letra: "M"},
    {q: "Con la N: Género de la obra 'Niebla' de Unamuno.", a: "nivola", letra: "N"},
    {q: "Contiene la Ñ: Novelista español autor de 'El jinete polaco'.", a: "Muñoz Molina", letra: "Ñ"},
    {q: "Con la O: Filósofo español autor de 'La rebelión de las masas'.", a: "Ortega", letra: "O"},
    {q: "Con la P: Protagonista de la novela de Cela 'La familia de ___ Duarte'.", a: "Pascual", letra: "P"},
    {q: "Con la Q: Apellido del autor de 'La vida de Marco Bruto'.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Protagonista de 'La Regenta', apodada así por su cargo.", a: "Regenta", letra: "R"},
    {q: "Con la S: Autor de 'Réquiem por un campesino español'.", a: "Sender", letra: "S"},
    {q: "Con la T: Apellido real del dramaturgo Tirso de Molina.", a: "Téllez", letra: "T"},
    {q: "Con la U: Autor de 'La tía Tula' y 'Amor y pedagogía'.", a: "Unamuno", letra: "U"},
    {q: "Con la V: Autor de 'Divinas palabras' y 'Sonata de otoño'.", a: "Valle-Inclán", letra: "V"},
    {q: "Con la W: Nombre del novelista Fernández Flórez.", a: "Wenceslao", letra: "W"},
    {q: "Contiene la X: Apellido del Nobel español de 1977, autor de 'Sombra del paraíso'.", a: "Aleixandre", letra: "X"},
    {q: "Contiene la Y: Apellido del autor de 'Reivindicación del conde don Julián'.", a: "Goytisolo", letra: "Y"},
    {q: "Con la Z: Autor de 'Don Juan Tenorio'.", a: "Zorrilla", letra: "Z"},

    // ROSCO 13 - FIGURAS RETÓRICAS Y VICIOS (LAS MÁS DIFÍCILES)
    {q: "Con la A: Figura que omite el nexo entre oraciones (ej. 'Vini, vidi, vici').", a: "asíndeton", letra: "A"},
    {q: "Con la B: Falta de ortografía o uso de una palabra ajena a la lengua propia.", a: "barbarismo", letra: "B"},
    {q: "Con la C: Repetición de una misma palabra al final de frases sucesivas.", a: "conversión", letra: "C"},
    {q: "Con la D: Sustantivo que solo tiene dos casos en su declinación.", a: "díptote", letra: "D"},
    {q: "Con la E: Repetición de un mismo verso al final de varias estrofas.", a: "estribillo", letra: "E"},
    {q: "Con la F: Término genérico para los recursos expresivos de la lengua literaria.", a: "figura", letra: "F"},
    {q: "Con la G: Unidad mínima de significado según la glosemática.", a: "glosema", letra: "G"},
    {q: "Con la H: Encuentro de dos vocales que se pronuncian en sílabas distintas.", a: "hiato", letra: "H"},
    {q: "Con la I: Figura que expresa lo contrario de lo que se dice.", a: "Ironía", letra: "I"},
    {q: "Con la J: Composición poética breve de la lírica mozárabe.", a: "jarcha", letra: "J"},
    {q: "Con la K: Lengua común formada a partir de varios dialectos.", a: "Koiné", letra: "K"},
    {q: "Con la L: Figura que consiste en negar lo contrario de lo que se desea afirmar.", a: "lítotes", letra: "L"},
    {q: "Con la M: Cambio semántico por semejanza entre dos conceptos.", a: "metáfora", letra: "M"},
    {q: "Con la N: Palabra nueva en una lengua o sentido nuevo de una antigua.", a: "neologismo", letra: "N"},
    {q: "Contiene la Ñ: Texto breve en prosa que valora una obra o espectáculo.", a: "reseña", letra: "Ñ"},
    {q: "Con la O: Palabra que imita sonidos de la naturaleza.", a: "onomatopeya", letra: "O"},
    {q: "Con la P: Palabra que tiene el acento en la penúltima sílaba.", a: "paroxítona", letra: "P"},
    {q: "Con la Q: Repetición de una estructura cruzada en dos frases.", a: "quiasmo", letra: "Q"},
    {q: "Con la R: Repetición inmediata de una palabra en el mismo verso.", a: "reduplicación", letra: "R"},
    {q: "Con la S: Figura que rompe la concordancia gramatical por el sentido.", a: "silepsis", letra: "S"},
    {q: "Con la T: Fragmentación de una palabra para introducir otra en medio.", a: "tmesis", letra: "T"},
    {q: "Con la U: Palabra que se usa con un solo sentido.", a: "unívoca", letra: "U"},
    {q: "Con la V: Defecto de dicción que consiste en pronunciar mal las palabras.", a: "vicio", letra: "V"},
    {q: "Con la W: Tipo de dicho irónico atribuido a una autoridad o personaje.", a: "Wellerismo", letra: "W"},
    {q: "Contiene la X: Figura que une dos términos de significado opuesto.", a: "Oxímoron", letra: "X"},
    {q: "Contiene la Y: Figura que atribuye cualidades humanas a seres inanimados.", a: "Prosopopeya", letra: "Y"},
    {q: "Con la Z: Figura que usa un solo verbo para varios complementos.", a: "zeugma", letra: "Z"},

    // ROSCO 14 - PARTES DEL LIBRO Y BIBLIOGRAFÍA
    {q: "Con la A: Texto añadido al final de una obra para completarla.", a: "apéndice", letra: "A"},
    {q: "Con la B: Lista de libros y fuentes consultadas para un trabajo.", a: "bibliografía", letra: "B"},
    {q: "Con la C: Anotación al final del libro con los datos de impresión.", a: "colofón", letra: "C"},
    {q: "Con la D: Nota escrita por el autor para ofrecer su obra a alguien.", a: "dedicatoria", letra: "D"},
    {q: "Con la E: Breve dedicatoria que encabeza un libro o capítulo.", a: "epígrafe", letra: "E"},
    {q: "Con la F: Ilustración o grabado situado frente a la portada de un libro.", a: "frontispicio", letra: "F"},
    {q: "Con la G: Lista de términos técnicos o difíciles al final del libro.", a: "glosario", letra: "G"},
    {q: "Con la H: Tipo de encuadernación con lomo y esquinas de piel.", a: "holandesa", letra: "H"},
    {q: "Con la I: Libro impreso en los albores de la imprenta, antes de 1501.", a: "incunable", letra: "I"},
    {q: "Con la J: Sinónimo de sobrecubierta o forro de un libro (Anglicismo).", a: "jacket", letra: "J"},
    {q: "Con la K: Lengua común o estándar surgida de la convergencia de varios dialectos.", a: "Koiné", letra: "K"},
    {q: "Con la L: Parte del libro opuesta al corte, donde se cosen o encolan los cuadernillos.", a: "Lomo", letra: "L"},
    {q: "Con la M: Espacio en blanco que rodea el texto de una página.", a: "margen", letra: "M"},
    {q: "Con la N: Aclaración breve añadida al pie o al final de un texto.", a: "Nota", letra: "N"},
    {q: "Contiene la Ñ: Nota crítica o descriptiva, breve, sobre un libro.", a: "reseña", letra: "Ñ"},
    {q: "Con la O: Adorno lineal que enmarca títulos o ilustraciones.", a: "Orla", letra: "O"},
    {q: "Con la P: Nota breve que se pone debajo del texto de una página", a: "pie", letra: "P"},
    {q: "Con la Q: Cuadernillo o reunión de pliegos en la tradición bibliográfica inglesa.", a: "Quire", letra: "Q"},
    {q: "Con la R: Cara posterior de una hoja o página de un libro.", a: "reverso", letra: "R"},
    {q: "Con la S: Resumen de una obra que suele aparecer en la contraportada.", a: "sinopsis", letra: "S"},
    {q: "Con la T: Número total de ejemplares impresos de una edición.", a: "tirada", letra: "T"},
    {q: "Con la U: Tipo de escritura mayúscula redondeada usada en códices latinos.", a: "uncial", letra: "U"},
    {q: "Con la V: Dibujo o adorno que encabeza un capítulo de un libro.", a: "viñeta", letra: "V"},
    {q: "Con la W: Marca de agua visible al trasluz en el papel.", a: "Watermark", letra: "W"},
    {q: "Contiene la X: Marca de propiedad adherida al libro, normalmente en la guarda.", a: "Exlibris", letra: "X"},
    {q: "Contiene la Y: Anglicismo para designar la hoja de guarda de un libro.", a: "Flyleaf", letra: "Y"},
    {q: "Con la Z: Procedimiento de grabado o impresión sobre plancha de zinc.", a: "Zincografía", letra: "Z"},

    // ROSCO 15 - NOBELES DE LITERATURA "CERROJO"
    {q: "Con la A: Nobel bielorrusa de 2015, autora de 'Voces de Chernóbil'.", a: "Alexiévich", letra: "A"},
    {q: "Con la B: Nobel ruso-estadounidense de 1987, autor de 'Menos que uno'.", a: "Brodsky", letra: "B"},
    {q: "Con la C: Nobel español de 1989, autor de 'Mazurca para dos muertos'.", a: "Cela", letra: "C"},
    {q: "Con la D: Nobel italiana de 1926, autora de 'Cenizas'.", a: "Deledda", letra: "D"},
    {q: "Con la E: Nobel francesa de 2022, autora de 'Los años'.", a: "Ernaux", letra: "E"},
    {q: "Con la F: Nobel noruego de 2023, autor de 'Aliss junto al fuego'.", a: "Fosse", letra: "F"},
    {q: "Con la G: Nobel tanzano de 2021, autor de 'En la orilla'.", a: "Gurnah", letra: "G"},
    {q: "Con la H: Nobel suizo de 1946, autor de 'El juego de los abalorios'.", a: "Hesse", letra: "H"},
    {q: "Con la I: Nobel británico de 2017, autor de 'Los restos del día'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Nobel austriaca de 2004, autora de 'La pianista'.", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel húngaro de 2002, autor de 'Sin destino'.", a: "Kertész", letra: "K"},
    {q: "Con la L: Nobel francés de 2008, autor de 'El atestado'.", a: "Le Clézio", letra: "L"},
    {q: "Con la M: Nobel italiano de 1975, poeta de 'Huesos de sepia'.", a: "Montale", letra: "M"},
    {q: "Con la N: Nobel estadounidense de 1936, autor de 'A Electra le sienta bien el luto'.", a: "Neill", letra: "N"},
    {q: "Contiene la Ñ: Novelista chileno autor de '2666' y 'Los detectives salvajes'.", a: "Bolaño", letra: "Ñ"},
    {q: "Con la O: Nobel japonés de 1994, autor de 'Una cuestión personal'.", a: "Oe", letra: "O"},
    {q: "Con la P: Nobel turco de 2006, autor de 'Nieve'.", a: "Pamuk", letra: "P"},
    {q: "Con la Q: Nobel italiano de 1959, poeta del hermetismo.", a: "Quasimodo", letra: "Q"},
    {q: "Con la R: Nobel polaco de 1924, autor de 'Los campesinos'.", a: "Reymont", letra: "R"},
    {q: "Con la S: Nobel polaca de 1996, autora de 'El gran número'.", a: "Szymborska", letra: "S"},
    {q: "Con la T: Nobel sueco de 2011, gran poeta y psicólogo.", a: "Transtromer", letra: "T"},
    {q: "Con la U: Nobel noruega de 1928, autora de 'Olav Audunsson'.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel peruano de 2010, autor de 'La guerra del fin del mundo'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la W: Nobel de 1992, autor de 'Omeros'.", a: "Walcott", letra: "W"},
    {q: "Contiene la X: Nobel chino de 2000, autor de 'La montaña del alma'.", a: "Xingjian", letra: "X"},
    {q: "Con la Y: Nobel irlandés de 1923, autor de 'El crepúsculo celta'.", a: "Yeats", letra: "Y"},
    {q: "Contiene la Z: Nobel polaca autora de 'El gran número'.", a: "Szymborska", letra: "Z"},

    // ROSCO 16 - EL GRAN FINAL LITERARIO (MISCELÁNEA)
    {q: "Con la A: Protagonista de 'La Regenta'.", a: "Ana Ozores", letra: "A"},
    {q: "Con la B: Autor de 'El tragaluz' y 'Historia de una escalera'.", a: "Buero Vallejo", letra: "B"},
    {q: "Con la C: Apellido del Nobel español autor de 'La familia de Pascual Duarte'.", a: "Cela", letra: "C"},
    {q: "Con la D: Poeta del 27, autor de 'Hijos de la ira'.", a: "Dámaso", letra: "D"},
    {q: "Con la E: Composición poética de tema amoroso puesta en boca de pastores.", a: "Égloga", letra: "E"},
    {q: "Con la F: Seudónimo de Mariano José de Larra.", a: "Fígaro", letra: "F"},
    {q: "Con la G: Autor de 'La zapatera prodigiosa'.", a: "García Lorca", letra: "G"},
    {q: "Con la H: Poeta hispanoamericano creador del creacionismo.", a: "Huidobro", letra: "H"},
    {q: "Con la I: Dramaturgo del absurdo, autor de 'La cantante calva'.", a: "Ionesco", letra: "I"},
    {q: "Con la J: Novelista español autor de 'Volverás a Región'.", a: "Juan Benet", letra: "J"},
    {q: "Con la K: Autor de 'En la colonia penitenciaria'.", a: "Kafka", letra: "K"},
    {q: "Con la L: Protagonista de 'Ulises', alter ego novelesco de Joyce.", a: "Leopold Bloom", letra: "L"},
    {q: "Con la M: Corriente literaria hispanoamericana de finales del XIX, de la que Darío fue líder.", a: "Modernismo", letra: "M"},
    {q: "Con la N: Género de la obra 'Niebla' de Unamuno.", a: "Nivola", letra: "N"},
    {q: "Contiene la Ñ: Novelista español autor de 'Beltenebros'.", a: "Muñoz Molina", letra: "Ñ"},
    {q: "Con la O: Poeta del 27 autor de 'Ángel fieramente humano' (Blas de ___).", a: "Otero", letra: "O"},
    {q: "Con la P: Autor de 'El árbol de la ciencia'.", a: "Pío Baroja", letra: "P"},
    {q: "Con la Q: Apellido del autor de 'El Buscón'.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Autor de 'La Celestina', Fernando de ___.", a: "Rojas", letra: "R"},
    {q: "Con la S: Autor de 'La sonrisa etrusca'.", a: "Sampedro", letra: "S"},
    {q: "Con la T: Novelista gallego autor de 'La saga/fuga de J.B.' (Torrente ___).", a: "Ballester", letra: "T"},
    {q: "Con la U: Autor de 'San Manuel Bueno, mártir'.", a: "Unamuno", letra: "U"},
    {q: "Con la V: Poeta peruano autor de 'Trilce'.", a: "Vallejo", letra: "V"},
    {q: "Con la W: Novelista británica autora de 'Las olas'.", a: "Woolf", letra: "W"},
    {q: "Contiene la X: Apellido del Nobel español de 1977.", a: "Aleixandre", letra: "X"},
    {q: "Con la Y: Poeta irlandés y Nobel de 1923.", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Autor de 'Don Juan Tenorio'.", a: "Zorrilla", letra: "Z"},
  ]
});