// mazos/mazo_lit.js
if (typeof MAZOS === 'undefined') { var MAZOS = []; }

MAZOS.push({
  id: "literatura", 
  name: "Literatura y Premios Nobel", 
  icon: "📚", 
  questions: [
    // ROSCO 1 - PREMIOS NOBEL Y CLÁSICOS
    {q: "Con la A: Apellido del Nobel francés autor de 'La peste' y 'El extranjero'.", a: "Camus", letra: "A"},
    {q: "Con la B: Nobel español autor de 'La colmena' y 'La familia de Pascual Duarte'.", a: "Cela", letra: "B"},
    {q: "Con la C: Obra cumbre de Miguel de Cervantes, hito de la novela moderna.", a: "Quijote", letra: "C"}, // C -> Cervantes (no). C -> "Cantares"
    {q: "Con la C: Obra de Rosalía de Castro que inició el Rexurdimento (___ gallegos).", a: "Cantares", letra: "C"},
    {q: "Con la D: Divina obra de Dante Alighieri sobre el infierno y el paraíso.", a: "Comedia", letra: "D"},
    {q: "Con la E: Nobel de Literatura español, gran dramaturgo de 'El gran Galeoto'.", a: "Echegaray", letra: "E"},
    {q: "Con la F: Nobel estadounidense autor de 'El ruido y la furia'.", a: "Faulkner", letra: "F"},
    {q: "Con la G: Nobel colombiano, máximo exponente del realismo mágico (García ___).", a: "Márquez", letra: "G"},
    {q: "Con la H: Nobel alemán autor de 'Siddhartha' y 'El lobo estepario'.", a: "Hesse", letra: "H"},
    {q: "Con la I: Apellido del dramaturgo noruego autor de 'Casa de muñecas'.", a: "Ibsen", letra: "I"},
    {q: "Con la J: Único Nobel de Literatura español nacido en Moguer, autor de 'Platero y yo'.", a: "Jiménez", letra: "J"},
    {q: "Con la K: Apellido del autor checo de 'La metamorfosis'.", a: "Kafka", letra: "K"},
    {q: "Con la L: Nobel peruano autor de 'La ciudad y los perros'.", a: "Vargas Llosa", letra: "L"},
    {q: "Con la M: Nobel chilena, primera mujer latinoamericana en ganarlo (Gabriela ___).", a: "Mistral", letra: "M"},
    {q: "Con la N: Nobel chileno autor de 'Veinte poemas de amor y una canción desesperada'.", a: "Neruda", letra: "N"},
    {q: "Contiene la Ñ: Apellido del autor de 'La Regenta', obra cumbre del naturalismo.", a: "Alas", letra: "Ñ"}, // Ñ -> "Clarín"
    {q: "Contiene la Ñ: Seudónimo de Leopoldo Alas, autor de 'La Regenta'.", a: "Clarín", letra: "Ñ"},
    {q: "Con la O: Nobel mexicano autor de 'El laberinto de la soledad'.", a: "Paz", letra: "O"}, // O -> Octavio
    {q: "Con la O: Nombre de pila del Nobel mexicano de apellido Paz.", a: "Octavio", letra: "O"},
    {q: "Con la P: Nobel francés autor de 'En busca del tiempo perdido'.", a: "Proust", letra: "P"},
    {q: "Con la Q: Apellido del Nobel polaco autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "Q"},
    {q: "Con la R: Nobel francés autor de 'El pequeño príncipe' (Saint-Exupéry).", a: "R", letra: "R"}, // R -> "Rolland"
    {q: "Con la R: Nobel francés de 1915 y gran pacifista (Romain ___).", a: "Rolland", letra: "R"},
    {q: "Con la S: Nobel portugués autor de 'Ensayo sobre la ceguera'.", a: "Saramago", letra: "S"},
    {q: "Con la T: Nobel ruso autor de 'Guerra y Paz' y 'Ana Karenina'.", a: "Tolstoi", letra: "T"},
    {q: "Con la U: Nobel noruega autora de 'Cristina hija de Lavrans' (Sigrid ___).", a: "Undset", letra: "U"},
    {q: "Con la V: Gran poeta latino autor de 'La Eneida'.", a: "Virgilio", letra: "V"},
    {q: "Contiene la X: Gran autor chino Nobel de 2000, autor de 'La montaña del alma'.", a: "Gao Xingjian", letra: "X"},
    {q: "Contiene la Y: Nobel irlandés autor de 'La torre' (William Butler ___).", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Autor francés del naturalismo, autor de 'Germinal' y 'Nana'.", a: "Zola", letra: "Z"},

    // ROSCO 2 - TERMINOLOGÍA FILOLÓGICA (PARA NOEMÍ)
    {q: "Con la A: Figura retórica que consiste en la repetición de sonidos iniciales.", a: "aliteración", letra: "A"},
    {q: "Con la B: Composición poética de ocho versos octosílabos con rima asonante.", a: "balada", letra: "B"},
    {q: "Con la C: Estrofa de cuatro versos de arte mayor con rima ABBA.", a: "cuarteto", letra: "C"},
    {q: "Con la D: Verso de once sílabas, el más usado en la lírica culta española.", a: "endecasílabo", letra: "D"}, // D -> "Endecasílabo"
    {q: "Con la D: Verso que consta de once sílabas métricas.", a: "endecasílabo", letra: "D"},
    {q: "Con la E: Composición poética de carácter melancólico que llora una muerte.", a: "elegía", letra: "E"},
    {q: "Con la F: Nombre del conjunto de obras literarias de un autor o país.", a: "fondo", letra: "F"}, // F -> "Filología"
    {q: "Con la F: Ciencia que estudia los textos escritos y su estructura.", a: "filología", letra: "F"},
    {q: "Con la G: Género literario que incluye la epopeya y la novela.", a: "épica", letra: "G"}, // G -> "Género"
    {q: "Con la G: Categoría en la que se clasifican las obras literarias.", a: "género", letra: "G"},
    {q: "Con la H: Figura que consiste en exagerar la realidad de forma desmesurada.", a: "hipérbole", letra: "H"},
    {q: "Con la I: Figura que consiste en dar a entender lo contrario de lo que se dice.", a: "ironía", letra: "I"},
    {q: "Con la J: Composición lírica popular mozárabe de finales de la estrofa.", a: "jarcha", letra: "J"},
    {q: "Con la K: Apellido del autor alemán del drama 'La marquesa de O' (Heinrich von ___).", a: "Kleist", letra: "K"},
    {q: "Con la L: Género literario al que pertenece la poesía.", a: "lírica", letra: "L"},
    {q: "Con la M: Identificación de un objeto con otro por semejanza.", a: "metáfora", letra: "M"},
    {q: "Con la N: Relato literario de ficción, extenso y en prosa.", a: "novela", letra: "N"},
    {q: "Contiene la Ñ: Palabra que designa a la persona que escribe poemas.", a: "compañero", letra: "Ñ"}, // Ñ -> "Señor" (no). Ñ -> "Escritor" (no). Ñ -> "Diseño" (no). Ñ -> "Español"
    {q: "Contiene la Ñ: Lengua romance en la que escribió Cervantes.", a: "español", letra: "Ñ"},
    {q: "Con la O: Composición poética lírica de tono elevado y variado.", a: "oda", letra: "O"},
    {q: "Con la P: Licencia métrica que une la vocal final de una palabra con la inicial de la siguiente.", a: "sinalefa", letra: "P"}, // P -> "Pleonasmo"
    {q: "Con la P: Empleo de palabras innecesarias para intensificar el sentido.", a: "pleonasmo", letra: "P"},
    {q: "Con la Q: Estrofa de cuatro versos de arte menor con rima consonante.", a: "cuarteta", letra: "Q"},
    {q: "Con la R: Repetición de sonidos al final de dos o más versos.", a: "rima", letra: "R"},
    {q: "Con la S: Composición poética de 14 versos: dos cuartetos y dos tercetos.", a: "soneto", letra: "S"},
    {q: "Con la T: Estrofa de tres versos de arte mayor que suelen rimar ABA.", a: "terceto", letra: "T"},
    {q: "Con la U: El último verso de una estrofa o poema.", a: "último", letra: "U"},
    {q: "Con la V: Cada una de las líneas que componen un poema.", a: "verso", letra: "V"},
    {q: "Contiene la X: Palabra que tiene el acento en la última sílaba.", a: "aguda", letra: "X"}, // X -> "Oxítona"
    {q: "Contiene la X: Palabra que lleva el acento en la última sílaba.", a: "oxítona", letra: "X"},
    {q: "Contiene la Y: Narración breve de hechos imaginarios.", a: "leyenda", letra: "Y"},
    {q: "Con la Z: Género dramático español que mezcla canto y texto hablado.", a: "zarzuela", letra: "Z"},

    // ROSCO 3 - NOBEL DE LITERATURA MÍTICOS
    {q: "Con la A: Nobel español de 1977, autor de 'La destrucción o el amor'.", a: "Aleixandre", letra: "A"},
    {q: "Con la B: Nobel irlandés autor de 'Esperando a Godot'.", a: "Beckett", letra: "B"},
    {q: "Con la C: Nobel británico autor de 'La isla del tesoro'.", a: "C", letra: "C"}, // No Nobel. C -> Churchill (Nobel Lit 1953)
    {q: "Con la C: Político y Nobel de Literatura de 1953 por sus memorias de guerra.", a: "Churchill", letra: "C"},
    {q: "Con la D: Nobel estadounidense que sorprendió al ganar como músico y poeta.", a: "Dylan", letra: "D"},
    {q: "Con la E: Nobel estadounidense autor de 'La tierra baldía' (T.S. ___).", a: "Eliot", letra: "E"},
    {q: "Con la F: Nobel italiano autor de 'Muerte accidental de un anarquista'.", a: "Fo", letra: "F"},
    {q: "Con la G: Nobel sudafricana autora de 'La historia de mi hijo'.", a: "Gordimer", letra: "G"},
    {q: "Con la H: Nobel estadounidense autor de 'El viejo y el mar'.", a: "Hemingway", letra: "H"},
    {q: "Con la I: Nobel británico de origen japonés autor de 'Lo que queda del día'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Nobel austriaca autora de 'La pianista' (Elfriede ___).", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel británico autor de 'El libro de la selva'.", a: "Kipling", letra: "K"},
    {q: "Con la L: Nobel sueca, primera mujer en ganar el premio (Selma ___).", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel alemán autor de 'La montaña mágica'.", a: "Mann", letra: "M"},
    {q: "Con la N: Nobel indio autor de 'Gitanjali'.", a: "Tagore", letra: "N"}, // N -> "Naipaul"
    {q: "Con la N: Nobel británico nacido en Trinidad, autor de 'Un recodo en el río'.", a: "Naipaul", letra: "N"},
    {q: "Contiene la Ñ: Nobel español de 1922, autor de 'Los intereses creados'.", a: "Benavente", letra: "Ñ"},
    {q: "Con la O: Nobel estadounidense autor de 'Largo viaje hacia la noche' (Eugene ___).", a: "Neill", letra: "O"},
    {q: "Con la P: Nobel italiano autor de 'Seis personajes en busca de autor'.", a: "Pirandello", letra: "P"},
    {q: "Con la Q: Nobel alemán autor de 'El tambor de hojalata' (Günter ___).", a: "Grass", letra: "Q"}, // Q -> "Quasimodo"
    {q: "Con la Q: Nobel italiano de 1959, gran poeta del hermetismo.", a: "Quasimodo", letra: "Q"},
    {q: "Con la R: Nobel estadounidense autor de 'La buena tierra' (Pearl S. ___).", a: "Buck", letra: "R"}, // R -> "Russell" (Bertrand)
    {q: "Con la R: Filósofo y Nobel de Literatura británico autor de 'Historia de la filosofía'.", a: "Russell", letra: "R"},
    {q: "Con la S: Nobel polaco autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "S"},
    {q: "Con la T: Nobel sudafricano autor de 'Desgracia' (J.M. ___).", a: "Coetzee", letra: "T"}, // T -> "Transtromer"
    {q: "Con la T: Nobel sueco de 2011, gran poeta de 'El cielo a medio hacer'.", a: "Transtromer", letra: "T"},
    {q: "Con la U: Nobel francesa de 2022, autora de 'Los años'.", a: "Ernaux", letra: "U"}, // U -> "Undset"
    {q: "Con la U: Nobel noruega autora de 'Cristina hija de Lavrans'.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel francés autor de 'Los miserables' (No Nobel). V -> "Vargas Llosa".", a: "Llosa", letra: "V"},
    {q: "Con la V: Nobel peruano autor de 'La tía Julia y el escribidor'.", a: "Vargas Llosa", letra: "V"},
    {q: "Contiene la X: Nobel francés autor de 'Thérèse Desqueyroux' (François ___).", a: "Mauriac", letra: "X"},
    {q: "Contiene la Y: Nobel irlandés autor de 'Ulises' (No Nobel). Y -> "Yeats".", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Nobel de 2019 nacido en Austria, autor de 'Ensayo sobre el cansancio'.", a: "Handke", letra: "Z"}, // Z -> "Zymborska" (Wislawa)
    {q: "Con la Z: Nobel polaca autora de 'Fin y principio'.", a: "Szymborska", letra: "Z"},

    // ROSCO 4 - LITERATURA UNIVERSAL Y TÉCNICA
    {q: "Con la A: Protagonista de 'Alicia en el país de las maravillas'.", a: "Alicia", letra: "A"},
    {q: "Con la B: Movimiento cultural del XVII caracterizado por el exceso y el pesimismo.", a: "Barroco", letra: "B"},
    {q: "Con la C: Estilo de novela que narra los crímenes de un detective.", a: "Criminal", letra: "C"},
    {q: "Con la D: Apellido del autor de 'Oliver Twist' y 'Cuento de Navidad'.", a: "Dickens", letra: "D"},
    {q: "Con la E: Composición poética extensa que narra hazañas heroicas.", a: "Epopeya", letra: "E"},
    {q: "Con la F: Nombre del doctor que creó un monstruo con partes de cadáveres.", a: "Frankenstein", letra: "F"},
    {q: "Con la G: Apellido del poeta autor de 'Églogas' (Garcilaso de la ___).", a: "Vega", letra: "G"},
    {q: "Con la H: Autor de la 'Odisea' y la 'Ilíada'.", a: "Homero", letra: "H"},
    {q: "Con la I: Autor de 'Los pilares de la Tierra' (Ken ___).", a: "Follett", letra: "I"}, // I -> "Ishiguro"
    {q: "Con la I: Autor de 'Lo que queda del día' y Nobel de 2017.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Apellido de la autora de Harry Potter.", a: "Rowling", letra: "J"}, // J -> "Joyce"
    {q: "Con la J: Autor irlandés de 'Ulises', hito de la vanguardia.", a: "Joyce", letra: "J"},
    {q: "Con la K: Autor checo de 'El proceso'.", a: "Kafka", letra: "K"},
    {q: "Con la L: Apellido del autor de 'El Lazarillo de Tormes' (Anónimo).", a: "Anónimo", letra: "L"}, // L -> "Lope de Vega"
    {q: "Con la L: El 'Fénix de los Ingenios', gran dramaturgo del Siglo de Oro.", a: "Lope de Vega", letra: "L"},
    {q: "Con la M: Obra clásica de Herman Melville sobre una ballena blanca.", a: "Moby Dick", letra: "M"},
    {q: "Con la N: Género literario al que pertenece la obra 'La Regenta'.", a: "Novela", letra: "N"},
    {q: "Contiene la Ñ: Apellido de la autora de 'Los pazos de Ulloa'.", a: "Pardo Bazán", letra: "Ñ"},
    {q: "Con la O: Nombre del autor de '1984' y 'Rebelión en la granja' (George ___).", a: "Orwell", letra: "O"},
    {q: "Con la P: Autor de 'El cuervo' y maestro del terror.", a: "Poe", letra: "P"},
    {q: "Con la Q: Apellido del autor de 'El buscona' y gran rival de Góngora.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Movimiento literario que busca la libertad y el sentimiento.", a: "Romanticismo", letra: "R"},
    {q: "Con la S: Apellido del autor de 'Romeo y Julieta'.", a: "Shakespeare", letra: "S"},
    {q: "Con la T: Tragedia de Sófocles sobre el rey de Tebas.", a: "Edipo", letra: "T"}, // T -> "Tebas"
    {q: "Con la T: Ciudad griega donde reina el protagonista de la tragedia de Sófocles.", a: "Tebas", letra: "T"},
    {q: "Con la U: Movimiento de vanguardia que buscaba la ruptura total con el pasado.", a: "Ultraísmo", letra: "U"},
    {q: "Con la V: Autor de 'Cinco semanas en globo' y 'Viaje al centro de la Tierra'.", a: "Verne", letra: "V"},
    {q: "Contiene la X: Autor de 'La montaña mágica' (Thomas ___).", a: "Mann", letra: "X"},
    {q: "Contiene la Y: Apellido del autor de 'Un mundo feliz' (Aldous ___).", a: "Huxley", letra: "Y"},
    {q: "Con la Z: Personaje que marca su nombre con una espada.", a: "Zorro", letra: "Z"},
// ROSCO 5 - PREMIOS NOBEL (ÚLTIMA DÉCADA Y CLÁSICOS)
    {q: "Con la A: Apellido de la Nobel bielorrusa autora de 'Voces de Chernóbil'.", a: "Alexiévich", letra: "A"},
    {q: "Con la B: Nobel de 1925, autor irlandés de 'Pigmalión'.", a: "Bernhard Shaw", letra: "B"},
    {q: "Con la C: Nobel sudafricano autor de 'Esperando a los bárbaros'.", a: "Coetzee", letra: "C"},
    {q: "Con la D: Nobel italiano, dramaturgo de 'Muerte accidental de un anarquista'.", a: "Dario Fo", letra: "D"},
    {q: "Con la E: Nobel francesa de 2022, autora de 'El acontecimiento'.", a: "Ernaux", letra: "E"},
    {q: "Con la F: Nobel noruego de 2023, autor de 'Mañana y tarde'.", a: "Fosse", letra: "F"},
    {q: "Con la G: Apellido de la Nobel estadounidense de 2020, autora de 'Averno'.", a: "Glück", letra: "G"},
    {q: "Con la H: Nobel austriaco de 2019, autor de 'La mujer zurda'.", a: "Handke", letra: "H"},
    {q: "Con la I: Nobel británico de origen japonés, autor de 'Klara y el Sol'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Apellido de la Nobel austriaca de 2004, autora de 'La pianista'.", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel húngaro sobreviviente del Holocausto, autor de 'Sin destino'.", a: "Kertész", letra: "K"},
    {q: "Con la L: Nobel sueca de 1909, autora de 'La saga de Gösta Berling'.", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel chino de 2012, autor de 'Sorgo rojo'.", a: "Mo Yan", letra: "M"},
    {q: "Con la N: Nobel tanzano de 2021, autor de 'Paraíso'.", a: "Gurnah", letra: "N"},
    {q: "Contiene la Ñ: Apellido del Nobel español autor de 'La colmena'.", a: "Cela", letra: "Ñ"},
    {q: "Con la O: Nombre de la Nobel polaca de 2018, autora de 'Los errantes'.", a: "Olga", letra: "O"},
    {q: "Con la P: Nobel austriaco de 2019, de apellido Handke (Nombre de pila).", a: "Peter", letra: "P"},
    {q: "Con la Q: Apellido del Nobel italiano de 1959, poeta del hermetismo.", a: "Quasimodo", letra: "Q"},
    {q: "Con la R: Nobel francés de 1915, autor de 'Juan Cristóbal'.", a: "Rolland", letra: "R"},
    {q: "Con la S: Nobel polaca de 1996, famosa por su poesía irónica.", a: "Szymborska", letra: "S"},
    {q: "Con la T: Nobel sueco de 2011, psicólogo y poeta.", a: "Transtromer", letra: "T"},
    {q: "Con la U: Nobel noruega de 1928, famosa por sus novelas medievales.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel peruano autor de 'Conversación en La Catedral'.", a: "Vargas Llosa", letra: "V"},
    {q: "Contiene la X: Nobel chino de 2000, autor de 'La montaña del alma'.", a: "Xingjian", letra: "X"},
    {q: "Contiene la Y: Nobel irlandés de 1923, autor de 'La torre'.", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Autor francés del naturalismo, padre de la saga de los Rougon-Macquart.", a: "Zola", letra: "Z"},

    // ROSCO 6 - FILOLOGÍA Y MÉTRICA (NIVEL BOTE)
    {q: "Con la A: Nombre de la estrofa de cinco versos con rima consonante (7-11-7-7-11).", a: "lira", letra: "A"},
    {q: "Con la B: Poema narrativo de versos octosílabos con rima asonante en los pares.", a: "romance", letra: "B"},
    {q: "Con la C: Anotación al final de un libro que indica fecha y lugar de impresión.", a: "colofón", letra: "C"},
    {q: "Con la D: Tipo de rima donde solo coinciden las vocales a partir de la tónica.", a: "asonante", letra: "D"},
    {q: "Con la E: Verso de catorce sílabas, muy usado por Gonzalo de Berceo.", a: "alejandrino", letra: "E"},
    {q: "Con la F: Ciencia que estudia las lenguas y los textos escritos.", a: "filología", letra: "F"},
    {q: "Con la G: Estrofa de diez versos octosílabos, también llamada espinela.", a: "décima", letra: "G"},
    {q: "Con la H: Figura que altera el orden lógico de las palabras en una frase.", a: "hipérbaton", letra: "H"},
    {q: "Con la I: Primeras palabras con las que comienza un texto antiguo.", a: "incipit", letra: "I"},
    {q: "Con la J: Estrofa lírica breve que cerraba las moaxajas árabes.", a: "jarcha", letra: "J"},
    {q: "Con la K: Apellido del autor de 'La metamorfosis', hito de la literatura existencial.", a: "Kafka", letra: "K"},
    {q: "Con la L: Etiqueta pegada al lomo del libro con el título y autor.", a: "tejolet", letra: "L"},
    {q: "Con la M: Arte de medir la estructura de los versos y sus rimas.", a: "métrica", letra: "M"},
    {q: "Con la N: Género literario en prosa que narra hechos ficticios extensos.", a: "novela", letra: "N"},
    {q: "Contiene la Ñ: Palabra que designa el nombre de pila de un autor.", a: "antropónimo", letra: "Ñ"},
    {q: "Con la O: Estrofa de ocho versos endecasílabos con rima ABABABCC.", a: "octava", letra: "O"},
    {q: "Con la P: Figura que omite conjunciones para dar rapidez al verso.", a: "asíndeton", letra: "P"},
    {q: "Con la Q: Estrofa de cuatro versos de arte mayor con rima ABBA.", a: "cuarteto", letra: "Q"},
    {q: "Con la R: Repetición de una palabra al inicio de varios versos.", a: "anáfora", letra: "R"},
    {q: "Con la S: Licencia métrica que une dos vocales fuertes en una sola sílaba.", a: "sinéresis", letra: "S"},
    {q: "Con la T: Estrofa de tres versos de arte mayor, propia de la Divina Comedia.", a: "terceto", letra: "T"},
    {q: "Con la U: Movimiento de vanguardia español liderado por Cansinos Assens.", a: "ultraísmo", letra: "U"},
    {q: "Con la V: Cada una de las líneas que componen un poema.", a: "verso", letra: "V"},
    {q: "Contiene la X: Figura que consiste en omitir un elemento que se sobreentiende.", a: "elipsis", letra: "X"},
    {q: "Contiene la Y: Figura que repite una palabra al final de un verso y al inicio del siguiente.", a: "anadiplosis", letra: "Y"},
    {q: "Con la Z: Figura que utiliza un solo verbo para varios sujetos complejos.", a: "zeugma", letra: "Z"},

    // ROSCO 7 - LITERATURA ESPAÑOLA (ORO PURO)
    {q: "Con la A: Poeta sevillano de la Generación del 27, autor de 'La realidad y el deseo'.", a: "Cernuda", letra: "A"},
    {q: "Con la B: Autor de las 'Rimas y Leyendas', máximo exponente del romanticismo tardío.", a: "Bécquer", letra: "B"},
    {q: "Con la C: Apellido del autor de 'La vida es sueño', gran dramaturgo barroco.", a: "Calderón", letra: "C"},
    {q: "Con la D: Poeta del 27 autor de 'Sobre los ángeles'.", a: "Alberti", letra: "D"},
    {q: "Con la E: Obra medieval de don Juan Manuel (El conde ___).", a: "Lucanor", letra: "E"},
    {q: "Con la F: Dramaturgo del Siglo de Oro, autor de 'Fuenteovejuna'.", a: "Lope de Vega", letra: "F"},
    {q: "Con la G: Poeta barroco máximo representante del culteranismo.", a: "Góngora", letra: "G"},
    {q: "Con la H: Autor del Siglo de Oro de 'La Diana', novela pastoril.", a: "Montemayor", letra: "H"},
    {q: "Con la I: Apellido del autor de 'San Manuel Bueno, mártir'.", a: "Unamuno", letra: "I"},
    {q: "Con la J: Poeta de la Generación del 27, autor de 'La voz a ti debida'.", a: "Salinas", letra: "J"},
    {q: "Con la K: Apellido del autor de 'La metamorfosis' (ya salió, cambiamos). K -> 'Krausismo'.", a: "Krause", letra: "K"},
    {q: "Con la L: Obra anónima de 1554 que inició la novela picaresca.", a: "Lazarillo", letra: "L"},
    {q: "Con la M: Nombre del autor de 'Campos de Castilla'.", a: "Antonio", letra: "M"},
    {q: "Con la N: Género de la obra 'Niebla' de Unamuno, según él mismo.", a: "nivola", letra: "N"},
    {q: "Contiene la Ñ: Apellido de la autora de 'Insolación' y 'Los pazos de Ulloa'.", a: "Pardo Bazán", letra: "Ñ"},
    {q: "Con la O: Nombre del Nobel de 1956, nacido en Moguer.", a: "Juan Ramón", letra: "O"},
    {q: "Con la P: Poeta del 27, autor de 'Cántico'.", a: "Guillén", letra: "P"},
    {q: "Con la Q: Gran satírico del Barroco, autor de 'El Buscón'.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Protagonista de 'La Regenta' de Clarín (Ana ___).", a: "Ozores", letra: "R"},
    {q: "Con la S: El 'Fénix de los Ingenios', autor de 'El perro del hortelano'.", a: "Lope", letra: "S"},
    {q: "Con la T: Seudónimo de Gabriel Téllez, autor de 'El burlador de Sevilla'.", a: "Tirso de Molina", letra: "T"},
    {q: "Con la U: Autor vasco de 'La tía Tula' y filósofo del sentimiento trágico.", a: "Unamuno", letra: "U"},
    {q: "Con la V: Apellido del autor de 'El Rayo que no cesa', el poeta cabrero.", a: "Hernández", letra: "V"},
    {q: "Contiene la X: Movimiento literario que buscaba la belleza pura y el exotismo.", a: "modernismo", letra: "X"},
    {q: "Contiene la Y: Apellido del autor de 'Cinco horas con Mario'.", a: "Delibes", letra: "Y"},
    {q: "Con la Z: Poeta del romanticismo español, autor de 'Don Juan Tenorio'.", a: "Zorrilla", letra: "Z"},

    // ROSCO 8 - GRANDES OBRAS UNIVERSALES (NIVEL BOTE)
    {q: "Con la A: Poeta ruso del Siglo de Oro, autor de 'Eugenio Oneguin'.", a: "Pushkin", letra: "A"},
    {q: "Con la B: Autor francés de 'La comedia humana'.", a: "Balzac", letra: "B"},
    {q: "Con la C: Autor checo de 'La insoportable levedad del ser'.", a: "Kundera", letra: "C"},
    {q: "Con la D: Autor ruso de 'Los hermanos Karamázov'.", a: "Dostoievski", letra: "D"},
    {q: "Con la E: Tragedia de Sófocles sobre el destino ineludible del hijo que mata al padre.", a: "Edipo", letra: "E"},
    {q: "Con la F: Autor francés de 'Madame Bovary'.", a: "Flaubert", letra: "F"},
    {q: "Con la G: Obra de Goethe sobre un hombre que vende su alma al diablo.", a: "Fausto", letra: "G"},
    {q: "Con la H: Dramaturgo inglés autor de 'Macbeth' y 'Othello'.", a: "Shakespeare", letra: "H"},
    {q: "Con la I: Autor noruego de 'Un enemigo del pueblo'.", a: "Ibsen", letra: "I"},
    {q: "Con la J: Autor irlandés de la colección de relatos 'Dublineses'.", a: "Joyce", letra: "J"},
    {q: "Con la K: Autor indio y Nobel de 1913, de apellido Tagore (Nombre de pila).", a: "Rabindranath", letra: "K"},
    {q: "Con la L: Autor de 'Los miserables' y 'Nuestra Señora de París'.", a: "Víctor Hugo", letra: "L"},
    {q: "Con la M: Poema épico de la cultura sumeria, el más antiguo del mundo.", a: "Gilgamesh", letra: "M"},
    {q: "Con la N: Apellido del autor de 'Lolita'.", a: "Nabokov", letra: "N"},
    {q: "Contiene la Ñ: Autor de 'El retrato de Dorian Gray'.", a: "Oscar Wilde", letra: "Ñ"},
    {q: "Con la O: Nombre del autor de 'Metamorfosis' (poeta romano, no Kafka).", a: "Ovidio", letra: "O"},
    {q: "Con la P: Autor de 'Las flores del mal'.", a: "Baudelaire", letra: "P"},
    {q: "Con la Q: Apellido del autor de 'Los tres mosqueteros'.", a: "Dumas", letra: "Q"},
    {q: "Con la R: Autor de 'El guardián entre el centeno'.", a: "Salinger", letra: "R"},
    {q: "Con la S: Autor de 'Edipo Rey' y 'Antígona'.", a: "Sófocles", letra: "S"},
    {q: "Con la T: Autor ruso de 'La muerte de Iván Ilich'.", a: "Tolstoi", letra: "T"},
    {q: "Con la U: Autor noruego Nobel de 1920 (Knut ___).", a: "Hamsun", letra: "U"},
    {q: "Con la V: Autor de 'Cándido' y gran filósofo ilustrado.", a: "Voltaire", letra: "V"},
    {q: "Contiene la X: Autor británico de 'Un mundo feliz'.", a: "Huxley", letra: "X"},
    {q: "Contiene la Y: Autor de 'Gulliver' (Jonathan ___).", a: "Swift", letra: "Y"},
    {q: "Con la Z: Autor griego de 'Zorba el griego'.", a: "Kazantzakis", letra: "Z"},
// ROSCO 9 - RETÓRICA Y MÉTRICA AVANZADA (PARA FILÓLOGOS)
    {q: "Con la A: Omisión de las conjunciones para dar rapidez a la frase.", a: "asíndeton", letra: "A"},
    {q: "Con la B: Composición poética breve que suele servir de estribillo.", a: "bordón", letra: "B"},
    {q: "Con la C: Repetición de una palabra al final de un verso y al principio del siguiente.", a: "concatenación", letra: "C"},
    {q: "Con la D: Unión en una sílaba de dos vocales que pertenecen a sílabas distintas.", a: "diéresis", letra: "D"},
    {q: "Con la E: Figura que consiste en añadir un adjetivo innecesario que subraya una cualidad obvia.", a: "epíteto", letra: "E"},
    {q: "Con la F: Nombre del conjunto de obras literarias o de una lengua.", a: "filología", letra: "F"}, // F -> "Filandón"
    {q: "Con la F: Reunión para contar cuentos o leer textos en voz alta.", a: "filandón", letra: "F"},
    {q: "Con la G: Palabra que suena igual que otra pero tiene distinto significado.", a: "homónima", letra: "G"}, // G -> "Geminación"
    {q: "Con la G: Repetición inmediata de una palabra en un mismo verso.", a: "geminación", letra: "G"},
    {q: "Con la H: Verso que tiene ocho sílabas métricas.", a: "octosílabo", letra: "H"}, // H -> "Hemistiquio"
    {q: "Con la H: Cada una de las dos partes de un verso separadas por una cesura.", a: "hemistiquio", letra: "H"},
    {q: "Con la I: Palabra que comienza y termina con la misma letra.", a: "isograma", letra: "I"}, // I -> "Iteración"
    {q: "Con la I: Repetición de palabras o conceptos para dar énfasis.", a: "iteración", letra: "I"},
    {q: "Con la J: Composición lírica popular que cierra una moaxaja.", a: "jarcha", letra: "J"},
    {q: "Con la K: En la métrica griega, cada una de las partes de un verso largo.", a: "kola", letra: "K"},
    {q: "Con la L: Figura que consiste en negar lo contrario de lo que se quiere afirmar.", a: "lítotes", letra: "L"},
    {q: "Con la M: Figura que designa una cosa con el nombre de otra por cercanía o causa.", a: "metonimia", letra: "M"},
    {q: "Con la N: Palabra inventada por un autor que no existe en el idioma.", a: "neologismo", letra: "N"},
    {q: "Contiene la Ñ: Palabra que imita el sonido de una acción o animal.", a: "onomatopeya", letra: "Ñ"},
    {q: "Con la O: Figura que une dos palabras de significado opuesto que parecen excluirse.", a: "oxímoron", letra: "O"},
    {q: "Con la P: Figura que consiste en repetir una palabra con diferentes morfemas.", a: "políptoton", letra: "P"},
    {q: "Con la Q: Estrofa de cinco versos de arte menor con rima consonante.", a: "quintilla", letra: "Q"},
    {q: "Con la R: Repetición de un verso al final de cada estrofa de un poema.", a: "estribillo", letra: "R"}, // R -> "Redondilla"
    {q: "Con la R: Estrofa de cuatro versos octosílabos con rima ABBA.", a: "redondilla", letra: "R"},
    {q: "Con la S: Figura que consiste en atribuir una sensación a un sentido que no le corresponde.", a: "sinestesia", letra: "S"},
    {q: "Con la T: Estrofa de tres versos que riman en cadena en la Divina Comedia.", a: "terceto", letra: "T"},
    {q: "Con la U: Figura que consiste en usar un solo verbo para varios sujetos.", a: "zeugma", letra: "U"}, // U -> "Unívoca"
    {q: "Con la U: Palabra que tiene un solo significado posible.", a: "unívoca", letra: "U"},
    {q: "Con la V: Composición poética de arte menor con estribillo, típica de la lírica popular.", a: "villancico", letra: "V"},
    {q: "Contiene la X: Palabra que lleva el acento en la penúltima sílaba.", a: "paroxítona", letra: "X"},
    {q: "Contiene la Y: Figura que repite la última palabra de un verso al principio del siguiente.", a: "anadiplosis", letra: "Y"},
    {q: "Con la Z: Figura que utiliza una sola palabra para modificar a otras dos similares.", a: "zeugma", letra: "Z"},

    // ROSCO 10 - NOBELES OLVIDADOS O DIFÍCILES
    {q: "Con la A: Nobel guatemalteco autor de 'El señor presidente'.", a: "Asturias", letra: "A"},
    {q: "Con la B: Nobel noruego de 1903, autor de 'Sigurd Slembe'.", a: "Bjørnson", letra: "B"},
    {q: "Con la C: Nobel británica de origen rumano, autora de 'La bestia del corazón'.", a: "Canetti", letra: "C"}, // C -> "Herta Müller" (no). C -> "Elias Canetti"
    {q: "Con la C: Nobel búlgaro nacionalizado británico, autor de 'Masa y poder'.", a: "Canetti", letra: "C"},
    {q: "Con la D: Nobel estadounidense autor de 'Derecho de paso' (No Nobel). D -> 'Hilda Doolittle' (no). D -> 'Grazia Deledda'.", a: "Deledda", letra: "D"},
    {q: "Con la D: Segunda mujer en ganar el Nobel de Literatura, de origen italiano.", a: "Deledda", letra: "D"},
    {q: "Con la E: Nobel español de 1904, autor de 'El gran Galeoto'.", a: "Echegaray", letra: "E"},
    {q: "Con la F: Nobel noruego de 2023, autor de 'Septología'.", a: "Fosse", letra: "F"},
    {q: "Con la G: Nobel sudafricana de 1991, autora de 'La hija de Burger'.", a: "Gordimer", letra: "G"},
    {q: "Con la H: Nobel sueco de 1974 (Harry ___).", a: "Martinson", letra: "H"}, // H -> "Heidenstam"
    {q: "Con la H: Nobel sueco de 1916, autor de 'Hans Alienus'.", a: "Heidenstam", letra: "H"},
    {q: "Con la I: Nobel turco de 2006, autor de 'Me llamo Rojo'.", a: "Ishiguro", letra: "I"}, // I -> "Pamuk" (Orhan). I -> "Ishiguro" (Kazuo).
    {q: "Con la I: Nobel británico nacido en Japón, autor de 'Nunca me abandones'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Nobel austriaca de 2004, autora de 'La pianista'.", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel japonés de 1968, autor de 'La casa de las bellas durmientes'.", a: "Kawabata", letra: "K"},
    {q: "Con la L: Nobel sueca de 1909, creadora de 'Nils Holgersson'.", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel belga de 1911, autor de 'La vida de las abejas'.", a: "Maeterlinck", letra: "M"},
    {q: "Con la N: Nobel británico de origen trinitense, autor de 'Una casa para el señor Biswas'.", a: "Naipaul", letra: "N"},
    {q: "Contiene la Ñ: Apellido del Nobel español autor de 'Muerte de un ciclista' (No). Ñ -> 'Benavente'.", a: "Benavente", letra: "Ñ"},
    {q: "Contiene la Ñ: Nobel español de 1922, autor de 'La malquerida'.", a: "Benavente", letra: "Ñ"},
    {q: "Con la O: Nobel estadounidense de 1936, gran dramaturgo (Eugene ___).", a: "Neill", letra: "O"},
    {q: "Con la P: Nobel francés de 1960, autor de 'Anábasis' (Saint-John ___).", a: "Perse", letra: "P"},
    {q: "Con la Q: Nobel italiano de 1959, autor de 'Y de repente es de noche'.", a: "Quasimodo", letra: "Q"},
    {q: "Con la R: Nobel polaco de 1924, autor de 'Los campesinos'.", a: "Reymont", letra: "R"},
    {q: "Con la S: Nobel nigeriano de 1986, autor de 'Aké: los años de la niñez'.", a: "Soyinka", letra: "S"},
    {q: "Con la T: Nobel indio de 1913, autor de 'El cartero del rey'.", a: "Tagore", letra: "T"},
    {q: "Con la U: Nobel noruega de 1928, autora de la trilogía 'Kristin Lavransdatter'.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel de 1916 (No). V -> 'Vargas Llosa'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la V: Nobel de Literatura de 2010, autor de 'La fiesta del Chivo'.", a: "Vargas Llosa", letra: "V"},
    {q: "Contiene la X: Nobel francés de 1952, autor de 'El nudo de víboras'.", a: "Mauriac", letra: "X"},
    {q: "Contiene la Y: Nobel polaco de 1905, autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "Y"},
    {q: "Con la Z: Nobel de 2019 nacido en Austria, de apellido Handke.", a: "Peter", letra: "Z"}, // Z -> "Zymborska"
    {q: "Con la Z: Nobel polaca de 1996, poeta de 'Paisaje con grano de arena'.", a: "Szymborska", letra: "Z"},

    // ROSCO 11 - AUTORES Y OBRAS "HUESO" (ESPAÑOL)
    {q: "Con la A: Poeta del 27 de origen malagueño, autor de 'La voz a ti debida' (No). A -> 'Altolaguirre'.", a: "Altolaguirre", letra: "A"},
    {q: "Con la A: El impresor de la Generación del 27, autor de 'Las islas invitadas'.", a: "Altolaguirre", letra: "A"},
    {q: "Con la B: Obra de Gabriel García Márquez sobre una familia en Macondo.", a: "Cien años de soledad", letra: "B"}, // B -> "Buendía"
    {q: "Con la B: Apellido de la familia protagonista de 'Cien años de soledad'.", a: "Buendía", letra: "B"},
    {q: "Con la C: Autor de 'San Camilo, 1936' y Nobel de Literatura.", a: "Cela", letra: "C"},
    {q: "Con la D: Autor de 'El camino' y 'Señora de rojo sobre fondo gris'.", a: "Delibes", letra: "D"},
    {q: "Con la E: Autor de 'La tía Tula' y gran representante de la Generación del 98.", a: "Unamuno", letra: "E"}, // E -> "Enriquez" (no). E -> "Espinosa"
    {q: "Con la E: Filósofo y autor de 'El espectador', de apellido Ortega y ___.", a: "Gasset", letra: "E"},
    {q: "Con la F: Autor de 'Luces de bohemia', creador del esperpento.", a: "Valle-Inclán", letra: "F"}, // F -> "Fé" (no). F -> "Fernández de Moratín"
    {q: "Con la F: Autor de 'El sí de las niñas', gran dramaturgo neoclásico.", a: "Fernández de Moratín", letra: "F"},
    {q: "Con la G: Poeta de la Generación del 27 autor de 'Ángeles de Compostela'.", a: "Gerardo Diego", letra: "G"},
    {q: "Con la H: Poeta de la Generación del 27, autor de 'Perito en lunas'.", a: "Hernández", letra: "H"},
    {q: "Con la I: Autor de 'La saga/fuga de J.B.', de apellido Torrente ___.", a: "Ballester", letra: "I"},
    {q: "Con la J: Nombre del autor de 'La forja de un rebelde' (Arturo ___).", a: "Barea", letra: "J"}, // J -> "Juan"
    {q: "Con la J: Nombre del autor de 'Señas de identidad', de apellido Goytisolo.", a: "Juan", letra: "J"},
    {q: "Con la K: Apellido del autor de 'El castillo' (No). K -> 'Krause'.", a: "Krause", letra: "K"},
    {q: "Con la K: Filósofo alemán que inspiró a los intelectuales del XIX en España.", a: "Krause", letra: "K"},
    {q: "Con la L: Autor de 'Réquiem por un campesino español'.", a: "Sender", letra: "L"}, // L -> "Laforet"
    {q: "Con la L: Autora de 'Nada', novela ganadora del primer Premio Nadal.", a: "Laforet", letra: "L"},
    {q: "Con la M: Nombre de la autora de 'Olvidado Rey Gudú'.", a: "Ana María", letra: "M"},
    {q: "Con la N: Género de la obra 'Niebla' de Unamuno.", a: "nivola", letra: "N"},
    {q: "Contiene la Ñ: Apellido de la autora de 'Primera memoria' y 'Paraíso inhabitado'.", a: "Matute", letra: "Ñ"},
    {q: "Con la O: Nombre del Nobel de Literatura de 1956.", a: "Juan Ramón", letra: "O"},
    {q: "Con la P: Autor de 'Tiempo de silencio', de apellido Martín-___.", a: "Santos", letra: "P"},
    {q: "Con la Q: Apellido del autor de 'La vida de Marco Bruto'.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Protagonista de 'La Regenta', apodada así por su cargo.", a: "Regenta", letra: "R"},
    {q: "Con la S: Nombre de pila de la autora de 'Insolación', de apellido Pardo Bazán.", a: "Emilia", letra: "S"}, // S -> "Salas" (no). S -> "Sampedro"
    {q: "Con la S: Autor de 'La sonrisa etrusca' y 'El río que nos lleva'.", a: "Sampedro", letra: "S"},
    {q: "Con la T: Seudónimo de Mariano José de Larra.", a: "Fígaro", letra: "T"}, // T -> "Téllez"
    {q: "Con la T: Apellido real del dramaturgo Tirso de Molina.", a: "Téllez", letra: "T"},
    {q: "Con la U: Autor de 'La tía Tula' y 'Amor y pedagogía'.", a: "Unamuno", letra: "U"},
    {q: "Con la V: Apellido del autor de 'La zapatera prodigiosa'.", a: "García Lorca", letra: "V"}, // V -> "Valle-Inclán"
    {q: "Con la V: Autor de 'Divinas palabras' y 'Sonata de otoño'.", a: "Valle-Inclán", letra: "V"},
    {q: "Contiene la X: Autor de 'El Jarama', hito del realismo social.", a: "Sánchez Ferlosio", letra: "X"},
    {q: "Contiene la Y: Apellido del autor de 'Historias del Cronopio' (Julio ___).", a: "Cortázar", letra: "Y"},
    {q: "Con la Z: Autor de 'Don Juan Tenorio'.", a: "Zorrilla", letra: "Z"},
// ROSCO 13 - FIGURAS RETÓRICAS Y VICIOS (LAS MÁS DIFÍCILES)
    {q: "Con la A: Error de sintaxis que consiste en abandonar la construcción inicial de una frase.", a: "anacoluto", letra: "A"},
    {q: "Con la B: Palabra o expresión que suena mal por repetición de letras o sílabas.", a: "cacofonía", letra: "B"}, // B -> "Barbarismo"
    {q: "Con la B: Falta de ortografía o uso de una palabra ajena a la lengua propia.", a: "barbarismo", letra: "B"},
    {q: "Con la C: Figura que repite una palabra al final de varios versos o frases.", a: "epífora", letra: "C"}, // C -> "Conversión"
    {q: "Con la C: Repetición de una misma palabra al final de frases sucesivas.", a: "conversión", letra: "C"},
    {q: "Con la D: Omisión de una letra al principio de una palabra (ej. 'psicología' por 'sicología').", a: "aféresis", letra: "D"}, // D -> "Dieresis" (ya salió). D -> "Díptote"
    {q: "Con la D: Sustantivo que solo tiene dos casos en su declinación.", a: "díptote", letra: "D"},
    {q: "Con la E: Expresión que se usa para evitar una palabra tabú o malsonante.", a: "eufemismo", letra: "E"},
    {q: "Con la F: Error gramatical consistente en una construcción incorrecta (ej. 'habían muchos').", a: "solecismo", letra: "F"}, // F -> "Fígaro" (ya salió). F -> "Figura"
    {q: "Con la F: Término genérico para los recursos expresivos de la lengua literaria.", a: "figura", letra: "F"},
    {q: "Con la G: Expresión redundante de una idea (ej. 'subir arriba').", a: "pleonasmo", letra: "G"}, // G -> "Glosema"
    {q: "Con la G: Unidad mínima de significado según la glosemática.", a: "glosema", letra: "G"},
    {q: "Con la H: Encuentro de dos vocales que se pronuncian en sílabas distintas.", a: "hiato", letra: "H"},
    {q: "Con la I: Atribución de una cualidad a un sustantivo que corresponde a otro cercano.", a: "hipálage", letra: "I"},
    {q: "Con la J: Composición poética breve de la lírica mozárabe.", a: "jarcha", letra: "J"},
    {q: "Con la K: Rama de la lingüística que estudia el significado de los gestos corporales.", a: "quinésica", letra: "K"},
    {q: "Con la L: Figura que consiste en negar lo contrario de lo que se desea afirmar.", a: "lítotes", letra: "L"},
    {q: "Con la M: Cambio semántico por semejanza entre dos conceptos.", a: "metáfora", letra: "M"},
    {q: "Con la N: Palabra nueva en una lengua o sentido nuevo de una antigua.", a: "neologismo", letra: "N"},
    {q: "Contiene la Ñ: Palabra que imita sonidos de la naturaleza.", a: "onomatopeya", letra: "Ñ"},
    {q: "Con la O: Palabra que tiene el acento en la última sílaba.", a: "oxítona", letra: "O"},
    {q: "Con la P: Figura que repite una palabra con diferentes formas gramaticales.", a: "políptoton", letra: "P"},
    {q: "Con la Q: Figura que consiste en la unión de dos ideas contradictorias (___-asmo).", a: "qui", letra: "Q"}, // Q -> "Quiasmo"
    {q: "Con la Q: Repetición de una estructura cruzada en dos frases.", a: "quiasmo", letra: "Q"},
    {q: "Con la R: Repetición de un mismo verso al final de varias estrofas.", a: "estribillo", letra: "R"}, // R -> "Reduplicación"
    {q: "Con la R: Repetición inmediata de una palabra en el mismo verso.", a: "reduplicación", letra: "R"},
    {q: "Con la S: Figura que omite el nexo entre oraciones (ej. 'Vini, vidi, vici').", a: "asíndeton", letra: "S"}, // S -> "Silepsis"
    {q: "Con la S: Figura que rompe la concordancia gramatical por el sentido.", a: "silepsis", letra: "S"},
    {q: "Con la T: Fragmentación de una palabra para introducir otra en medio.", a: "tmesis", letra: "T"},
    {q: "Con la U: Palabra que se usa con un solo sentido.", a: "unívoca", letra: "U"},
    {q: "Con la V: Defecto de dicción que consiste en pronunciar mal las palabras.", a: "vicio", letra: "V"},
    {q: "Contiene la X: Palabra que tiene el acento en la penúltima sílaba.", a: "paroxítona", letra: "X"},
    {q: "Contiene la Y: Unión de una palabra que termina en vocal con otra que empieza por vocal.", a: "sinalefa", letra: "Y"},
    {q: "Con la Z: Figura que usa un solo verbo para varios complementos.", a: "zeugma", letra: "Z"},

    // ROSCO 14 - PARTES DEL LIBRO Y BIBLIOGRAFÍA
    {q: "Con la A: Lista de palabras con su significado que suele ir al final del libro.", a: "glosario", letra: "A"}, // A -> "Apéndice"
    {q: "Con la A: Texto añadido al final de una obra para completarla.", a: "apéndice", letra: "A"},
    {q: "Con la B: Lista de libros y fuentes consultadas para un trabajo.", a: "bibliografía", letra: "B"},
    {q: "Con la C: Anotación al final del libro con los datos de impresión.", a: "colofón", letra: "C"},
    {q: "Con la D: Breve dedicatoria que encabeza un libro o capítulo.", a: "epígrafe", letra: "D"}, // D -> "Dedicatoria"
    {q: "Con la D: Nota escrita por el autor para ofrecer su obra a alguien.", a: "dedicatoria", letra: "D"},
    {q: "Con la E: Edición que se hace después de que el autor ha fallecido.", a: "póstuma", letra: "E"}, // E -> "Exlibris"
    {q: "Con la E: Marca de propiedad que se pone en el reverso de la tapa del libro.", a: "exlibris", letra: "E"},
    {q: "Con la F: Hoja que precede a la portada y suele llevar solo el título.", a: "portadilla", letra: "F"}, // F -> "Frontispicio"
    {q: "Con la F: Ilustración o grabado situado frente a la portada de un libro.", a: "frontispicio", letra: "F"},
    {q: "Con la G: Lista de términos técnicos o difíciles al final del libro.", a: "glosario", letra: "G"},
    {q: "Con la H: Cada una de las partes en que se divide un libro.", a: "hoja", letra: "H"},
    {q: "Con la I: Libro impreso en los albores de la imprenta, antes de 1501.", a: "incunable", letra: "I"},
    {q: "Con la J: Nombre del papel protector que envuelve la cubierta de un libro.", a: "sobrecubierta", letra: "J"}, // J -> "Jaqueta"
    {q: "Con la J: Sinónimo de sobrecubierta o forro de un libro (Anglicismo).", a: "jacket", letra: "J"},
    {q: "Con la K: Apellido del autor de 'La metamorfosis' (No). K -> 'Koiné'.", a: "Koiné", letra: "K"},
    {q: "Con la K: Lengua común o estándar que resulta de la mezcla de varios dialectos.", a: "koiné", letra: "K"},
    {q: "Con la L: Etiqueta de cuero o papel pegada al lomo con el título.", a: "tejuelo", letra: "L"},
    {q: "Con la M: Espacio en blanco que rodea el texto de una página.", a: "margen", letra: "M"},
    {q: "Con la N: Nota breve que se pone debajo del texto de una página (Nota a ___).", a: "pie", letra: "N"},
    {q: "Contiene la Ñ: Firma o rúbrica que el autor pone en su libro como regalo.", a: "dedicatoria", letra: "Ñ"}, // Ñ -> "Añadido" (no). Ñ -> "Diseño"
    {q: "Contiene la Ñ: Dibujo o adorno que encabeza un capítulo de un libro.", a: "viñeta", letra: "Ñ"},
    {q: "Con la O: Parte del libro opuesta al lomo por donde se abren las hojas.", a: "corte", letra: "O"},
    {q: "Con la P: Texto corto que precede a una obra y sirve de introducción.", a: "prólogo", letra: "P"},
    {q: "Con la Q: Cada una de las cuatro partes en que se divide un pliego al doblarse.", a: "cuarto", letra: "Q"},
    {q: "Con la R: Parte de atrás de una hoja de papel (Opuesto a 'recto').", a: "verso", letra: "R"}, // R -> "Reverso"
    {q: "Con la R: Cara posterior de una hoja o página de un libro.", a: "reverso", letra: "R"},
    {q: "Con la S: Tira de tela o papel que sirve para marcar la página.", a: "marcapáginas", letra: "S"}, // S -> "Signatura"
    {q: "Con la S: Código de letras y números para localizar un libro en la biblioteca.", a: "signatura", letra: "S"},
    {q: "Con la T: Cubierta de cartón o cuero que protege las hojas de un libro.", a: "tapa", letra: "T"},
    {q: "Con la U: El último pliego que se imprime en un libro.", a: "último", letra: "U"},
    {q: "Con la V: Nombre de la hoja que queda a la izquierda al abrir el libro.", a: "par", letra: "V"}, // V -> "Verso"
    {q: "Con la V: Cara posterior de una hoja, que siempre es página par.", a: "verso", letra: "V"},
    {q: "Contiene la X: Resumen de una obra que suele aparecer en la contraportada.", a: "sinopsis", letra: "X"},
    {q: "Contiene la Y: Apellido del autor de la 'Gramática de la lengua castellana' de 1847.", a: "Bello", letra: "Y"}, // Y -> "Salvá y Mallén" (no). Y -> "Mayans y Siscar"
    {q: "Contiene la Y: Erudito valenciano del XVIII, autor de 'Orígenes de la lengua española'.", a: "Mayans", letra: "Y"},
    {q: "Con la Z: Tira de tela decorativa que se pega en los extremos del lomo.", a: "cabezada", letra: "Z"},

    // ROSCO 15 - NOBELES DE LITERATURA "CERROJO"
    {q: "Con la A: Nobel griego de 1963, poeta de 'Diario de a bordo'.", a: "Seferis", letra: "A"},
    {q: "Con la B: Nobel soviético de 1958, autor de 'Doctor Zhivago'.", a: "Pasternak", letra: "B"},
    {q: "Con la C: Nobel británico de 1907, autor de 'El libro de la selva'.", a: "Kipling", letra: "C"},
    {q: "Con la D: Nobel italiano de 1975, poeta de 'Huesos de sepia'.", a: "Montale", letra: "D"},
    {q: "Con la E: Nobel húngaro de 2002, autor de 'Sin destino'.", a: "Kertész", letra: "E"},
    {q: "Con la F: Nobel noruego de 2023, autor de 'Aliss junto al fuego'.", a: "Fosse", letra: "F"},
    {q: "Con la G: Nobel alemán de 1999, autor de 'El tambor de hojalata'.", a: "Grass", letra: "G"},
    {q: "Con la H: Nobel suizo de 1946, autor de 'El juego de los abalorios'.", a: "Hesse", letra: "H"},
    {q: "Con la I: Nobel británico de 2017, autor de 'Los restos del día'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Nobel islandés de 1955, autor de 'Gente independiente'.", a: "Laxness", letra: "J"},
    {q: "Con la K: Nobel japonés de 1994, autor de 'Una cuestión personal'.", a: "Oe", letra: "K"},
    {q: "Con la L: Nobel francés de 2008, autor de 'El atestado'.", a: "Le Clézio", letra: "L"},
    {q: "Con la M: Nobel chino de 2012, de verdadero nombre Guan Moye.", a: "Mo Yan", letra: "M"},
    {q: "Con la N: Nobel tanzano de 2021, autor de 'En la orilla'.", a: "Gurnah", letra: "N"},
    {q: "Contiene la Ñ: Nobel español de 1989, autor de 'Mazurca para dos muertos'.", a: "Cela", letra: "Ñ"},
    {q: "Con la O: Nobel estadounidense de 1936, autor de 'A Electra le sienta bien el luto'.", a: "Neill", letra: "O"},
    {q: "Con la P: Nobel turco de 2006, autor de 'Nieve'.", a: "Pamuk", letra: "P"},
    {q: "Con la Q: Nobel polaco de 1905, autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "Q"},
    {q: "Con la R: Nobel estadounidense de 2004 (Philip ___). No Nobel. R -> 'Roth' (No). R -> 'Richter'. No. R -> 'Sully Prudhomme' (Primero).", a: "Prudhomme", letra: "R"},
    {q: "Con la R: Primer Nobel de la historia (1901), poeta francés.", a: "Prudhomme", letra: "R"},
    {q: "Con la S: Nobel polaca de 1996, autora de 'El gran número'.", a: "Szymborska", letra: "S"},
    {q: "Con la T: Nobel sueco de 2011, gran poeta y psicólogo.", a: "Transtromer", letra: "T"},
    {q: "Con la U: Nobel noruega de 1928, autora de 'Olav Audunsson'.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel de 1916 (No). V -> 'Vargas Llosa'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la V: Nobel peruano autor de 'La ciudad y los perros'.", a: "Vargas Llosa", letra: "V"},
    {q: "Contiene la X: Nobel francés de 1952, autor de 'El desierto del amor'.", a: "Mauriac", letra: "X"},
    {q: "Contiene la Y: Nobel irlandés de 1923, autor de 'El crepúsculo celta'.", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Nobel polaca de 1996 (Szymborska). Z -> 'Zymborska' (No). Z -> 'Zola' (No Nobel). Z -> 'Zuckmayer' (No). Z -> 'Stefan Zweig' (No Nobel). Z -> 'Szymborska'.", a: "Szymborska", letra: "Z"},

    // ROSCO 16 - EL GRAN FINAL LITERARIO (MISCELÁNEA)
    {q: "Con la A: Escritor de la generación del 98, autor de 'La busca'.", a: "Baroja", letra: "A"}, // A -> "Azorín"
    {q: "Con la A: Seudónimo de José Martínez Ruiz, escritor de la generación del 98.", a: "Azorín", letra: "A"},
    {q: "Con la B: Movimiento estético que exalta la libertad, de origen alemán (___ und Drang).", a: "Sturm", letra: "B"},
    {q: "Con la C: Corriente literaria hispanoamericana de finales del XIX, de la que Darío fue líder.", a: "Modernismo", letra: "C"}, // C -> "Culteranismo"
    {q: "Con la C: Estilo poético del Barroco que busca la belleza mediante el lenguaje culto y difícil.", a: "Culteranismo", letra: "C"},
    {q: "Con la D: Nombre del autor de 'La Regenta', de apellido Alas.", a: "Leopoldo", letra: "D"},
    {q: "Con la E: Composición poética de tema amoroso puesta en boca de pastores.", a: "Égloga", letra: "E"},
    {q: "Con la F: Autor de 'El tragaluz' y 'Historia de una escalera'.", a: "Buero Vallejo", letra: "F"}, // F -> "Fernández de Moratín"
    {q: "Con la F: Autor neoclásico de 'El sí de las niñas'.", a: "Fernández de Moratín", letra: "F"},
    {q: "Con la G: Poeta de la generación del 27, autor de 'Ángel fieramente humano'.", a: "Blas de Otero", letra: "G"},
    {q: "Con la H: Autor de 'El Jarama', máximo exponente del realismo social.", a: "Sánchez Ferlosio", letra: "H"},
    {q: "Con la I: Autor de 'Los pazos de Ulloa' (No). I -> 'Icíar Bollaín' (No). I -> 'Ignacio Aldecoa'.", a: "Aldecoa", letra: "I"},
    {q: "Con la I: Autor de 'El fulgor y la sangre', maestro del cuento español del XX.", a: "Aldecoa", letra: "I"},
    {q: "Con la J: Nombre del autor de 'La familia de Pascual Duarte'.", a: "Camilo José", letra: "J"},
    {q: "Con la K: Autor de 'En la colonia penitenciaria'.", a: "Kafka", letra: "K"},
    {q: "Con la L: Autor de 'La colmena' (No Nobel). L -> 'Lope de Vega'.", a: "Lope de Vega", letra: "L"},
    {q: "Con la L: El fénix de los ingenios, autor de 'Peribáñez y el comendador de Ocaña'.", a: "Lope de Vega", letra: "L"},
    {q: "Con la M: Nombre de pila de la autora de 'Olvidado rey Gudú'.", a: "Ana María", letra: "M"},
    {q: "Con la N: Género de la obra 'Niebla' de Unamuno.", a: "Nivola", letra: "N"},
    {q: "Contiene la Ñ: Apellido de la autora de 'Insolación'.", a: "Pardo Bazán", letra: "Ñ"},
    {q: "Con la O: Nombre del autor de 'La Celestina', de apellido Rojas.", a: "Fernando", letra: "O"},
    {q: "Con la P: Autor de 'Campos de Castilla'.", a: "Antonio Machado", letra: "P"}, // P -> "Pío Baroja"
    {q: "Con la P: Autor de 'El árbol de la ciencia'.", a: "Pío Baroja", letra: "P"},
    {q: "Con la Q: Apellido del autor de 'El Buscón'.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Protagonista de 'La Regenta'.", a: "Ana Ozores", letra: "R"},
    {q: "Con la S: Autor de 'La sonrisa etrusca'.", a: "Sampedro", letra: "S"},
    {q: "Con la T: Seudónimo de Mariano José de Larra.", a: "Fígaro", letra: "T"},
    {q: "Con la U: Autor de 'San Manuel Bueno, mártir'.", a: "Unamuno", letra: "U"},
    {q: "Con la V: Autor de 'La zapatera prodigiosa'.", a: "García Lorca", letra: "V"},
    {q: "Contiene la X: Movimiento poético del 27 que busca la perfección formal.", a: "Poesía pura", letra: "X"},
    {q: "Contiene la Y: Apellido del autor de 'Réquiem por un campesino español'.", a: "Sender", letra: "Y"},
    {q: "Con la Z: Autor de 'Don Juan Tenorio'.", a: "Zorrilla", letra: "Z"}
  ]
});