// mazos/mazo_ciencia.js
if (typeof MAZOS === 'undefined') { var MAZOS = []; }

MAZOS.push({
  id: "ciencia", 
  name: "Ciencia y Tecnología", 
  icon: "🔬", 
  questions: [
    // ROSCO 1 - BIOLOGÍA Y CUERPO HUMANO
    {q: "Con la A: Molécula que contiene las instrucciones genéticas usadas en el desarrollo de los seres vivos (Siglas).", a: "ADN", letra: "A"},
    {q: "Con la B: Microorganismo unicelular sin núcleo definido que puede causar enfermedades o ser beneficioso.", a: "bacteria", letra: "B"},
    {q: "Con la C: Unidad anatómica y fisiológica fundamental de todos los seres vivos.", a: "célula", letra: "C"},
    {q: "Con la D: Movimiento de relajación y expansión del corazón y las arterias.", a: "diástole", letra: "D"},
    {q: "Con la E: Proteína que cataliza y acelera las reacciones químicas en los seres vivos.", a: "enzima", letra: "E"},
    {q: "Con la F: Proceso químico que tiene lugar en las plantas con clorofila y que permite, gracias a la luz, transformar un sustrato inorgánico en materia orgánica rica en energía.", a: "fotosíntesis", letra: "F"},
    {q: "Con la G: Rama de la biología que estudia cómo los caracteres hereditarios se transmiten de generación en generación.", a: "genética", letra: "G"},
    {q: "Con la H: Pigmento rojo contenido en los glóbulos rojos de la sangre de los vertebrados, cuya función consiste en captar el oxígeno.", a: "hemoglobina", letra: "H"},
    {q: "Con la I: Capacidad del cuerpo humano para resistir una enfermedad infecciosa o defenderse de agentes patógenos.", a: "inmunidad", letra: "I"},
    {q: "Con la J: Líquido ácido segregado por las glándulas del estómago, fundamental para la digestión (___ gástrico).", a: "jugo", letra: "J"},
    {q: "Con la L: Glóbulo blanco de la sangre, encargado de defender el organismo contra las infecciones.", a: "leucocito", letra: "L"},
    {q: "Con la M: Orgánulo celular encargado de suministrar la mayor parte de la energía necesaria para la actividad celular.", a: "mitocondria", letra: "M"},
    {q: "Con la N: Célula especializada del sistema nervioso cuya función principal es recibir, procesar y transmitir información.", a: "neurona", letra: "N"},
    {q: "Contiene la Ñ: Cada uno de los dos órganos excretores de los vertebrados, encargados de filtrar la sangre y producir la orina.", a: "riñón", letra: "Ñ"},
    {q: "Con la O: Órgano reproductor femenino encargado de producir los óvulos.", a: "ovario", letra: "O"},
    {q: "Con la P: Glándula del sistema digestivo que segrega insulina y jugo pancreático.", a: "páncreas", letra: "P"},
    {q: "Con la Q: Entrecruzamiento en forma de 'X' de dos estructuras anatómicas, como el que forman los nervios ópticos.", a: "quiasma", letra: "Q"},
    {q: "Con la R: Membrana interior del ojo en la cual se forman las imágenes visuales que se transmiten al cerebro.", a: "retina", letra: "R"},
    {q: "Con la S: Conexión o espacio entre dos neuronas por donde se transmiten los impulsos nerviosos.", a: "sinapsis", letra: "S"},
    {q: "Con la T: Coágulo de sangre que se forma en el interior de un vaso sanguíneo y que puede obstruirlo.", a: "trombo", letra: "T"},
    {q: "Con la U: Órgano muscular hueco de las hembras de los mamíferos, en el que se desarrolla el feto.", a: "útero", letra: "U"},
    {q: "Con la V: Preparado biológico que proporciona inmunidad adquirida activa ante una determinada enfermedad.", a: "vacuna", letra: "V"},
    {q: "Contiene la X: Cada uno de los dos huesos que forman la mandíbula superior en los vertebrados.", a: "maxilar", letra: "X"},
    {q: "Con la Y: Segunda porción del intestino delgado, situada entre el duodeno y el íleon.", a: "yeyuno", letra: "Y"},
    {q: "Con la Z: Célula resultante de la unión del espermatozoide y el óvulo en la reproducción sexual.", a: "zigoto", letra: "Z"},

    // ROSCO 2 - FÍSICA, QUÍMICA Y ELEMENTOS
    {q: "Con la A: Porción material menor de un elemento químico que interviene en las reacciones químicas y posee las propiedades características de dicho elemento.", a: "átomo", letra: "A"},
    {q: "Con la B: Instrumento para medir la presión atmosférica.", a: "barómetro", letra: "B"},
    {q: "Con la C: Rama de la física que estudia el movimiento de los cuerpos en el espacio sin atender a las causas que lo producen.", a: "cinemática", letra: "C"},
    {q: "Con la D: Magnitud que expresa la relación entre la masa y el volumen de un cuerpo.", a: "densidad", letra: "D"},
    {q: "Con la E: Partícula subatómica con carga eléctrica elemental negativa.", a: "electrón", letra: "E"},
    {q: "Con la F: Partícula mínima de energía luminosa o de otra energía electromagnética que se produce, se transmite y se absorbe.", a: "fotón", letra: "F"},
    {q: "Con la G: Fuerza física de atracción que ejerce la masa de la Tierra sobre los cuerpos situados en ella.", a: "gravedad", letra: "G"},
    {q: "Con la H: Elemento químico de número atómico 2, que es un gas noble muy ligero e inflamable.", a: "helio", letra: "H"},
    {q: "Con la I: Propiedad de los cuerpos de mantener su estado de reposo o de movimiento rectilíneo uniforme si no actúan fuerzas sobre ellos.", a: "inercia", letra: "I"},
    {q: "Con la J: Unidad del Sistema Internacional para medir energía, trabajo y calor.", a: "julio", letra: "J"},
    {q: "Con la L: Elemento químico metálico, el más ligero de todos los metales sólidos, muy usado en baterías.", a: "litio", letra: "L"},
    {q: "Con la M: Magnitud física que expresa la cantidad de materia de un cuerpo, medida por la inercia de este.", a: "masa", letra: "M"},
    {q: "Con la N: Partícula subatómica sin carga eléctrica neta, presente en el núcleo atómico.", a: "neutrón", letra: "N"},
    {q: "Contiene la Ñ: Elemento químico metálico cuyo símbolo en la tabla periódica es Sn.", a: "estaño", letra: "Ñ"},
    {q: "Con la O: Paso de disolvente a través de una membrana semipermeable desde una disolución más diluida a otra más concentrada.", a: "ósmosis", letra: "O"},
    {q: "Con la P: Partícula subatómica con carga eléctrica elemental positiva.", a: "protón", letra: "P"},
    {q: "Con la Q: Ciencia que estudia la composición, estructura y propiedades de la materia, así como sus transformaciones.", a: "química", letra: "Q"},
    {q: "Con la R: Propiedad de ciertos elementos químicos de emitir espontáneamente radiaciones penetrantes.", a: "radiactividad", letra: "R"},
    {q: "Con la S: Paso directo de una sustancia del estado sólido al gaseoso sin pasar por el estado líquido.", a: "sublimación", letra: "S"},
    {q: "Con la T: Parte de la física que estudia las relaciones entre el calor y el resto de formas de energía.", a: "termodinámica", letra: "T"},
    {q: "Con la U: Elemento químico radiactivo de número atómico 92, utilizado como combustible principal en las centrales nucleares.", a: "uranio", letra: "U"},
    {q: "Con la V: Magnitud física que expresa el espacio recorrido por un móvil en la unidad de tiempo.", a: "velocidad", letra: "V"},
    {q: "Contiene la X: Gas esencial para la respiración de los seres vivos y para la combustión.", a: "oxígeno", letra: "X"},
    {q: "Con la Y: Elemento químico halógeno de número atómico 53, cuyo déficit en la dieta provoca bocio.", a: "yodo", letra: "Y"},
    {q: "Con la Z: Elemento metálico de número atómico 30, cuyo símbolo es Zn, usado para galvanizar el acero.", a: "zinc", letra: "Z"},

    // ROSCO 3 - ASTRONOMÍA Y TECNOLOGÍA
    {q: "Con la A: Cuerpo rocoso o metálico, más pequeño que un planeta, que orbita alrededor del Sol.", a: "asteroide", letra: "A"},
    {q: "Con la B: Gran explosión con la que, según la cosmología moderna, se originó el universo.", a: "Big Bang", letra: "B"},
    {q: "Con la C: Cuerpo celeste formado por hielo y rocas que orbita el Sol y desarrolla una cola luminosa al acercarse a él.", a: "cometa", letra: "C"},
    {q: "Con la D: Componente electrónico que permite el paso de la corriente eléctrica en un solo sentido.", a: "diodo", letra: "D"},
    {q: "Con la E: Ocultación transitoria total o parcial de un astro por interposición de otro.", a: "eclipse", letra: "E"},
    {q: "Con la F: Reacción nuclear en la que el núcleo de un átomo pesado se divide en dos o más núcleos ligeros, liberando gran cantidad de energía.", a: "fisión", letra: "F"},
    {q: "Con la G: Agrupación gigantesca de estrellas, planetas, polvo y gas cósmico unidos por la gravedad.", a: "galaxia", letra: "G"},
    {q: "Con la H: Conjunto de los componentes físicos, mecánicos o electrónicos de un sistema informático.", a: "hardware", letra: "H"},
    {q: "Con la I: Red informática mundial, descentralizada, formada por la conexión directa entre computadoras mediante un protocolo especial.", a: "internet", letra: "I"},
    {q: "Con la J: El planeta más grande del sistema solar, un gigante gaseoso situado después de Marte.", a: "Júpiter", letra: "J"},
    {q: "Con la L: Dispositivo que utiliza un efecto de la mecánica cuántica para generar un haz de luz coherente y muy intenso.", a: "láser", letra: "L"},
    {q: "Con la M: Fragmento de un cuerpo celeste que cae sobre la Tierra o sobre cualquier astro.", a: "meteorito", letra: "M"},
    {q: "Con la N: Nube gigante de polvo y gas en el espacio, que a menudo es el lugar donde nacen las estrellas.", a: "nebulosa", letra: "N"},
    {q: "Contiene la Ñ: Palabra clave o código secreto que permite el acceso a un sistema informático o cuenta de usuario.", a: "contraseña", letra: "Ñ"},
    {q: "Con la O: Curva que describe un astro o nave espacial en torno a otro cuerpo bajo la influencia de fuerzas gravitatorias.", a: "órbita", letra: "O"},
    {q: "Con la P: Cuerpo celeste sólido que gira alrededor de una estrella y que no emite luz propia.", a: "planeta", letra: "P"},
    {q: "Con la Q: Fuente de energía astronómica extremadamente lejana y luminosa, propulsada por un agujero negro supermasivo.", a: "quásar", letra: "Q"},
    {q: "Con la R: Sistema que utiliza ondas electromagnéticas para medir distancias, altitudes, direcciones y velocidades de objetos estáticos o móviles.", a: "radar", letra: "R"},
    {q: "Con la S: Cuerpo celeste opaco que gira alrededor de un planeta primario.", a: "satélite", letra: "S"},
    {q: "Con la T: Instrumento óptico que permite observar objetos lejanos, especialmente astros, con mucho más detalle que a simple vista.", a: "telescopio", letra: "T"},
    {q: "Con la U: Conjunto de todo lo que tiene existencia física, en la Tierra y fuera de ella.", a: "universo", letra: "U"},
    {q: "Con la V: Nombre de la galaxia espiral en la que se encuentra el sistema solar y la Tierra (___ Láctea).", a: "Vía", letra: "V"},
    {q: "Contiene la X: Cada uno de los puntos luminosos de color que forman la unidad mínima de una imagen digital en una pantalla.", a: "píxel", letra: "X"},
    {q: "Contiene la Y: Unidad de información en computación que, por lo general, está compuesta por 8 bits.", a: "byte", letra: "Y"},
    {q: "Con la Z: Franja del firmamento por la que aparentemente transitan el Sol y los planetas, dividida en doce constelaciones.", a: "zodíaco", letra: "Z"},

    // ROSCO 4 - NATURALEZA, ANIMALES Y BOTÁNICA
    {q: "Con la A: Clase de vertebrados de sangre fría que pasan una fase de su vida en el agua respirando por branquias y otra en la tierra con pulmones.", a: "anfibios", letra: "A"},
    {q: "Con la B: Rama de la biología que estudia las plantas.", a: "botánica", letra: "B"},
    {q: "Con la C: Pigmento de color verde que se halla presente en las hojas y tallos de muchos vegetales.", a: "clorofila", letra: "C"},
    {q: "Con la D: Animal que caza a otros de distinta especie para su subsistencia.", a: "depredador", letra: "D"},
    {q: "Con la E: Comunidad de los seres vivos cuyos procesos vitales se relacionan entre sí y se desarrollan en función de los factores físicos de un mismo ambiente.", a: "ecosistema", letra: "E"},
    {q: "Con la F: Resto o molde natural de un organismo de épocas geológicas pasadas, conservado en las rocas sedimentarias.", a: "fósil", letra: "F"},
    {q: "Con la G: Planta cuyas semillas están al descubierto, no encerradas en el interior de un fruto, como los pinos.", a: "gimnosperma", letra: "G"},
    {q: "Con la H: Medio ambiente físico o lugar adecuado para que vivan y se reproduzcan determinadas especies animales o vegetales.", a: "hábitat", letra: "H"},
    {q: "Con la I: Animal que carece de columna vertebral o esqueleto interno articulado.", a: "invertebrado", letra: "I"},
    {q: "Con la J: Pequeño pájaro cantor muy apreciado por su plumaje de colores y su canto melodioso.", a: "jilguero", letra: "J"},
    {q: "Con la L: Organismo resultante de la simbiosis entre un hongo y un alga, que suele crecer en rocas y cortezas de árboles.", a: "liquen", letra: "L"},
    {q: "Con la M: Clase de vertebrados de temperatura constante que, en su mayoría, se desarrollan dentro del claustro materno y alimentan a sus crías con leche.", a: "mamífero", letra: "M"},
    {q: "Con la N: Líquido azucarado que producen ciertas glándulas de las flores y que atrae a los insectos polinizadores.", a: "néctar", letra: "N"},
    {q: "Contiene la Ñ: Animal artrópodo con ocho patas que segrega un hilo sedoso con el que teje su tela.", a: "araña", letra: "Ñ"},
    {q: "Con la O: Animal que se alimenta de toda clase de sustancias orgánicas, tanto vegetales como animales.", a: "omnívoro", letra: "O"},
    {q: "Con la P: Conjunto de organismos microscópicos, tanto animales como vegetales, que flotan en aguas dulces y saladas.", a: "plancton", letra: "P"},
    {q: "Con la Q: Hidrato de carbono que forma el caparazón de los artrópodos y la pared celular de los hongos.", a: "quitina", letra: "Q"},
    {q: "Con la R: Clase de vertebrados de sangre fría que están recubiertos de escamas y, en su mayoría, se reproducen por huevos.", a: "reptil", letra: "R"},
    {q: "Con la S: Asociación íntima de organismos de especies diferentes para beneficiarse mutuamente en su desarrollo vital.", a: "simbiosis", letra: "S"},
    {q: "Con la T: Terreno abierto y llano, de clima subglacial y subsuelo helado, con vegetación de musgos y líquenes.", a: "tundra", letra: "T"},
    {q: "Con la U: Animal mamífero que tiene las patas terminadas en pezuñas, como el caballo o el ciervo.", a: "ungulado", letra: "U"},
    {q: "Con la V: Animal que tiene esqueleto con columna vertebral y cráneo.", a: "vertebrado", letra: "V"},
    {q: "Con la X: Tejido vegetal leñoso de las plantas que transporta el agua y las sales minerales desde las raíces.", a: "xilema", letra: "X"},
    {q: "Con la Y: Hembra del caballo.", a: "yegua", letra: "Y"},
    {q: "Con la Z: Rama de la biología que se encarga del estudio de los animales.", a: "zoología", letra: "Z"},

  ]
});