// mazos/mazo_lit.js
if (typeof MAZOS === 'undefined') { var MAZOS = []; }

MAZOS.push({
  id: "literatura", 
  name: "Literatura y Premios Nobel", 
  icon: "📚", 
  questions: [
    // ROSCO 1 - PREMIOS NOBEL Y CLÁSICOS
    {q: "Con la C: Apellido del Nobel francés autor de 'La peste' y 'El extranjero'.", a: "Camus", letra: "C"},
    {q: "Con la C: Nobel español autor de 'La colmena' y 'La familia de Pascual Duarte'.", a: "Cela", letra: "C"},
    {q: "Con la Q: Obra cumbre de Miguel de Cervantes, hito de la novela moderna.", a: "Quijote", letra: "Q"}, // C -> Cervantes (no). C -> "Cantares"
    {q: "Con la C: Obra de Rosalía de Castro que inició el Rexurdimento (___ gallegos).", a: "Cantares", letra: "C"},
    {q: "Con la C: Divina obra de Dante Alighieri sobre el infierno y el paraíso.", a: "Comedia", letra: "C"},
    {q: "Con la E: Nobel de Literatura español, gran dramaturgo de 'El gran Galeoto'.", a: "Echegaray", letra: "E"},
    {q: "Con la F: Nobel estadounidense autor de 'El ruido y la furia'.", a: "Faulkner", letra: "F"},
    {q: "Con la M: Nobel colombiano, máximo exponente del realismo mágico (García ___).", a: "Márquez", letra: "M"},
    {q: "Con la H: Nobel alemán autor de 'Siddhartha' y 'El lobo estepario'.", a: "Hesse", letra: "H"},
    {q: "Con la I: Apellido del dramaturgo noruego autor de 'Casa de muñecas'.", a: "Ibsen", letra: "I"},
    {q: "Con la J: Único Nobel de Literatura español nacido en Moguer, autor de 'Platero y yo'.", a: "Jiménez", letra: "J"},
    {q: "Con la K: Apellido del autor checo de 'La metamorfosis'.", a: "Kafka", letra: "K"},
    {q: "Con la V: Nobel peruano autor de 'La ciudad y los perros'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la M: Nobel chilena, primera mujer latinoamericana en ganarlo (Gabriela ___).", a: "Mistral", letra: "M"},
    {q: "Con la N: Nobel chileno autor de 'Veinte poemas de amor y una canción desesperada'.", a: "Neruda", letra: "N"},
    {q: "Con la A: Apellido del autor de 'La Regenta', obra cumbre del naturalismo.", a: "Alas", letra: "A"}, // Ñ -> "Clarín"
    {q: "Contiene la Ñ: Seudónimo de Leopoldo Alas, autor de 'La Regenta'.", a: "Clarín", letra: "Ñ"},
    {q: "Con la P: Nobel mexicano autor de 'El laberinto de la soledad'.", a: "Paz", letra: "P"}, // O -> Octavio
    {q: "Con la O: Nombre de pila del Nobel mexicano de apellido Paz.", a: "Octavio", letra: "O"},
    {q: "Con la P: Nobel francés autor de 'En busca del tiempo perdido'.", a: "Proust", letra: "P"},
    {q: "Con la S: Apellido del Nobel polaco autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "S"},
    {q: "Con la R: Nobel francés autor de 'El pequeño príncipe' (Saint-Exupéry).", a: "R", letra: "R"}, // R -> "Rolland"
    {q: "Con la R: Nobel francés de 1915 y gran pacifista (Romain ___).", a: "Rolland", letra: "R"},
    {q: "Con la S: Nobel portugués autor de 'Ensayo sobre la ceguera'.", a: "Saramago", letra: "S"},
    {q: "Con la T: Nobel ruso autor de 'Guerra y Paz' y 'Ana Karenina'.", a: "Tolstoi", letra: "T"},
    {q: "Con la U: Nobel noruega autora de 'Cristina hija de Lavrans' (Sigrid ___).", a: "Undset", letra: "U"},
    {q: "Con la V: Gran poeta latino autor de 'La Eneida'.", a: "Virgilio", letra: "V"},
    {q: "Contiene la X: Gran autor chino Nobel de 2000, autor de 'La montaña del alma'.", a: "Gao Xingjian", letra: "X"},
    {q: "Contiene la Y: Nobel irlandés autor de 'La torre' (William Butler ___).", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Autor francés del naturalismo, autor de 'Germinal' y 'Nana'.", a: "Zola", letra: "Z"},

    // ROSCO 2 - TERMINOLOGÍA FILOLÓGICA (PARA NOEMÍ)
    {q: "Con la A: Figura retórica que consiste en la repetición de sonidos iniciales.", a: "aliteración", letra: "A"},
    {q: "Con la B: Composición poética de ocho versos octosílabos con rima asonante.", a: "balada", letra: "B"},
    {q: "Con la C: Estrofa de cuatro versos de arte mayor con rima ABBA.", a: "cuarteto", letra: "C"},
    {q: "Con la E: Verso de once sílabas, el más usado en la lírica culta española.", a: "endecasílabo", letra: "E"}, // D -> "Endecasílabo"
    {q: "Con la E: Verso que consta de once sílabas métricas.", a: "endecasílabo", letra: "E"},
    {q: "Con la E: Composición poética de carácter melancólico que llora una muerte.", a: "elegía", letra: "E"},
    {q: "Con la F: Nombre del conjunto de obras literarias de un autor o país.", a: "fondo", letra: "F"}, // F -> "Filología"
    {q: "Con la F: Ciencia que estudia los textos escritos y su estructura.", a: "filología", letra: "F"},
    {q: "Con la E: Género literario que incluye la epopeya y la novela.", a: "épica", letra: "E"}, // G -> "Género"
    {q: "Con la G: Categoría en la que se clasifican las obras literarias.", a: "género", letra: "G"},
    {q: "Con la H: Figura que consiste en exagerar la realidad de forma desmesurada.", a: "hipérbole", letra: "H"},
    {q: "Con la I: Figura que consiste en dar a entender lo contrario de lo que se dice.", a: "ironía", letra: "I"},
    {q: "Con la J: Composición lírica popular mozárabe de finales de la estrofa.", a: "jarcha", letra: "J"},
    {q: "Con la K: Apellido del autor alemán del drama 'La marquesa de O' (Heinrich von ___).", a: "Kleist", letra: "K"},
    {q: "Con la L: Género literario al que pertenece la poesía.", a: "lírica", letra: "L"},
    {q: "Con la M: Identificación de un objeto con otro por semejanza.", a: "metáfora", letra: "M"},
    {q: "Con la N: Relato literario de ficción, extenso y en prosa.", a: "novela", letra: "N"},
    {q: "Contiene la Ñ: Palabra que designa a la persona que escribe poemas.", a: "compañero", letra: "Ñ"}, // Ñ -> "Señor" (no). Ñ -> "Escritor" (no). Ñ -> "Diseño" (no). Ñ -> "Español"
    {q: "Contiene la Ñ: Lengua romance en la que escribió Cervantes.", a: "español", letra: "Ñ"},
    {q: "Con la O: Composición poética lírica de tono elevado y variado.", a: "oda", letra: "O"},
    {q: "Con la S: Licencia métrica que une la vocal final de una palabra con la inicial de la siguiente.", a: "sinalefa", letra: "S"}, // P -> "Pleonasmo"
    {q: "Con la P: Empleo de palabras innecesarias para intensificar el sentido.", a: "pleonasmo", letra: "P"},
    {q: "Con la C: Estrofa de cuatro versos de arte menor con rima consonante.", a: "cuarteta", letra: "C"},
    {q: "Con la R: Repetición de sonidos al final de dos o más versos.", a: "rima", letra: "R"},
    {q: "Con la S: Composición poética de 14 versos: dos cuartetos y dos tercetos.", a: "soneto", letra: "S"},
    {q: "Con la T: Estrofa de tres versos de arte mayor que suelen rimar ABA.", a: "terceto", letra: "T"},
    {q: "Con la U: El último verso de una estrofa o poema.", a: "último", letra: "U"},
    {q: "Con la V: Cada una de las líneas que componen un poema.", a: "verso", letra: "V"},
    {q: "Con la A: Palabra que tiene el acento en la última sílaba.", a: "aguda", letra: "A"}, // X -> "Oxítona"
    {q: "Contiene la X: Palabra que lleva el acento en la última sílaba.", a: "oxítona", letra: "X"},
    {q: "Contiene la Y: Narración breve de hechos imaginarios.", a: "leyenda", letra: "Y"},
    {q: "Con la Z: Género dramático español que mezcla canto y texto hablado.", a: "zarzuela", letra: "Z"},

    // ROSCO 3 - NOBEL DE LITERATURA MÍTICOS
    {q: "Con la A: Nobel español de 1977, autor de 'La destrucción o el amor'.", a: "Aleixandre", letra: "A"},
    {q: "Con la B: Nobel irlandés autor de 'Esperando a Godot'.", a: "Beckett", letra: "B"},
    {q: "Con la C: Nobel británico autor de 'La isla del tesoro'.", a: "C", letra: "C"}, // No Nobel. C -> Churchill (Nobel Lit 1953)
    {q: "Con la C: Político y Nobel de Literatura de 1953 por sus memorias de guerra.", a: "Churchill", letra: "C"},
    {q: "Con la D: Nobel estadounidense que sorprendió al ganar como músico y poeta.", a: "Dylan", letra: "D"},
    {q: "Con la E: Nobel estadounidense autor de 'La tierra baldía' (T.S. ___).", a: "Eliot", letra: "E"},
    {q: "Con la F: Nobel italiano autor de 'Muerte accidental de un anarquista'.", a: "Fo", letra: "F"},
    {q: "Con la G: Nobel sudafricana autora de 'La historia de mi hijo'.", a: "Gordimer", letra: "G"},
    {q: "Con la H: Nobel estadounidense autor de 'El viejo y el mar'.", a: "Hemingway", letra: "H"},
    {q: "Con la I: Nobel británico de origen japonés autor de 'Lo que queda del día'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Nobel austriaca autora de 'La pianista' (Elfriede ___).", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel británico autor de 'El libro de la selva'.", a: "Kipling", letra: "K"},
    {q: "Con la L: Nobel sueca, primera mujer en ganar el premio (Selma ___).", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel alemán autor de 'La montaña mágica'.", a: "Mann", letra: "M"},
    {q: "Con la T: Nobel indio autor de 'Gitanjali'.", a: "Tagore", letra: "T"}, // N -> "Naipaul"
    {q: "Con la N: Nobel británico nacido en Trinidad, autor de 'Un recodo en el río'.", a: "Naipaul", letra: "N"},
    {q: "Contiene la Ñ: Nobel español de 1922, autor de 'Los intereses creados'.", a: "Benavente", letra: "Ñ"},
    {q: "Con la N: Nobel estadounidense autor de 'Largo viaje hacia la noche' (Eugene ___).", a: "Neill", letra: "N"},
    {q: "Con la P: Nobel italiano autor de 'Seis personajes en busca de autor'.", a: "Pirandello", letra: "P"},
    {q: "Con la G: Nobel alemán autor de 'El tambor de hojalata' (Günter ___).", a: "Grass", letra: "G"}, // Q -> "Quasimodo"
    {q: "Con la Q: Nobel italiano de 1959, gran poeta del hermetismo.", a: "Quasimodo", letra: "Q"},
    {q: "Con la B: Nobel estadounidense autor de 'La buena tierra' (Pearl S. ___).", a: "Buck", letra: "B"}, // R -> "Russell" (Bertrand)
    {q: "Con la R: Filósofo y Nobel de Literatura británico autor de 'Historia de la filosofía'.", a: "Russell", letra: "R"},
    {q: "Con la S: Nobel polaco autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "S"},
    {q: "Con la C: Nobel sudafricano autor de 'Desgracia' (J.M. ___).", a: "Coetzee", letra: "C"}, // T -> "Transtromer"
    {q: "Con la T: Nobel sueco de 2011, gran poeta de 'El cielo a medio hacer'.", a: "Transtromer", letra: "T"},
    {q: "Con la E: Nobel francesa de 2022, autora de 'Los años'.", a: "Ernaux", letra: "E"}, // U -> "Undset"
    {q: "Con la U: Nobel noruega autora de 'Cristina hija de Lavrans'.", a: "Undset", letra: "U"},
    {q: "Con la L: Autor de Los miserables, Víctor Hugo. (Pista: no confundir con el Nobel peruano).", a: "Llosa", letra: "L"},
    {q: "Con la V: Nobel peruano autor de 'La tía Julia y el escribidor'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la M: Nobel francés autor de 'Thérèse Desqueyroux' (François ___).", a: "Mauriac", letra: "M"},
    {q: "Contiene la Y: Nobel irlandés de 1923, poeta autor de La torre (William Butler ___)", a: "Yeats", letra: "Y"},
    {q: "Con la H: Nobel de 2019 nacido en Austria, autor de 'Ensayo sobre el cansancio'.", a: "Handke", letra: "H"}, // Z -> "Zymborska" (Wislawa)
    {q: "Con la S: Nobel polaca autora de 'Fin y principio'.", a: "Szymborska", letra: "S"},

    // ROSCO 4 - LITERATURA UNIVERSAL Y TÉCNICA
    {q: "Con la A: Protagonista de 'Alicia en el país de las maravillas'.", a: "Alicia", letra: "A"},
    {q: "Con la B: Movimiento cultural del XVII caracterizado por el exceso y el pesimismo.", a: "Barroco", letra: "B"},
    {q: "Con la C: Estilo de novela que narra los crímenes de un detective.", a: "Criminal", letra: "C"},
    {q: "Con la D: Apellido del autor de 'Oliver Twist' y 'Cuento de Navidad'.", a: "Dickens", letra: "D"},
    {q: "Con la E: Composición poética extensa que narra hazañas heroicas.", a: "Epopeya", letra: "E"},
    {q: "Con la F: Nombre del doctor que creó un monstruo con partes de cadáveres.", a: "Frankenstein", letra: "F"},
    {q: "Con la V: Apellido del poeta autor de 'Églogas' (Garcilaso de la ___).", a: "Vega", letra: "V"},
    {q: "Con la H: Autor de la 'Odisea' y la 'Ilíada'.", a: "Homero", letra: "H"},
    {q: "Con la F: Autor de 'Los pilares de la Tierra' (Ken ___).", a: "Follett", letra: "F"}, // I -> "Ishiguro"
    {q: "Con la I: Autor de 'Lo que queda del día' y Nobel de 2017.", a: "Ishiguro", letra: "I"},
    {q: "Con la R: Apellido de la autora de Harry Potter.", a: "Rowling", letra: "R"}, // J -> "Joyce"
    {q: "Con la J: Autor irlandés de 'Ulises', hito de la vanguardia.", a: "Joyce", letra: "J"},
    {q: "Con la K: Autor checo de 'El proceso'.", a: "Kafka", letra: "K"},
    {q: "Con la A: Apellido del autor de 'El Lazarillo de Tormes' (Anónimo).", a: "Anónimo", letra: "A"}, // L -> "Lope de Vega"
    {q: "Con la L: El 'Fénix de los Ingenios', gran dramaturgo del Siglo de Oro.", a: "Lope de Vega", letra: "L"},
    {q: "Con la M: Obra clásica de Herman Melville sobre una ballena blanca.", a: "Moby Dick", letra: "M"},
    {q: "Con la N: Género literario al que pertenece la obra 'La Regenta'.", a: "Novela", letra: "N"},
    {q: "Contiene la Ñ: Apellido de la autora de 'Los pazos de Ulloa'.", a: "Pardo Bazán", letra: "Ñ"},
    {q: "Con la O: Nombre del autor de '1984' y 'Rebelión en la granja' (George ___).", a: "Orwell", letra: "O"},
    {q: "Con la P: Autor de 'El cuervo' y maestro del terror.", a: "Poe", letra: "P"},
    {q: "Con la Q: Apellido del autor de 'El buscona' y gran rival de Góngora.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Movimiento literario que busca la libertad y el sentimiento.", a: "Romanticismo", letra: "R"},
    {q: "Con la S: Apellido del autor de 'Romeo y Julieta'.", a: "Shakespeare", letra: "S"},
    {q: "Con la E: Tragedia de Sófocles sobre el rey de Tebas.", a: "Edipo", letra: "E"}, // T -> "Tebas"
    {q: "Con la T: Ciudad griega donde reina el protagonista de la tragedia de Sófocles.", a: "Tebas", letra: "T"},
    {q: "Con la U: Movimiento de vanguardia que buscaba la ruptura total con el pasado.", a: "Ultraísmo", letra: "U"},
    {q: "Con la V: Autor de 'Cinco semanas en globo' y 'Viaje al centro de la Tierra'.", a: "Verne", letra: "V"},
    {q: "Con la M: Autor de 'La montaña mágica' (Thomas ___).", a: "Mann", letra: "M"},
    {q: "Contiene la Y: Apellido del autor de 'Un mundo feliz' (Aldous ___).", a: "Huxley", letra: "Y"},
    {q: "Con la Z: Personaje que marca su nombre con una espada.", a: "Zorro", letra: "Z"},
// ROSCO 5 - PREMIOS NOBEL (ÚLTIMA DÉCADA Y CLÁSICOS)
    {q: "Con la A: Apellido de la Nobel bielorrusa autora de 'Voces de Chernóbil'.", a: "Alexiévich", letra: "A"},
    {q: "Con la B: Nobel de 1925, autor irlandés de 'Pigmalión'.", a: "Bernhard Shaw", letra: "B"},
    {q: "Con la C: Nobel sudafricano autor de 'Esperando a los bárbaros'.", a: "Coetzee", letra: "C"},
    {q: "Con la D: Nobel italiano, dramaturgo de 'Muerte accidental de un anarquista'.", a: "Dario Fo", letra: "D"},
    {q: "Con la E: Nobel francesa de 2022, autora de 'El acontecimiento'.", a: "Ernaux", letra: "E"},
    {q: "Con la F: Nobel noruego de 2023, autor de 'Mañana y tarde'.", a: "Fosse", letra: "F"},
    {q: "Con la G: Apellido de la Nobel estadounidense de 2020, autora de 'Averno'.", a: "Glück", letra: "G"},
    {q: "Con la H: Nobel austriaco de 2019, autor de 'La mujer zurda'.", a: "Handke", letra: "H"},
    {q: "Con la I: Nobel británico de origen japonés, autor de 'Klara y el Sol'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Apellido de la Nobel austriaca de 2004, autora de 'La pianista'.", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel húngaro sobreviviente del Holocausto, autor de 'Sin destino'.", a: "Kertész", letra: "K"},
    {q: "Con la L: Nobel sueca de 1909, autora de 'La saga de Gösta Berling'.", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel chino de 2012, autor de 'Sorgo rojo'.", a: "Mo Yan", letra: "M"},
    {q: "Con la G: Nobel tanzano de 2021, autor de 'Paraíso'.", a: "Gurnah", letra: "G"},
    {q: "Con la C: Apellido del Nobel español autor de 'La colmena'.", a: "Cela", letra: "C"},
    {q: "Con la O: Nombre de la Nobel polaca de 2018, autora de 'Los errantes'.", a: "Olga", letra: "O"},
    {q: "Con la P: Nobel austriaco de 2019, de apellido Handke (Nombre de pila).", a: "Peter", letra: "P"},
    {q: "Con la Q: Apellido del Nobel italiano de 1959, poeta del hermetismo.", a: "Quasimodo", letra: "Q"},
    {q: "Con la R: Nobel francés de 1915, autor de 'Juan Cristóbal'.", a: "Rolland", letra: "R"},
    {q: "Con la S: Nobel polaca de 1996, famosa por su poesía irónica.", a: "Szymborska", letra: "S"},
    {q: "Con la T: Nobel sueco de 2011, psicólogo y poeta.", a: "Transtromer", letra: "T"},
    {q: "Con la U: Nobel noruega de 1928, famosa por sus novelas medievales.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel peruano autor de 'Conversación en La Catedral'.", a: "Vargas Llosa", letra: "V"},
    {q: "Contiene la X: Nobel chino de 2000, autor de 'La montaña del alma'.", a: "Xingjian", letra: "X"},
    {q: "Contiene la Y: Nobel irlandés de 1923, autor de 'La torre'.", a: "Yeats", letra: "Y"},
    {q: "Con la Z: Autor francés del naturalismo, padre de la saga de los Rougon-Macquart.", a: "Zola", letra: "Z"},

    // ROSCO 6 - FILOLOGÍA Y MÉTRICA (NIVEL BOTE)
    {q: "Con la L: Nombre de la estrofa de cinco versos con rima consonante (7-11-7-7-11).", a: "lira", letra: "L"},
    {q: "Con la R: Poema narrativo de versos octosílabos con rima asonante en los pares.", a: "romance", letra: "R"},
    {q: "Con la C: Anotación al final de un libro que indica fecha y lugar de impresión.", a: "colofón", letra: "C"},
    {q: "Con la A: Tipo de rima donde solo coinciden las vocales a partir de la tónica.", a: "asonante", letra: "A"},
    {q: "Con la A: Verso de catorce sílabas, muy usado por Gonzalo de Berceo.", a: "alejandrino", letra: "A"},
    {q: "Con la F: Ciencia que estudia las lenguas y los textos escritos.", a: "filología", letra: "F"},
    {q: "Con la D: Estrofa de diez versos octosílabos, también llamada espinela.", a: "décima", letra: "D"},
    {q: "Con la H: Figura que altera el orden lógico de las palabras en una frase.", a: "hipérbaton", letra: "H"},
    {q: "Con la I: Primeras palabras con las que comienza un texto antiguo.", a: "incipit", letra: "I"},
    {q: "Con la J: Estrofa lírica breve que cerraba las moaxajas árabes.", a: "jarcha", letra: "J"},
    {q: "Con la K: Apellido del autor de 'La metamorfosis', hito de la literatura existencial.", a: "Kafka", letra: "K"},
    {q: "Con la T: Etiqueta pegada al lomo del libro con el título y autor.", a: "tejolet", letra: "T"},
    {q: "Con la M: Arte de medir la estructura de los versos y sus rimas.", a: "métrica", letra: "M"},
    {q: "Con la N: Género literario en prosa que narra hechos ficticios extensos.", a: "novela", letra: "N"},
    {q: "Contiene la Ñ: Palabra que designa el nombre de pila de un autor.", a: "antropónimo", letra: "Ñ"},
    {q: "Con la O: Estrofa de ocho versos endecasílabos con rima ABABABCC.", a: "octava", letra: "O"},
    {q: "Con la A: Figura que omite conjunciones para dar rapidez al verso.", a: "asíndeton", letra: "A"},
    {q: "Con la C: Estrofa de cuatro versos de arte mayor con rima ABBA.", a: "cuarteto", letra: "C"},
    {q: "Con la A: Repetición de una palabra al inicio de varios versos.", a: "anáfora", letra: "A"},
    {q: "Con la S: Licencia métrica que une dos vocales fuertes en una sola sílaba.", a: "sinéresis", letra: "S"},
    {q: "Con la T: Estrofa de tres versos de arte mayor, propia de la Divina Comedia.", a: "terceto", letra: "T"},
    {q: "Con la U: Movimiento de vanguardia español liderado por Cansinos Assens.", a: "ultraísmo", letra: "U"},
    {q: "Con la V: Cada una de las líneas que componen un poema.", a: "verso", letra: "V"},
    {q: "Con la E: Figura que consiste en omitir un elemento que se sobreentiende.", a: "elipsis", letra: "E"},
    {q: "Con la A: Figura que repite una palabra al final de un verso y al inicio del siguiente.", a: "anadiplosis", letra: "A"},
    {q: "Con la Z: Figura que utiliza un solo verbo para varios sujetos complejos.", a: "zeugma", letra: "Z"},

    // ROSCO 7 - LITERATURA ESPAÑOLA (ORO PURO)
    {q: "Con la C: Poeta sevillano de la Generación del 27, autor de 'La realidad y el deseo'.", a: "Cernuda", letra: "C"},
    {q: "Con la B: Autor de las 'Rimas y Leyendas', máximo exponente del romanticismo tardío.", a: "Bécquer", letra: "B"},
    {q: "Con la C: Apellido del autor de 'La vida es sueño', gran dramaturgo barroco.", a: "Calderón", letra: "C"},
    {q: "Con la A: Poeta del 27 autor de 'Sobre los ángeles'.", a: "Alberti", letra: "A"},
    {q: "Con la L: Obra medieval de don Juan Manuel (El conde ___).", a: "Lucanor", letra: "L"},
    {q: "Con la L: Dramaturgo del Siglo de Oro, autor de 'Fuenteovejuna'.", a: "Lope de Vega", letra: "L"},
    {q: "Con la G: Poeta barroco máximo representante del culteranismo.", a: "Góngora", letra: "G"},
    {q: "Con la M: Autor del Siglo de Oro de 'La Diana', novela pastoril.", a: "Montemayor", letra: "M"},
    {q: "Con la U: Apellido del autor de 'San Manuel Bueno, mártir'.", a: "Unamuno", letra: "U"},
    {q: "Con la S: Poeta de la Generación del 27, autor de 'La voz a ti debida'.", a: "Salinas", letra: "S"},
    {q: "Con la K: Apellido del autor de 'La metamorfosis' (ya salió, cambiamos). K -> 'Krausismo'.", a: "Krause", letra: "K"},
    {q: "Con la L: Obra anónima de 1554 que inició la novela picaresca.", a: "Lazarillo", letra: "L"},
    {q: "Con la A: Nombre del autor de 'Campos de Castilla'.", a: "Antonio", letra: "A"},
    {q: "Con la N: Género de la obra 'Niebla' de Unamuno, según él mismo.", a: "nivola", letra: "N"},
    {q: "Contiene la Ñ: Apellido de la autora de 'Insolación' y 'Los pazos de Ulloa'.", a: "Pardo Bazán", letra: "Ñ"},
    {q: "Con la J: Nombre del Nobel de 1956, nacido en Moguer.", a: "Juan Ramón", letra: "J"},
    {q: "Con la G: Poeta del 27, autor de 'Cántico'.", a: "Guillén", letra: "G"},
    {q: "Con la Q: Gran satírico del Barroco, autor de 'El Buscón'.", a: "Quevedo", letra: "Q"},
    {q: "Con la O: Protagonista de 'La Regenta' de Clarín (Ana ___).", a: "Ozores", letra: "O"},
    {q: "Con la L: El 'Fénix de los Ingenios', autor de 'El perro del hortelano'.", a: "Lope", letra: "L"},
    {q: "Con la T: Seudónimo de Gabriel Téllez, autor de 'El burlador de Sevilla'.", a: "Tirso de Molina", letra: "T"},
    {q: "Con la U: Autor vasco de 'La tía Tula' y filósofo del sentimiento trágico.", a: "Unamuno", letra: "U"},
    {q: "Con la H: Apellido del autor de 'El Rayo que no cesa', el poeta cabrero.", a: "Hernández", letra: "H"},
    {q: "Con la M: Movimiento literario hispanoamericano de finales del XIX que buscaba la belleza y el exotismo.", a: "modernismo", letra: "M"},
    {q: "Con la D: Apellido del autor de 'Cinco horas con Mario'.", a: "Delibes", letra: "D"},
    {q: "Con la Z: Poeta del romanticismo español, autor de 'Don Juan Tenorio'.", a: "Zorrilla", letra: "Z"},

    // ROSCO 8 - GRANDES OBRAS UNIVERSALES (NIVEL BOTE)
    {q: "Con la P: Poeta ruso del Siglo de Oro, autor de 'Eugenio Oneguin'.", a: "Pushkin", letra: "P"},
    {q: "Con la B: Autor francés de 'La comedia humana'.", a: "Balzac", letra: "B"},
    {q: "Con la K: Autor checo de 'La insoportable levedad del ser'.", a: "Kundera", letra: "K"},
    {q: "Con la D: Autor ruso de 'Los hermanos Karamázov'.", a: "Dostoievski", letra: "D"},
    {q: "Con la E: Tragedia de Sófocles sobre el destino ineludible del hijo que mata al padre.", a: "Edipo", letra: "E"},
    {q: "Con la F: Autor francés de 'Madame Bovary'.", a: "Flaubert", letra: "F"},
    {q: "Con la F: Obra de Goethe sobre un hombre que vende su alma al diablo.", a: "Fausto", letra: "F"},
    {q: "Con la S: Dramaturgo inglés autor de 'Macbeth' y 'Othello'.", a: "Shakespeare", letra: "S"},
    {q: "Con la I: Autor noruego de 'Un enemigo del pueblo'.", a: "Ibsen", letra: "I"},
    {q: "Con la J: Autor irlandés de la colección de relatos 'Dublineses'.", a: "Joyce", letra: "J"},
    {q: "Con la R: Autor indio y Nobel de 1913, de apellido Tagore (Nombre de pila).", a: "Rabindranath", letra: "R"},
    {q: "Con la V: Autor de 'Los miserables' y 'Nuestra Señora de París'.", a: "Víctor Hugo", letra: "V"},
    {q: "Con la G: Poema épico de la cultura sumeria, el más antiguo del mundo.", a: "Gilgamesh", letra: "G"},
    {q: "Con la N: Apellido del autor de 'Lolita'.", a: "Nabokov", letra: "N"},
    {q: "Con la O: Autor de 'El retrato de Dorian Gray'.", a: "Oscar Wilde", letra: "O"},
    {q: "Con la O: Nombre del autor de 'Metamorfosis' (poeta romano, no Kafka).", a: "Ovidio", letra: "O"},
    {q: "Con la B: Autor de 'Las flores del mal'.", a: "Baudelaire", letra: "B"},
    {q: "Con la D: Apellido del autor de 'Los tres mosqueteros'.", a: "Dumas", letra: "D"},
    {q: "Con la S: Autor de 'El guardián entre el centeno'.", a: "Salinger", letra: "S"},
    {q: "Con la S: Autor de 'Edipo Rey' y 'Antígona'.", a: "Sófocles", letra: "S"},
    {q: "Con la T: Autor ruso de 'La muerte de Iván Ilich'.", a: "Tolstoi", letra: "T"},
    {q: "Con la H: Autor noruego Nobel de 1920 (Knut ___).", a: "Hamsun", letra: "H"},
    {q: "Con la V: Autor de 'Cándido' y gran filósofo ilustrado.", a: "Voltaire", letra: "V"},
    {q: "Contiene la X: Autor británico de 'Un mundo feliz'.", a: "Huxley", letra: "X"},
    {q: "Con la S: Autor de 'Gulliver' (Jonathan ___).", a: "Swift", letra: "S"},
    {q: "Con la K: Autor griego de 'Zorba el griego'.", a: "Kazantzakis", letra: "K"},
// ROSCO 9 - RETÓRICA Y MÉTRICA AVANZADA (PARA FILÓLOGOS)
    {q: "Con la A: Omisión de las conjunciones para dar rapidez a la frase.", a: "asíndeton", letra: "A"},
    {q: "Con la B: Composición poética breve que suele servir de estribillo.", a: "bordón", letra: "B"},
    {q: "Con la C: Repetición de una palabra al final de un verso y al principio del siguiente.", a: "concatenación", letra: "C"},
    {q: "Con la D: Unión en una sílaba de dos vocales que pertenecen a sílabas distintas.", a: "diéresis", letra: "D"},
    {q: "Con la E: Figura que consiste en añadir un adjetivo innecesario que subraya una cualidad obvia.", a: "epíteto", letra: "E"},
    {q: "Con la F: Nombre del conjunto de obras literarias o de una lengua.", a: "filología", letra: "F"}, // F -> "Filandón"
    {q: "Con la F: Reunión para contar cuentos o leer textos en voz alta.", a: "filandón", letra: "F"},
    {q: "Con la H: Palabra que suena igual que otra pero tiene distinto significado.", a: "homónima", letra: "H"}, // G -> "Geminación"
    {q: "Con la G: Repetición inmediata de una palabra en un mismo verso.", a: "geminación", letra: "G"},
    {q: "Con la O: Verso que tiene ocho sílabas métricas.", a: "octosílabo", letra: "O"}, // H -> "Hemistiquio"
    {q: "Con la H: Cada una de las dos partes de un verso separadas por una cesura.", a: "hemistiquio", letra: "H"},
    {q: "Con la I: Palabra que comienza y termina con la misma letra.", a: "isograma", letra: "I"}, // I -> "Iteración"
    {q: "Con la I: Repetición de palabras o conceptos para dar énfasis.", a: "iteración", letra: "I"},
    {q: "Con la J: Composición lírica popular que cierra una moaxaja.", a: "jarcha", letra: "J"},
    {q: "Con la K: En la métrica griega, cada una de las partes de un verso largo.", a: "kola", letra: "K"},
    {q: "Con la L: Figura que consiste en negar lo contrario de lo que se quiere afirmar.", a: "lítotes", letra: "L"},
    {q: "Con la M: Figura que designa una cosa con el nombre de otra por cercanía o causa.", a: "metonimia", letra: "M"},
    {q: "Con la N: Palabra inventada por un autor que no existe en el idioma.", a: "neologismo", letra: "N"},
    {q: "Contiene la Ñ: Palabra que imita el sonido de una acción o animal.", a: "onomatopeya", letra: "Ñ"},
    {q: "Con la O: Figura que une dos palabras de significado opuesto que parecen excluirse.", a: "oxímoron", letra: "O"},
    {q: "Con la P: Figura que consiste en repetir una palabra con diferentes morfemas.", a: "políptoton", letra: "P"},
    {q: "Con la Q: Estrofa de cinco versos de arte menor con rima consonante.", a: "quintilla", letra: "Q"},
    {q: "Con la E: Repetición de un verso al final de cada estrofa de un poema.", a: "estribillo", letra: "E"}, // R -> "Redondilla"
    {q: "Con la R: Estrofa de cuatro versos octosílabos con rima ABBA.", a: "redondilla", letra: "R"},
    {q: "Con la S: Figura que consiste en atribuir una sensación a un sentido que no le corresponde.", a: "sinestesia", letra: "S"},
    {q: "Con la T: Estrofa de tres versos que riman en cadena en la Divina Comedia.", a: "terceto", letra: "T"},
    {q: "Con la Z: Figura que consiste en usar un solo verbo para varios sujetos.", a: "zeugma", letra: "Z"}, // U -> "Unívoca"
    {q: "Con la U: Palabra que tiene un solo significado posible.", a: "unívoca", letra: "U"},
    {q: "Con la V: Composición poética de arte menor con estribillo, típica de la lírica popular.", a: "villancico", letra: "V"},
    {q: "Contiene la X: Palabra que lleva el acento en la penúltima sílaba.", a: "paroxítona", letra: "X"},
    {q: "Con la A: Figura que repite la última palabra de un verso al principio del siguiente.", a: "anadiplosis", letra: "A"},
    {q: "Con la Z: Figura que utiliza una sola palabra para modificar a otras dos similares.", a: "zeugma", letra: "Z"},

    // ROSCO 10 - NOBELES OLVIDADOS O DIFÍCILES
    {q: "Con la A: Nobel guatemalteco autor de 'El señor presidente'.", a: "Asturias", letra: "A"},
    {q: "Con la B: Nobel noruego de 1903, autor de 'Sigurd Slembe'.", a: "Bjørnson", letra: "B"},
    {q: "Con la C: Nobel británica de origen rumano, autora de 'La bestia del corazón'.", a: "Canetti", letra: "C"}, // C -> "Herta Müller" (no). C -> "Elias Canetti"
    {q: "Con la C: Nobel búlgaro nacionalizado británico, autor de 'Masa y poder'.", a: "Canetti", letra: "C"},
    {q: "Con la D: Nobel estadounidense autor de 'Derecho de paso' (No Nobel). D -> 'Hilda Doolittle' (no). D -> 'Grazia Deledda'.", a: "Deledda", letra: "D"},
    {q: "Con la D: Segunda mujer en ganar el Nobel de Literatura, de origen italiano.", a: "Deledda", letra: "D"},
    {q: "Con la E: Nobel español de 1904, autor de 'El gran Galeoto'.", a: "Echegaray", letra: "E"},
    {q: "Con la F: Nobel noruego de 2023, autor de 'Septología'.", a: "Fosse", letra: "F"},
    {q: "Con la G: Nobel sudafricana de 1991, autora de 'La hija de Burger'.", a: "Gordimer", letra: "G"},
    {q: "Con la M: Nobel sueco de 1974 (Harry ___).", a: "Martinson", letra: "M"}, // H -> "Heidenstam"
    {q: "Con la H: Nobel sueco de 1916, autor de 'Hans Alienus'.", a: "Heidenstam", letra: "H"},
    {q: "Con la I: Nobel turco de 2006, autor de 'Me llamo Rojo'.", a: "Ishiguro", letra: "I"}, // I -> "Pamuk" (Orhan). I -> "Ishiguro" (Kazuo).
    {q: "Con la I: Nobel británico nacido en Japón, autor de 'Nunca me abandones'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Nobel austriaca de 2004, autora de 'La pianista'.", a: "Jelinek", letra: "J"},
    {q: "Con la K: Nobel japonés de 1968, autor de 'La casa de las bellas durmientes'.", a: "Kawabata", letra: "K"},
    {q: "Con la L: Nobel sueca de 1909, creadora de 'Nils Holgersson'.", a: "Lagerlöf", letra: "L"},
    {q: "Con la M: Nobel belga de 1911, autor de 'La vida de las abejas'.", a: "Maeterlinck", letra: "M"},
    {q: "Con la N: Nobel británico de origen trinitense, autor de 'Una casa para el señor Biswas'.", a: "Naipaul", letra: "N"},
    {q: "Contiene la Ñ: Apellido del Nobel español autor de 'Muerte de un ciclista' (No). Ñ -> 'Benavente'.", a: "Benavente", letra: "Ñ"},
    {q: "Contiene la Ñ: Nobel español de 1922, autor de 'La malquerida'.", a: "Benavente", letra: "Ñ"},
    {q: "Con la N: Nobel estadounidense de 1936, gran dramaturgo (Eugene ___).", a: "Neill", letra: "N"},
    {q: "Con la P: Nobel francés de 1960, autor de 'Anábasis' (Saint-John ___).", a: "Perse", letra: "P"},
    {q: "Con la Q: Nobel italiano de 1959, autor de 'Y de repente es de noche'.", a: "Quasimodo", letra: "Q"},
    {q: "Con la R: Nobel polaco de 1924, autor de 'Los campesinos'.", a: "Reymont", letra: "R"},
    {q: "Con la S: Nobel nigeriano de 1986, autor de 'Aké: los años de la niñez'.", a: "Soyinka", letra: "S"},
    {q: "Con la T: Nobel indio de 1913, autor de 'El cartero del rey'.", a: "Tagore", letra: "T"},
    {q: "Con la U: Nobel noruega de 1928, autora de la trilogía 'Kristin Lavransdatter'.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel de Literatura del año 2010, novelista peruano.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la V: Nobel de Literatura de 2010, autor de 'La fiesta del Chivo'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la M: Nobel francés de 1952, autor de 'El nudo de víboras'.", a: "Mauriac", letra: "M"},
    {q: "Con la S: Nobel polaco de 1905, autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "S"},
    {q: "Con la P: Nobel de 2019 nacido en Austria, de apellido Handke.", a: "Peter", letra: "P"}, // Z -> "Zymborska"
    {q: "Con la S: Nobel polaca de 1996, poeta de 'Paisaje con grano de arena'.", a: "Szymborska", letra: "S"},

    // ROSCO 11 - AUTORES Y OBRAS "HUESO" (ESPAÑOL)
    {q: "Con la A: Poeta del 27 de origen malagueño, autor de 'La voz a ti debida' (No). A -> 'Altolaguirre'.", a: "Altolaguirre", letra: "A"},
    {q: "Con la A: El impresor de la Generación del 27, autor de 'Las islas invitadas'.", a: "Altolaguirre", letra: "A"},
    {q: "Con la C: Obra de Gabriel García Márquez sobre una familia en Macondo.", a: "Cien años de soledad", letra: "C"}, // B -> "Buendía"
    {q: "Con la B: Apellido de la familia protagonista de 'Cien años de soledad'.", a: "Buendía", letra: "B"},
    {q: "Con la C: Autor de 'San Camilo, 1936' y Nobel de Literatura.", a: "Cela", letra: "C"},
    {q: "Con la D: Autor de 'El camino' y 'Señora de rojo sobre fondo gris'.", a: "Delibes", letra: "D"},
    {q: "Con la U: Autor de 'La tía Tula' y gran representante de la Generación del 98.", a: "Unamuno", letra: "U"}, // E -> "Enriquez" (no). E -> "Espinosa"
    {q: "Con la G: Filósofo y autor de 'El espectador', de apellido Ortega y ___.", a: "Gasset", letra: "G"},
    {q: "Con la V: Autor de 'Luces de bohemia', creador del esperpento.", a: "Valle-Inclán", letra: "V"}, // F -> "Fé" (no). F -> "Fernández de Moratín"
    {q: "Con la F: Autor de 'El sí de las niñas', gran dramaturgo neoclásico.", a: "Fernández de Moratín", letra: "F"},
    {q: "Con la G: Poeta de la Generación del 27 autor de 'Ángeles de Compostela'.", a: "Gerardo Diego", letra: "G"},
    {q: "Con la H: Poeta de la Generación del 27, autor de 'Perito en lunas'.", a: "Hernández", letra: "H"},
    {q: "Con la B: Autor de 'La saga/fuga de J.B.', de apellido Torrente ___.", a: "Ballester", letra: "B"},
    {q: "Con la B: Nombre del autor de 'La forja de un rebelde' (Arturo ___).", a: "Barea", letra: "B"}, // J -> "Juan"
    {q: "Con la J: Nombre del autor de 'Señas de identidad', de apellido Goytisolo.", a: "Juan", letra: "J"},
    {q: "Con la K: Apellido del autor de 'El castillo' (No). K -> 'Krause'.", a: "Krause", letra: "K"},
    {q: "Con la K: Filósofo alemán que inspiró a los intelectuales del XIX en España.", a: "Krause", letra: "K"},
    {q: "Con la S: Autor de 'Réquiem por un campesino español'.", a: "Sender", letra: "S"}, // L -> "Laforet"
    {q: "Con la L: Autora de 'Nada', novela ganadora del primer Premio Nadal.", a: "Laforet", letra: "L"},
    {q: "Con la A: Nombre de la autora de 'Olvidado Rey Gudú'.", a: "Ana María", letra: "A"},
    {q: "Con la N: Género de la obra 'Niebla' de Unamuno.", a: "nivola", letra: "N"},
    {q: "Con la M: Apellido de la autora de 'Primera memoria' y 'Paraíso inhabitado'.", a: "Matute", letra: "M"},
    {q: "Con la J: Nombre del Nobel de Literatura de 1956.", a: "Juan Ramón", letra: "J"},
    {q: "Con la S: Autor de 'Tiempo de silencio', de apellido Martín-___.", a: "Santos", letra: "S"},
    {q: "Con la Q: Apellido del autor de 'La vida de Marco Bruto'.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Protagonista de 'La Regenta', apodada así por su cargo.", a: "Regenta", letra: "R"},
    {q: "Con la E: Nombre de pila de la autora de 'Insolación', de apellido Pardo Bazán.", a: "Emilia", letra: "E"}, // S -> "Salas" (no). S -> "Sampedro"
    {q: "Con la S: Autor de 'La sonrisa etrusca' y 'El río que nos lleva'.", a: "Sampedro", letra: "S"},
    {q: "Con la F: Seudónimo de Mariano José de Larra.", a: "Fígaro", letra: "F"}, // T -> "Téllez"
    {q: "Con la T: Apellido real del dramaturgo Tirso de Molina.", a: "Téllez", letra: "T"},
    {q: "Con la U: Autor de 'La tía Tula' y 'Amor y pedagogía'.", a: "Unamuno", letra: "U"},
    {q: "Con la G: Apellido del autor de 'La zapatera prodigiosa'.", a: "García Lorca", letra: "G"}, // V -> "Valle-Inclán"
    {q: "Con la V: Autor de 'Divinas palabras' y 'Sonata de otoño'.", a: "Valle-Inclán", letra: "V"},
    {q: "Con la S: Autor de 'El Jarama', hito del realismo social.", a: "Sánchez Ferlosio", letra: "S"},
    {q: "Con la C: Apellido del autor de 'Historias del Cronopios y Famas' (Julio ___).", a: "Cortázar", letra: "C"},
    {q: "Con la Z: Autor de 'Don Juan Tenorio'.", a: "Zorrilla", letra: "Z"},
// ROSCO 13 - FIGURAS RETÓRICAS Y VICIOS (LAS MÁS DIFÍCILES)
    {q: "Con la A: Error de sintaxis que consiste en abandonar la construcción inicial de una frase.", a: "anacoluto", letra: "A"},
    {q: "Con la C: Palabra o expresión que suena mal por repetición de letras o sílabas.", a: "cacofonía", letra: "C"}, // B -> "Barbarismo"
    {q: "Con la B: Falta de ortografía o uso de una palabra ajena a la lengua propia.", a: "barbarismo", letra: "B"},
    {q: "Con la E: Figura que repite una palabra al final de varios versos o frases.", a: "epífora", letra: "E"}, // C -> "Conversión"
    {q: "Con la C: Repetición de una misma palabra al final de frases sucesivas.", a: "conversión", letra: "C"},
    {q: "Con la A: Omisión de una letra al principio de una palabra (ej. 'psicología' por 'sicología').", a: "aféresis", letra: "A"}, // D -> "Dieresis" (ya salió). D -> "Díptote"
    {q: "Con la D: Sustantivo que solo tiene dos casos en su declinación.", a: "díptote", letra: "D"},
    {q: "Con la E: Expresión que se usa para evitar una palabra tabú o malsonante.", a: "eufemismo", letra: "E"},
    {q: "Con la S: Error gramatical consistente en una construcción incorrecta (ej. 'habían muchos').", a: "solecismo", letra: "S"}, // F -> "Fígaro" (ya salió). F -> "Figura"
    {q: "Con la F: Término genérico para los recursos expresivos de la lengua literaria.", a: "figura", letra: "F"},
    {q: "Con la P: Expresión redundante de una idea (ej. 'subir arriba').", a: "pleonasmo", letra: "P"}, // G -> "Glosema"
    {q: "Con la G: Unidad mínima de significado según la glosemática.", a: "glosema", letra: "G"},
    {q: "Con la H: Encuentro de dos vocales que se pronuncian en sílabas distintas.", a: "hiato", letra: "H"},
    {q: "Con la H: Atribución de una cualidad a un sustantivo que corresponde a otro cercano.", a: "hipálage", letra: "H"},
    {q: "Con la J: Composición poética breve de la lírica mozárabe.", a: "jarcha", letra: "J"},
    {q: "Con la Q: Rama de la lingüística que estudia el significado de los gestos corporales.", a: "quinésica", letra: "Q"},
    {q: "Con la L: Figura que consiste en negar lo contrario de lo que se desea afirmar.", a: "lítotes", letra: "L"},
    {q: "Con la M: Cambio semántico por semejanza entre dos conceptos.", a: "metáfora", letra: "M"},
    {q: "Con la N: Palabra nueva en una lengua o sentido nuevo de una antigua.", a: "neologismo", letra: "N"},
    {q: "Contiene la Ñ: Palabra que imita sonidos de la naturaleza.", a: "onomatopeya", letra: "Ñ"},
    {q: "Con la O: Palabra que tiene el acento en la última sílaba.", a: "oxítona", letra: "O"},
    {q: "Con la P: Figura que repite una palabra con diferentes formas gramaticales.", a: "políptoton", letra: "P"},
    {q: "Con la Q: Figura que consiste en la unión de dos ideas contradictorias (___-asmo).", a: "qui", letra: "Q"}, // Q -> "Quiasmo"
    {q: "Con la Q: Repetición de una estructura cruzada en dos frases.", a: "quiasmo", letra: "Q"},
    {q: "Con la E: Repetición de un mismo verso al final de varias estrofas.", a: "estribillo", letra: "E"}, // R -> "Reduplicación"
    {q: "Con la R: Repetición inmediata de una palabra en el mismo verso.", a: "reduplicación", letra: "R"},
    {q: "Con la A: Figura que omite el nexo entre oraciones (ej. 'Vini, vidi, vici').", a: "asíndeton", letra: "A"}, // S -> "Silepsis"
    {q: "Con la S: Figura que rompe la concordancia gramatical por el sentido.", a: "silepsis", letra: "S"},
    {q: "Con la T: Fragmentación de una palabra para introducir otra en medio.", a: "tmesis", letra: "T"},
    {q: "Con la U: Palabra que se usa con un solo sentido.", a: "unívoca", letra: "U"},
    {q: "Con la V: Defecto de dicción que consiste en pronunciar mal las palabras.", a: "vicio", letra: "V"},
    {q: "Contiene la X: Palabra que tiene el acento en la penúltima sílaba.", a: "paroxítona", letra: "X"},
    {q: "Con la S: Licencia métrica que une la vocal final de una palabra con la vocal inicial de la siguiente.", a: "sinalefa", letra: "S"},
    {q: "Con la Z: Figura que usa un solo verbo para varios complementos.", a: "zeugma", letra: "Z"},

    // ROSCO 14 - PARTES DEL LIBRO Y BIBLIOGRAFÍA
    {q: "Con la G: Lista de palabras con su significado que suele ir al final del libro.", a: "glosario", letra: "G"}, // A -> "Apéndice"
    {q: "Con la A: Texto añadido al final de una obra para completarla.", a: "apéndice", letra: "A"},
    {q: "Con la B: Lista de libros y fuentes consultadas para un trabajo.", a: "bibliografía", letra: "B"},
    {q: "Con la C: Anotación al final del libro con los datos de impresión.", a: "colofón", letra: "C"},
    {q: "Con la E: Breve dedicatoria que encabeza un libro o capítulo.", a: "epígrafe", letra: "E"}, // D -> "Dedicatoria"
    {q: "Con la D: Nota escrita por el autor para ofrecer su obra a alguien.", a: "dedicatoria", letra: "D"},
    {q: "Con la P: Edición que se hace después de que el autor ha fallecido.", a: "póstuma", letra: "P"}, // E -> "Exlibris"
    {q: "Con la E: Marca de propiedad que se pone en el reverso de la tapa del libro.", a: "exlibris", letra: "E"},
    {q: "Con la P: Hoja que precede a la portada y suele llevar solo el título.", a: "portadilla", letra: "P"}, // F -> "Frontispicio"
    {q: "Con la F: Ilustración o grabado situado frente a la portada de un libro.", a: "frontispicio", letra: "F"},
    {q: "Con la G: Lista de términos técnicos o difíciles al final del libro.", a: "glosario", letra: "G"},
    {q: "Con la H: Cada una de las partes en que se divide un libro.", a: "hoja", letra: "H"},
    {q: "Con la I: Libro impreso en los albores de la imprenta, antes de 1501.", a: "incunable", letra: "I"},
    {q: "Con la S: Nombre del papel protector que envuelve la cubierta de un libro.", a: "sobrecubierta", letra: "S"}, // J -> "Jaqueta"
    {q: "Con la J: Sinónimo de sobrecubierta o forro de un libro (Anglicismo).", a: "jacket", letra: "J"},
    {q: "Con la K: Apellido del autor de 'La metamorfosis' (No). K -> 'Koiné'.", a: "Koiné", letra: "K"},
    {q: "Con la K: Lengua común o estándar que resulta de la mezcla de varios dialectos.", a: "koiné", letra: "K"},
    {q: "Con la T: Etiqueta de cuero o papel pegada al lomo con el título.", a: "tejuelo", letra: "T"},
    {q: "Con la M: Espacio en blanco que rodea el texto de una página.", a: "margen", letra: "M"},
    {q: "Con la P: Nota breve que se pone debajo del texto de una página (Nota a ___).", a: "pie", letra: "P"},
    {q: "Con la D: Inscripción con la que el autor dedica su libro como obsequio.", a: "dedicatoria", letra: "D"}, // Ñ -> "Añadido" (no). Ñ -> "Diseño"
    {q: "Contiene la Ñ: Dibujo o adorno que encabeza un capítulo de un libro.", a: "viñeta", letra: "Ñ"},
    {q: "Con la C: Parte del libro opuesta al lomo por donde se abren las hojas.", a: "corte", letra: "C"},
    {q: "Con la P: Texto corto que precede a una obra y sirve de introducción.", a: "prólogo", letra: "P"},
    {q: "Con la C: Cada una de las cuatro partes en que se divide un pliego al doblarse.", a: "cuarto", letra: "C"},
    {q: "Con la V: Parte de atrás de una hoja de papel (Opuesto a 'recto').", a: "verso", letra: "V"}, // R -> "Reverso"
    {q: "Con la R: Cara posterior de una hoja o página de un libro.", a: "reverso", letra: "R"},
    {q: "Con la M: Tira de tela o papel que sirve para marcar la página.", a: "marcapáginas", letra: "M"}, // S -> "Signatura"
    {q: "Con la S: Código de letras y números para localizar un libro en la biblioteca.", a: "signatura", letra: "S"},
    {q: "Con la T: Cubierta de cartón o cuero que protege las hojas de un libro.", a: "tapa", letra: "T"},
    {q: "Con la U: El último pliego que se imprime en un libro.", a: "último", letra: "U"},
    {q: "Con la P: Nombre de la hoja que queda a la izquierda al abrir el libro.", a: "par", letra: "P"}, // V -> "Verso"
    {q: "Con la V: Cara posterior de una hoja, que siempre es página par.", a: "verso", letra: "V"},
    {q: "Con la S: Resumen de una obra que suele aparecer en la contraportada.", a: "sinopsis", letra: "S"},
    {q: "Con la B: Apellido del autor de la 'Gramática de la lengua castellana' de 1847.", a: "Bello", letra: "B"}, // Y -> "Salvá y Mallén" (no). Y -> "Mayans y Siscar"
    {q: "Contiene la Y: Erudito valenciano del XVIII, autor de 'Orígenes de la lengua española'.", a: "Mayans", letra: "Y"},
    {q: "Con la C: Tira de tela decorativa que se pega en los extremos del lomo.", a: "cabezada", letra: "C"},

    // ROSCO 15 - NOBELES DE LITERATURA "CERROJO"
    {q: "Con la S: Nobel griego de 1963, poeta de 'Diario de a bordo'.", a: "Seferis", letra: "S"},
    {q: "Con la P: Nobel soviético de 1958, autor de 'Doctor Zhivago'.", a: "Pasternak", letra: "P"},
    {q: "Con la K: Nobel británico de 1907, autor de 'El libro de la selva'.", a: "Kipling", letra: "K"},
    {q: "Con la M: Nobel italiano de 1975, poeta de 'Huesos de sepia'.", a: "Montale", letra: "M"},
    {q: "Con la K: Nobel húngaro de 2002, autor de 'Sin destino'.", a: "Kertész", letra: "K"},
    {q: "Con la F: Nobel noruego de 2023, autor de 'Aliss junto al fuego'.", a: "Fosse", letra: "F"},
    {q: "Con la G: Nobel alemán de 1999, autor de 'El tambor de hojalata'.", a: "Grass", letra: "G"},
    {q: "Con la H: Nobel suizo de 1946, autor de 'El juego de los abalorios'.", a: "Hesse", letra: "H"},
    {q: "Con la I: Nobel británico de 2017, autor de 'Los restos del día'.", a: "Ishiguro", letra: "I"},
    {q: "Con la L: Nobel islandés de 1955, autor de 'Gente independiente'.", a: "Laxness", letra: "L"},
    {q: "Con la O: Nobel japonés de 1994, autor de 'Una cuestión personal'.", a: "Oe", letra: "O"},
    {q: "Con la L: Nobel francés de 2008, autor de 'El atestado'.", a: "Le Clézio", letra: "L"},
    {q: "Con la M: Nobel chino de 2012, de verdadero nombre Guan Moye.", a: "Mo Yan", letra: "M"},
    {q: "Con la G: Nobel tanzano de 2021, autor de 'En la orilla'.", a: "Gurnah", letra: "G"},
    {q: "Con la C: Nobel español de 1989, autor de 'Mazurca para dos muertos'.", a: "Cela", letra: "C"},
    {q: "Con la N: Nobel estadounidense de 1936, autor de 'A Electra le sienta bien el luto'.", a: "Neill", letra: "N"},
    {q: "Con la P: Nobel turco de 2006, autor de 'Nieve'.", a: "Pamuk", letra: "P"},
    {q: "Con la S: Nobel polaco de 1905, autor de 'Quo Vadis?'.", a: "Sienkiewicz", letra: "S"},
    {q: "Con la P: Nobel estadounidense de 2004 (Philip ___). No Nobel. R -> 'Roth' (No). R -> 'Richter'. No. R -> 'Sully Prudhomme' (Primero).", a: "Prudhomme", letra: "P"},
    {q: "Con la P: Primer Nobel de la historia (1901), poeta francés.", a: "Prudhomme", letra: "P"},
    {q: "Con la S: Nobel polaca de 1996, autora de 'El gran número'.", a: "Szymborska", letra: "S"},
    {q: "Con la T: Nobel sueco de 2011, gran poeta y psicólogo.", a: "Transtromer", letra: "T"},
    {q: "Con la U: Nobel noruega de 1928, autora de 'Olav Audunsson'.", a: "Undset", letra: "U"},
    {q: "Con la V: Nobel de Literatura del año 2010, novelista peruano.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la V: Nobel peruano autor de 'La ciudad y los perros'.", a: "Vargas Llosa", letra: "V"},
    {q: "Con la M: Nobel francés de 1952, autor de 'El desierto del amor'.", a: "Mauriac", letra: "M"},
    {q: "Contiene la Y: Nobel irlandés de 1923, autor de 'El crepúsculo celta'.", a: "Yeats", letra: "Y"},
    {q: "Con la S: Nobel polaca de 1996 (Szymborska). Z -> 'Zymborska' (No). Z -> 'Zola' (No Nobel). Z -> 'Zuckmayer' (No). Z -> 'Stefan Zweig' (No Nobel). Z -> 'Szymborska'.", a: "Szymborska", letra: "S"},

    // ROSCO 16 - EL GRAN FINAL LITERARIO (MISCELÁNEA)
    {q: "Con la B: Escritor de la generación del 98, autor de 'La busca'.", a: "Baroja", letra: "B"}, // A -> "Azorín"
    {q: "Con la A: Seudónimo de José Martínez Ruiz, escritor de la generación del 98.", a: "Azorín", letra: "A"},
    {q: "Con la S: Movimiento estético que exalta la libertad, de origen alemán (___ und Drang).", a: "Sturm", letra: "S"},
    {q: "Con la M: Corriente literaria hispanoamericana de finales del XIX, de la que Darío fue líder.", a: "Modernismo", letra: "M"}, // C -> "Culteranismo"
    {q: "Con la C: Estilo poético del Barroco que busca la belleza mediante el lenguaje culto y difícil.", a: "Culteranismo", letra: "C"},
    {q: "Con la L: Nombre del autor de 'La Regenta', de apellido Alas.", a: "Leopoldo", letra: "L"},
    {q: "Con la E: Composición poética de tema amoroso puesta en boca de pastores.", a: "Égloga", letra: "E"},
    {q: "Con la B: Autor de 'El tragaluz' y 'Historia de una escalera'.", a: "Buero Vallejo", letra: "B"}, // F -> "Fernández de Moratín"
    {q: "Con la F: Autor neoclásico de 'El sí de las niñas'.", a: "Fernández de Moratín", letra: "F"},
    {q: "Con la B: Poeta de la generación del 27, autor de 'Ángel fieramente humano'.", a: "Blas de Otero", letra: "B"},
    {q: "Con la S: Autor de 'El Jarama', máximo exponente del realismo social.", a: "Sánchez Ferlosio", letra: "S"},
    {q: "Con la A: Autor de 'Los pazos de Ulloa' (No). I -> 'Icíar Bollaín' (No). I -> 'Ignacio Aldecoa'.", a: "Aldecoa", letra: "A"},
    {q: "Con la A: Autor de 'El fulgor y la sangre', maestro del cuento español del XX.", a: "Aldecoa", letra: "A"},
    {q: "Con la C: Nombre del autor de 'La familia de Pascual Duarte'.", a: "Camilo José", letra: "C"},
    {q: "Con la K: Autor de 'En la colonia penitenciaria'.", a: "Kafka", letra: "K"},
    {q: "Con la L: Autor de 'La colmena' (No Nobel). L -> 'Lope de Vega'.", a: "Lope de Vega", letra: "L"},
    {q: "Con la L: El fénix de los ingenios, autor de 'Peribáñez y el comendador de Ocaña'.", a: "Lope de Vega", letra: "L"},
    {q: "Con la A: Nombre de pila de la autora de 'Olvidado rey Gudú'.", a: "Ana María", letra: "A"},
    {q: "Con la N: Género de la obra 'Niebla' de Unamuno.", a: "Nivola", letra: "N"},
    {q: "Contiene la Ñ: Apellido de la autora de 'Insolación'.", a: "Pardo Bazán", letra: "Ñ"},
    {q: "Con la F: Nombre del autor de 'La Celestina', de apellido Rojas.", a: "Fernando", letra: "F"},
    {q: "Con la A: Autor de 'Campos de Castilla'.", a: "Antonio Machado", letra: "A"}, // P -> "Pío Baroja"
    {q: "Con la P: Autor de 'El árbol de la ciencia'.", a: "Pío Baroja", letra: "P"},
    {q: "Con la Q: Apellido del autor de 'El Buscón'.", a: "Quevedo", letra: "Q"},
    {q: "Con la A: Protagonista de 'La Regenta'.", a: "Ana Ozores", letra: "A"},
    {q: "Con la S: Autor de 'La sonrisa etrusca'.", a: "Sampedro", letra: "S"},
    {q: "Con la F: Seudónimo de Mariano José de Larra.", a: "Fígaro", letra: "F"},
    {q: "Con la U: Autor de 'San Manuel Bueno, mártir'.", a: "Unamuno", letra: "U"},
    {q: "Con la G: Autor de 'La zapatera prodigiosa'.", a: "García Lorca", letra: "G"},
    {q: "Con la P: Tendencia poética que busca la perfección formal y la depuración del lenguaje.", a: "Poesía pura", letra: "P"},
    {q: "Con la S: Apellido del autor de 'Réquiem por un campesino español'.", a: "Sender", letra: "S"},
    {q: "Con la Z: Autor de 'Don Juan Tenorio'.", a: "Zorrilla", letra: "Z"}
,
    {q: "Con la A: Autor del 'Lazarillo de Tormes', obra anónima del siglo XVI considerada la primera novela picaresca.", a: "anónimo", letra: "A"},
    {q: "Con la B: Dramaturgo español autor de 'Fuente Ovejuna' y 'El caballero de Olmedo'.", a: "Lope de Vega", letra: "L"},
    {q: "Con la C: Mística carmelita española que escribió 'El castillo interior' y 'Las moradas'.", a: "Catalina", letra: "C"},
    {q: "Con la D: Poeta del Siglo de Oro español, rival de Lope, autor de 'Fábula de Polifemo y Galatea'.", a: "Góngora", letra: "G"},
    {q: "Con la E: Escritor español del 98, autor de 'El árbol de la ciencia' y 'Zalacaín el aventurero'.", a: "Baroja", letra: "B"},
    {q: "Con la F: Poeta granadino asesinado en 1936, autor de 'Romancero gitano' y 'La casa de Bernarda Alba'.", a: "Federico García Lorca", letra: "F"},
    {q: "Con la G: Novelista sevillana del siglo XIX, autora de 'Cecilia Valdés'.", a: "Gómez de Avellaneda", letra: "G"},
    {q: "Con la H: Escritora española contemporánea, autora de 'El tiempo entre costuras'.", a: "Dueñas", letra: "D"},
    {q: "Con la I: Autor de 'La tía Tula' y 'Niebla', fundador de la Generación del 98.", a: "Unamuno", letra: "U"},
    {q: "Con la J: Poeta sevillano del Siglo de Oro, autor de 'Epístola moral a Fabio'.", a: "Jáuregui", letra: "J"},
    {q: "Con la L: Poeta del 27, autor de 'Cántico' y 'Clamor', residente en Francia durante el exilio.", a: "Luis Cernuda", letra: "L"},
    {q: "Con la M: Autor de 'La verdad sospechosa', obra que inspiró a Molière en 'El mentiroso'.", a: "Moreto", letra: "M"},
    {q: "Con la N: Poeta romántico español, autor de 'Rimas y Leyendas', de nombre Gustavo Adolfo.", a: "Núñez de Arce", letra: "N"},
    {q: "Con la O: Filósofo español autor de 'La rebelión de las masas' y 'La deshumanización del arte'.", a: "Ortega y Gasset", letra: "O"},
    {q: "Con la P: Novelista realista español del siglo XIX, autor de 'Fortunata y Jacinta'.", a: "Pérez Galdós", letra: "P"},
    {q: "Con la Q: Escritor español del Barroco, autor de 'El Buscón' y 'Sueños'.", a: "Quevedo", letra: "Q"},
    {q: "Con la R: Novelista española contemporánea, autora de 'El médico de Sefarad'.", a: "Rosa Regàs", letra: "R"},
    {q: "Con la S: Autor español del Barroco, conocido por sus aforos y su novela 'El Criticón'.", a: "Baltasar Gracián", letra: "B"},
    {q: "Con la T: Novelista español autor de 'Juegos de la edad tardía' (Luis Landero no, este...).", a: "Torrente Ballester", letra: "T"},
    {q: "Con la U: Poeta del 27 y autor de 'Marinero en tierra', Premio Nacional de Literatura.", a: "Alberti", letra: "A"},
    {q: "Con la V: Escritor valenciano medieval, autor de 'Tirant lo Blanch'.", a: "Martorell", letra: "M"},
    {q: "Con la W: Escritor catalán contemporáneo conocido por 'La sombra del viento' (Carlos ___).", a: "Zafón", letra: "Z"},
    {q: "Con la X: Historiador y humanista español del siglo XVI autor de 'Diálogo de la lengua'.", a: "Valdés", letra: "V"},
    {q: "Con la Y: Poeta español del 27, autor de 'Perfil del aire' y 'Donde habite el olvido'.", a: "Luis Cernuda", letra: "L"},
    {q: "Con la Z: Novelista aragonesa contemporánea, autora de 'El círculo de Viena'.", a: "Zúñiga", letra: "Z"},
    {q: "Con la A: Novelista rusa autora de 'El manantial' y 'La rebelión de Atlas'.", a: "Ayn Rand", letra: "A"},
    {q: "Con la B: Dramaturgo irlandés, Premio Nobel, autor de 'Esperando a Godot'.", a: "Beckett", letra: "B"},
    {q: "Con la C: Novelista colombiano autor de 'Cien años de soledad'.", a: "García Márquez", letra: "G"},
    {q: "Con la D: Escritora inglesa autora de 'Orgullo y prejuicio' y 'Sentido y sensibilidad'.", a: "Jane Austen", letra: "J"},
    {q: "Con la E: Poeta norteamericano autor de 'Hojas de hierba'.", a: "Whitman", letra: "W"},
    {q: "Con la F: Novelista ruso autor de 'Los hermanos Karamazov'.", a: "Dostoievski", letra: "D"},
    {q: "Con la G: Poeta alemán del clasicismo, autor de 'Fausto' y 'Las penas del joven Werther'.", a: "Goethe", letra: "G"},
    {q: "Con la H: Novelista estadounidense autor de 'El viejo y el mar', Premio Nobel.", a: "Hemingway", letra: "H"},
    {q: "Con la I: Novelista japonesa autora de 'La tienda de Kokoro'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Novelista irlandés autor de 'Ulises' y 'Dublineses'.", a: "Joyce", letra: "J"},
    {q: "Con la K: Novelista japonés Premio Nobel, autor de 'El país de la nieve'.", a: "Kawabata", letra: "K"},
    {q: "Con la L: Novelista portugués Premio Nobel, autor de 'Ensayo sobre la ceguera'.", a: "Saramago", letra: "S"},
    {q: "Con la M: Poeta austriaco de principios del siglo XX, autor de 'Elegías de Duino'.", a: "Rilke", letra: "R"},
    {q: "Con la N: Novelista nigeriano Premio Nobel, autor de 'Todo se derrumba'.", a: "Achebe", letra: "A"},
    {q: "Con la O: Novelista inglesa autora de '1984' y 'Rebelión en la granja'.", a: "Orwell", letra: "O"},
    {q: "Con la P: Poeta chileno Premio Nobel, autor de 'Veinte poemas de amor y una canción desesperada'.", a: "Pablo Neruda", letra: "P"},
    {q: "Con la Q: Novelista china Premio Nobel de 2012, escritora de 'El clan del sorgo rojo'.", a: "Quindao", letra: "Q"},
    {q: "Con la R: Novelista sudafricana, Premio Nobel, autora de 'Julio'.", a: "Gordimer", letra: "G"},
    {q: "Con la S: Novelista sueco autor de la trilogía Millennium ('Los hombres que no amaban a las mujeres').", a: "Stieg Larsson", letra: "S"},
    {q: "Con la T: Novelista estadounidense autora de 'Beloved', Premio Nobel.", a: "Toni Morrison", letra: "T"},
    {q: "Con la U: Escritora canadiense autora de 'El cuento de la criada'.", a: "Atwood", letra: "A"},
    {q: "Con la V: Novelista francés del siglo XIX, autor de 'Los miserables' y 'Nuestra Señora de París'.", a: "Victor Hugo", letra: "V"},
    {q: "Con la W: Escritora inglesa, pionera del modernismo literario, autora de 'La señora Dalloway'.", a: "Woolf", letra: "W"},
    {q: "Con la X: Novelista chino Premio Nobel de 2000, autor de 'La montaña del alma'.", a: "Xingjian", letra: "X"},
    {q: "Con la Y: Escritora israelí autora de 'My Michael'.", a: "Amos Oz", letra: "A"},
    {q: "Con la Z: Novelista iraní exiliada, autora de 'Leer Lolita en Teherán'.", a: "Zafar Nafisi", letra: "Z"},
    {q: "Con la A: Figura retórica que consiste en hablar a seres ausentes, muertos o abstractos.", a: "apóstrofe", letra: "A"},
    {q: "Con la B: Composición lírica medieval de tema moral o satírico con estribillo.", a: "balada", letra: "B"},
    {q: "Con la C: Relato en verso que narra las hazañas de un héroe de la epopeya medieval.", a: "cantar de gesta", letra: "C"},
    {q: "Con la D: Obra dramática breve, de carácter cómico, que se representaba entre los actos.", a: "drama", letra: "D"},
    {q: "Con la E: Poema extenso de tono elevado que narra las hazañas de un héroe o pueblo.", a: "epopeya", letra: "E"},
    {q: "Con la F: Figura retórica en la que se da a entender lo contrario de lo que se dice.", a: "figura", letra: "F"},
    {q: "Con la G: Composición poética bucólica de tema pastoril y amoroso.", a: "glosa", letra: "G"},
    {q: "Con la H: Figura retórica que consiste en alterar el orden lógico de los elementos.", a: "hipérbaton", letra: "H"},
    {q: "Con la I: Figura literaria que consiste en decir lo contrario de lo que se piensa.", a: "ironía", letra: "I"},
    {q: "Con la J: Composición lírica mozárabe, breve y amorosa, la más antigua en romance.", a: "jarcha", letra: "J"},
    {q: "Con la K: Voz japonesa que denomina la poesía breve de 17 sílabas en tres versos.", a: "haiku", letra: "H"},
    {q: "Con la L: Composición poética de tema fúnebre que llora la muerte de alguien.", a: "lamento", letra: "L"},
    {q: "Con la M: Figura retórica que sustituye un término por otro con el que guarda relación de contigüidad.", a: "metonimia", letra: "M"},
    {q: "Con la N: Narrador que cuenta los hechos desde dentro de la historia, siendo protagonista.", a: "narrador protagonista", letra: "N"},
    {q: "Con la O: Discurso o composición poética en que se habla o exclama ante un ser imaginario.", a: "oda", letra: "O"},
    {q: "Con la P: Combinación de palabras contradictorias que producen un efecto expresivo.", a: "paradoja", letra: "P"},
    {q: "Con la Q: Figura retórica que se ocupa de la pronunciación o dicción correctas.", a: "quiasmo", letra: "Q"},
    {q: "Con la R: Figura retórica que consiste en repetir palabras al comienzo de frases sucesivas.", a: "repetición", letra: "R"},
    {q: "Con la S: Composición lírica de catorce versos endecasílabos, dos cuartetos y dos tercetos.", a: "soneto", letra: "S"},
    {q: "Con la T: Género dramático que busca el horror y el terror del espectador con trágico final.", a: "tragedia", letra: "T"},
    {q: "Con la U: Tipo de novela que presenta una sociedad ideal e irrealizable.", a: "utopía", letra: "U"},
    {q: "Con la V: Estudio de la medida y ritmo de los versos de una composición poética.", a: "versificación", letra: "V"},
    {q: "Con la X: Nombre del protagonista de la novela 'Don Quijote', su alter ego real.", a: "Alonso Quijano", letra: "A"},
    {q: "Con la Y: Técnica narrativa que salta en el tiempo hacia adelante rompiendo la linealidad.", a: "flashforward", letra: "F"},
    {q: "Con la Z: Composición dramática española en la que se alternan el canto y la declamación.", a: "zarzuela", letra: "Z"},
    {q: "Con la A: Obra de Dante Alighieri donde el poeta viaja por el infierno, el purgatorio y el paraíso.", a: "Divina Comedia", letra: "D"},
    {q: "Con la B: Primera novela de la escritora inglesa Charlotte Brontë.", a: "Brontë", letra: "B"},
    {q: "Con la C: Nobel francés de 1957, autor de 'El extranjero' y 'La caída'.", a: "Camus", letra: "C"},
    {q: "Con la D: Novela de Miguel de Cervantes considerada la primera novela moderna.", a: "Don Quijote", letra: "D"},
    {q: "Con la E: Nobel de Literatura de 2004, escritora austriaca de 'La pianista'.", a: "Elfriede Jelinek", letra: "E"},
    {q: "Con la F: Premio Nobel de 2007, novelista inglesa autora de 'El cuaderno dorado'.", a: "Doris Lessing", letra: "D"},
    {q: "Con la G: Novela de Gabriel García Márquez sobre cien años de historia de la familia Buendía.", a: "Cien años de soledad", letra: "C"},
    {q: "Con la H: Obra poética del siglo VIII a.C. atribuida a Homero, que narra la guerra de Troya.", a: "Ilíada", letra: "I"},
    {q: "Con la I: Premio Nobel de 2017, escritor japonés-británico autor de 'Lo que queda del día'.", a: "Ishiguro", letra: "I"},
    {q: "Con la J: Premio Nobel de 1913, poeta bengalí autor de 'Gitanjali'.", a: "Tagore", letra: "T"},
    {q: "Con la K: Nobel polaca de 2018, autora de 'Los errantes' y 'El alma perdida'.", a: "Olga Tokarczuk", letra: "O"},
    {q: "Con la L: Nobel de Literatura de 1962, novelista estadounidense autor de 'Las uvas de la ira'.", a: "Steinbeck", letra: "S"},
    {q: "Con la M: Nobel de Literatura de 2016, músico y poeta estadounidense autor de 'Blowin' in the Wind'.", a: "Bob Dylan", letra: "B"},
    {q: "Con la N: Nobel australiano de 1973, primer autor australiano en recibir el galardón.", a: "Patrick White", letra: "P"},
    {q: "Con la O: Premio Nobel de 2006, novelista turco autor de 'Nieve' y 'El museo de la inocencia'.", a: "Orhan Pamuk", letra: "O"},
    {q: "Con la P: Novela de Marcel Proust compuesta por siete volúmenes, un hito de la literatura del siglo XX.", a: "En busca del tiempo perdido", letra: "E"},
    {q: "Con la Q: Premio Nobel de 1961, autor yugoslavo de 'El puente sobre el Drina'.", a: "Andrić", letra: "A"},
    {q: "Con la R: Premio Nobel de Literatura de 1999, novelista alemán autor de 'El tambor de hojalata'.", a: "Günter Grass", letra: "G"},
    {q: "Con la S: Premio Nobel de Literatura de 1925, dramaturgo irlandés autor de 'Pygmalion'.", a: "Shaw", letra: "S"},
    {q: "Con la T: Premio Nobel de Literatura de 1994, novelista japonés autor de 'Una cuestión personal'.", a: "Oe Kenzaburo", letra: "O"},
    {q: "Con la U: Premio Nobel de Literatura de 1988, escritor egipcio y primer árabe en recibirlo.", a: "Naguib Mahfuz", letra: "N"},
    {q: "Con la V: Premio Nobel de Literatura de 1910, autor alemán de 'Los Buddenbrook'.", a: "Thomas Mann", letra: "T"},
    {q: "Con la W: Premio Nobel de Literatura de 1923, poeta irlandés autor de 'La torre'.", a: "William Butler Yeats", letra: "W"},
    {q: "Con la X: Premio Nobel de Literatura de 1969, novela irlandesa de Samuel Beckett.", a: "Esperando a Godot", letra: "E"},
    {q: "Con la Y: Premio Nobel de Literatura de 2010, novelista peruano autor de 'La fiesta del chivo'.", a: "Mario Vargas Llosa", letra: "M"},
    {q: "Con la Z: Premio Nobel de Literatura de 1966, novelista judía de lengua yídish, Shmuel ___.", a: "Agnon", letra: "A"},
    {q: "Con la A: Movimiento artístico y literario de principios del siglo XX que proclama la ruptura con la tradición.", a: "avant-garde", letra: "A"},
    {q: "Con la B: Movimiento literario estadounidense de los años 50, con Kerouac y Ginsberg.", a: "beat", letra: "B"},
    {q: "Con la C: Conjunto de escritores españoles nacidos hacia 1898 que reaccionaron ante el desastre colonial.", a: "Generación del 98", letra: "G"},
    {q: "Con la D: Movimiento literario y artístico de principios del siglo XX, absurdo y provocador.", a: "dadaísmo", letra: "D"},
    {q: "Con la E: Tendencia literaria española de posguerra que retrata la realidad social con intención crítica.", a: "existencialismo", letra: "E"},
    {q: "Con la F: Movimiento literario del siglo XIX que busca la representación objetiva de la realidad.", a: "realismo", letra: "R"},
    {q: "Con la G: Grupo de poetas españoles de los años 20, entre ellos Lorca, Alberti y Cernuda.", a: "Generación del 27", letra: "G"},
    {q: "Con la H: Corriente literaria que subraya el papel de la historia en la sociedad.", a: "historicismo", letra: "H"},
    {q: "Con la I: Movimiento literario del siglo XIX que exalta la emoción, la naturaleza y la libertad.", a: "Romanticismo", letra: "R"},
    {q: "Con la J: Generación literaria española de los años 70, llamada también 'los novísimos'.", a: "Generación de los 70", letra: "G"},
    {q: "Con la K: Movimiento artístico centroeuropeo de expresión interna de la angustia y la emoción.", a: "Expresionismo", letra: "E"},
    {q: "Con la L: Movimiento literario hispanoamericano de los años 60-70 que explora nuevas técnicas narrativas.", a: "boom latinoamericano", letra: "B"},
    {q: "Con la M: Tendencia literaria que combina lo real con lo fantástico de forma natural.", a: "realismo mágico", letra: "R"},
    {q: "Con la N: Movimiento literario de principios del siglo XX que explora el subconsciente.", a: "Surrealismo", letra: "S"},
    {q: "Con la O: Corriente literaria española del siglo XX caracterizada por la objetividad y la escasez de argumento.", a: "objetivismo", letra: "O"},
    {q: "Con la P: Movimiento literario europeo del siglo XVI centrado en el hombre y los clásicos grecolatinos.", a: "humanismo", letra: "H"},
    {q: "Con la Q: Poesía de los años 70 que rompe con el lenguaje convencional y emplea referencias culturales diversas.", a: "poesía novísima", letra: "P"},
    {q: "Con la R: Tendencia del siglo XIX que lleva el realismo hasta el retrato más crudo y descarnado de la sociedad.", a: "Naturalismo", letra: "N"},
    {q: "Con la S: Movimiento literario español de principios del XX de renovación estética, con Valle-Inclán y Jiménez.", a: "Modernismo", letra: "M"},
    {q: "Con la T: Corriente filosófico-literaria de postguerra que parte de la angustia y la libertad del individuo.", a: "existencialismo", letra: "E"},
    {q: "Con la U: Movimiento vanguardista español fundado en 1918 por Ramón Gómez de la Serna.", a: "ultraísmo", letra: "U"},
    {q: "Con la V: Conjunto de poetas que renovaron la lírica española entre 1920 y 1936.", a: "Generación del 27", letra: "G"},
    {q: "Con la W: Tendencia literaria hispanoamericana que introduce elementos fantásticos en la narrativa realista.", a: "realismo mágico", letra: "R"},
    {q: "Con la X: Movimiento poético español de los años 20 impulsado por Gerardo Diego y Juan Larrea.", a: "creacionismo", letra: "C"},
    {q: "Con la Y: Corriente vanguardista española que renovó la poesía a través de la imagen irracional.", a: "ultraísmo", letra: "U"},
    {q: "Con la Z: Tendencia artística que rechaza el arte establecido y busca la provocación.", a: "dadaísmo", letra: "D"},
    {q: "Con la A: Novela de Leon Tolstói sobre la aristocracia rusa y la guerra napoleónica.", a: "Ana Karenina", letra: "A"},
    {q: "Con la B: Novela de Herman Melville sobre la persecución de una ballena blanca.", a: "Moby Dick", letra: "M"},
    {q: "Con la C: Novela de Charles Dickens sobre la vida de un huérfano en la Inglaterra victoriana.", a: "Copperfield", letra: "C"},
    {q: "Con la D: Novela de Umberto Eco que es un thriller filosófico ambientado en un monasterio medieval.", a: "El nombre de la rosa", letra: "E"},
    {q: "Con la E: Novela de Gustave Flaubert sobre el adulterio en la Francia rural del siglo XIX.", a: "Madame Bovary", letra: "M"},
    {q: "Con la F: Obra de William Shakespeare en la que el príncipe de Dinamarca venga a su padre.", a: "Hamlet", letra: "H"},
    {q: "Con la G: Novela de Fiódor Dostoievski sobre un joven que asesina a una usurera.", a: "Crimen y castigo", letra: "C"},
    {q: "Con la L: Obra de Virgilio que narra las aventuras de Eneas desde Troya hasta Italia.", a: "La Eneida", letra: "L"},
    {q: "Con la I: Novela de Franz Kafka sobre Joseph K., acusado de un crimen que nunca se le revela.", a: "El proceso", letra: "E"},
    {q: "Con la J: Obra de Sófocles sobre el rey que mató a su padre y se casó con su madre sin saberlo.", a: "Edipo Rey", letra: "E"},
    {q: "Con la K: Novela de Marcel Proust que es el primero de los siete volúmenes de 'En busca del tiempo perdido'.", a: "Por el camino de Swann", letra: "P"},
    {q: "Con la L: Poema épico medieval sobre el caballero Rolando y la batalla de Roncesvalles.", a: "Cantar de Roldán", letra: "C"},
    {q: "Con la M: Obra de Shakespeare que narra los celos del general moro que termina asesinando a su esposa.", a: "Otelo", letra: "O"},
    {q: "Con la N: Novela de Aldous Huxley sobre una sociedad distópica del futuro donde el placer es obligatorio.", a: "Un mundo feliz", letra: "U"},
    {q: "Con la N: Novela distópica de George Orwell ambientada en el año de su título, donde el Gran Hermano todo lo vigila.", a: "Nineteen Eighty-Four", letra: "N"},
    {q: "Con la P: Obra clásica griega de Platón en forma de diálogos que reflexiona sobre la sociedad ideal.", a: "La República", letra: "L"},
    {q: "Con la Q: Novela corta de Albert Camus sobre un hombre que mata a un árabe en una playa sin motivo claro.", a: "El extranjero", letra: "E"},
    {q: "Con la R: Obra de Shakespeare sobre dos jóvenes de familias enemigas en Verona.", a: "Romeo y Julieta", letra: "R"},
    {q: "Con la S: Novela de Miguel Delibes sobre un maestro rural en la Castilla de los años 60.", a: "El camino", letra: "E"},
    {q: "Con la T: Novela de Emile Zola sobre las minas de carbón y los obreros del norte de Francia.", a: "Germinal", letra: "G"},
    {q: "Con la U: Novela de James Joyce ambientada en un solo día en Dublín, estructurada como la Odisea.", a: "Ulises", letra: "U"},
    {q: "Con la V: Novela de Stendhal cuyo título es el color de la milicia y el clero en la Francia del XIX.", a: "Rojo y negro", letra: "R"},
    {q: "Con la W: Clásico inglés de Wilde que reflexiona sobre la superficialidad y la doble moral victoriana.", a: "El retrato de Dorian Gray", letra: "E"},
    {q: "Con la X: Obra de Esquilo que narra el juicio de Orestes por matar a su madre.", a: "La Orestíada", letra: "L"},
    {q: "Con la Y: Novela de D.H. Lawrence sobre el amor prohibido entre la esposa de un minero y un poeta.", a: "Hijos y amantes", letra: "H"},
    {q: "Con la Z: Novela de Émile Zola protagonizada por una mujer que usa su belleza para ascender socialmente.", a: "Nana", letra: "N"},
    {q: "Con la A: Héroe griego protagonista de la Ilíada, el más veloz y temible guerrero aqueo.", a: "Aquiles", letra: "A"},
    {q: "Con la B: Monstruo mitológico con cuerpo de toro y cabeza de hombre, encerrado en el laberinto de Creta.", a: "Minotauro", letra: "M"},
    {q: "Con la C: Héroe épico medieval castellano que reconquistó Valencia, llamado Rodrigo Díaz de Vivar.", a: "Cid", letra: "C"},
    {q: "Con la D: Diosa griega de la caza y la luna, virgen y arquera.", a: "Diana", letra: "D"},
    {q: "Con la E: Rey de Ítaca, protagonista de la Odisea, famoso por su astucia.", a: "Edipo", letra: "E"},
    {q: "Con la F: Dios griego del fuego que robó el fuego del Olimpo para dárselo a los hombres.", a: "Prometeo", letra: "P"},
    {q: "Con la G: Gigante de la mitología griega condenado a sostener el cielo sobre sus hombros.", a: "Atlas", letra: "A"},
    {q: "Con la H: Semidiós griego que realizó doce trabajos como expiación, hijo de Zeus.", a: "Hércules", letra: "H"},
    {q: "Con la I: Personaje mítico que voló demasiado cerca del sol con sus alas de cera.", a: "Ícaro", letra: "I"},
    {q: "Con la J: Hijo del rey de Cólquida, líder de los Argonautas que buscó el Vellocino de Oro.", a: "Jasón", letra: "J"},
    {q: "Con la L: Mujer de la mitología griega cuya curiosidad la llevó a abrir una caja liberando todos los males.", a: "Pandora", letra: "P"},
    {q: "Con la M: Musa de la Historia en la mitología griega.", a: "Clío", letra: "C"},
    {q: "Con la N: Diosa griega de la victoria, representada con alas.", a: "Niké", letra: "N"},
    {q: "Con la O: Dios griego del mar, hermano de Zeus, armado con un tridente.", a: "Poseidón", letra: "P"},
    {q: "Con la P: Ser mitológico mitad hombre mitad caballo.", a: "Centauro", letra: "C"},
    {q: "Con la Q: Serpiente mitológica cuya mirada convertía en piedra a quien la miraba.", a: "Quimera", letra: "Q"},
    {q: "Con la R: Rey de los dioses en la mitología nórdica, dios de la sabiduría y la guerra.", a: "Odín", letra: "O"},
    {q: "Con la S: Monstruo marino de la mitología griega de seis cabezas situado frente a Caribdis.", a: "Escila", letra: "E"},
    {q: "Con la T: Titán condenado a empujar eternamente una roca cuesta arriba que siempre cae.", a: "Sísifo", letra: "S"},
    {q: "Con la U: Dios romano de la guerra, equivalente al Ares griego.", a: "Marte", letra: "M"},
    {q: "Con la V: Diosa romana del amor y la belleza, equivalente a la Afrodita griega.", a: "Venus", letra: "V"},
    {q: "Con la W: Bestia del folclore germánico, hombre que se transforma en lobo.", a: "Werwolf", letra: "W"},
    {q: "Con la X: Rey de los dioses olímpicos, señor del rayo y el trueno.", a: "Zeus", letra: "Z"},
    {q: "Con la Y: Ser alado de la mitología griega que habitaba el Parnaso e inspiraba a los artistas.", a: "Musa", letra: "M"},
    {q: "Con la Z: Dios del vino, la fertilidad y el teatro en la mitología griega.", a: "Zeus", letra: "Z"},
    {q: "Con la A: Primera obra literaria de la literatura española, poema épico sobre el Cid.", a: "Cantar de Mio Cid", letra: "C"},
    {q: "Con la B: Escritor español del siglo XIV, autor del 'Libro del buen amor'.", a: "Arcipreste de Hita", letra: "A"},
    {q: "Con la C: Novela renacentista española que relata los amores de Calisto y Melibea.", a: "Celestina", letra: "C"},
    {q: "Con la D: Don Juan es protagonista de 'El burlador de Sevilla', atribuida a este escritor del Barroco.", a: "Tirso de Molina", letra: "T"},
    {q: "Con la E: Personaje de la literatura española, escudero de don Quijote.", a: "Sancho Panza", letra: "S"},
    {q: "Con la F: Género literario del Renacimiento español, protagonizado por caballeros andantes.", a: "novela de caballerías", letra: "N"},
    {q: "Con la G: Prosa didáctica medieval española de Alfonso X que contenía cuentos y fábulas.", a: "Calila e Dimna", letra: "C"},
    {q: "Con la H: Autor del 'Lazarillo de Tormes', primer antihéroe de la literatura española.", a: "Anónimo", letra: "A"},
    {q: "Con la I: Libro de cuentos de don Juan Manuel que contiene la historia 'Lo que sucedió a un deán de Santiago'.", a: "El conde Lucanor", letra: "E"},
    {q: "Con la J: Poeta judío medieval español que escribió en hebreo y árabe, nacido en Málaga.", a: "Ibn Gabirol", letra: "I"},
    {q: "Con la K: Nombre del rey visigodo que protagoniza el 'Cantar de Mio Cid' como figura de autoridad.", a: "Alfonso VI", letra: "A"},
    {q: "Con la L: Escritor del Barroco español, autor de 'La vida es sueño' y 'El alcalde de Zalamea'.", a: "Calderón de la Barca", letra: "C"},
    {q: "Con la M: Novela picaresca del siglo XVI, primera de género, cuyo protagonista es un lazarillo.", a: "Lazarillo de Tormes", letra: "L"},
    {q: "Con la N: Santa española del siglo XVI, reformadora del Carmelo y escritora mística.", a: "Teresa de Ávila", letra: "T"},
    {q: "Con la O: Mística española del siglo XVI y doctor de la Iglesia, autor de 'Noche oscura del alma'.", a: "San Juan de la Cruz", letra: "S"},
    {q: "Con la P: Poeta renacentista español que introdujo el verso endecasílabo, amigo de Boscán.", a: "Garcilaso de la Vega", letra: "G"},
    {q: "Con la Q: Critico literario que describe a don Quijote como 'el primer hombre moderno'.", a: "quijotesco", letra: "Q"},
    {q: "Con la R: Escritor del Siglo de Oro español, autor de 'El perro del hortelano'.", a: "Lope de Vega", letra: "L"},
    {q: "Con la S: Libro de cuentos medievales de carácter didáctico de don Juan Manuel.", a: "El Conde Lucanor", letra: "E"},
    {q: "Con la T: Dramaturgo español del Barroco, autor de 'La verdad sospechosa'.", a: "Tirso de Molina", letra: "T"},
    {q: "Con la U: Estrofa más usada en la poesía medieval española, de cuatro versos octosílabos.", a: "cuaderna vía", letra: "C"},
    {q: "Con la V: Poeta y novelista español del siglo XIX, autor de 'Pepita Jiménez'.", a: "Valera", letra: "V"},
    {q: "Con la W: Escritor asturiano del siglo XIX, autor de la monumental 'La Regenta'.", a: "Leopoldo Alas Clarín", letra: "L"},
    {q: "Con la X: Rey Alfonso que impulsó la prosa científica y literaria castellana en el siglo XIII.", a: "Alfonso X el Sabio", letra: "A"},
    {q: "Con la Y: Poeta y dramaturgo sevillano del Siglo de Oro, autor de 'Fuente Ovejuna'.", a: "Lope de Vega", letra: "L"},
    {q: "Con la Z: Escritor del Siglo de Oro español, autor de 'El criticón' y 'Oráculo manual'.", a: "Baltasar Gracián", letra: "B"},
    {q: "Con la A: Poeta de la Generación del 27, autor de 'Marinero en tierra' y 'La arboleda perdida'.", a: "Alberto Alberti", letra: "A"},
    {q: "Con la B: Poeta del 27, autor de 'Cal y canto' y 'Sobre los ángeles'.", a: "Rafael Alberti", letra: "R"},
    {q: "Con la C: Poeta de la Generación del 27, autor de 'Poema del cante jondo'.", a: "Federico García Lorca", letra: "F"},
    {q: "Con la D: Poeta español de la Generación del 27, autor de 'Un río, un amor' y exiliado en Francia.", a: "Luis Cernuda", letra: "L"},
    {q: "Con la E: Poeta español del 27, autor de 'Ámbito' y 'Espadas como labios' (Vicente ___-xandre).", a: "Aleixandre", letra: "A"},
    {q: "Con la F: Poema de Lorca que recoge canciones andaluzas del cante jondo.", a: "Poema del cante jondo", letra: "P"},
    {q: "Con la G: Poeta y dramaturgo del 27, autor de 'Bodas de sangre' y 'Yerma'.", a: "García Lorca", letra: "G"},
    {q: "Con la H: Poeta español de posguerra, autor de 'Hijos de la ira'.", a: "Dámaso Alonso", letra: "D"},
    {q: "Con la I: Poeta extremeño de posguerra, autor de 'Ancia' y 'Noche abierta'.", a: "Claudio Rodríguez", letra: "C"},
    {q: "Con la J: Poeta sevillano autor de 'Las piedras del cielo' y 'Canto General'.", a: "Pablo Neruda", letra: "P"},
    {q: "Con la K: Poeta vasco contemporáneo que escribe en castellano y euskera.", a: "Kirmen Uribe", letra: "K"},
    {q: "Con la L: Poeta español de posguerra autor de 'Don de la ebriedad'.", a: "Claudio Rodríguez", letra: "C"},
    {q: "Con la M: Poeta sevillano del 27, autor de 'Cántico' y Premio Cervantes en 1993.", a: "Jorge Guillén", letra: "J"},
    {q: "Con la N: Poeta chilena, primera latinoamericana en ganar el Premio Nobel, en 1945.", a: "Gabriela Mistral", letra: "G"},
    {q: "Con la O: Poeta barcelonés del 27, autor de 'Nocturnos de Chopin'.", a: "Pedro Salinas", letra: "P"},
    {q: "Con la P: Poeta de la Generación del 27, autor de 'La voz a ti debida'.", a: "Pedro Salinas", letra: "P"},
    {q: "Con la Q: Poeta salmantino del siglo XX, autor de 'El contemplado' y 'Todo más claro'.", a: "Pedro Salinas", letra: "P"},
    {q: "Con la R: Poeta español, autor de 'Campos de Castilla' y vinculado al 98, de nombre Antonio.", a: "Machado", letra: "M"},
    {q: "Con la S: Poeta de la Generación del 27, autor de 'Alondra de verdad'.", a: "Gerardo Diego", letra: "G"},
    {q: "Con la T: Poeta catalán del siglo XX, vinculado al surrealismo (Joan ___).", a: "Tàpies", letra: "T"},
    {q: "Con la U: Poeta y ensayista español, autor de 'La realidad y el deseo', en exilio en México.", a: "Luis Cernuda", letra: "L"},
    {q: "Con la V: Poeta de la Generación del 98, autor de 'Soledades, galerías y otros poemas'.", a: "Antonio Machado", letra: "A"},
    {q: "Con la W: Poeta estadounidense que influyó en la poesía española del 27 con su visión visionaria.", a: "Walt Whitman", letra: "W"},
    {q: "Con la X: Poeta de la Generación del 27, Premio Nobel de Literatura en 1977 (Vicente ___).", a: "Aleixandre", letra: "A"},
    {q: "Con la Y: Poeta asturiano de posguerra conocido por su poesía social.", a: "Gloria Fuertes", letra: "G"},
    {q: "Con la Z: Poeta español contemporáneo autor de 'El libro de los pasos'.", a: "Luis García Montero", letra: "L"}
  ]
});